### ISSUE TITLE
Discover page and landing page show different titles for the same resource.

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#826] opened 2015-12-14 18:07 UTC
When I created this resource https://www.hydroshare.org/resource/c813e5c26ba24222ba1b73f43943aca6/
 I named it "Raster 1". Later I changed its title to "Charles de Gaulle Airport, Paris".
Now on "My Resource" page and the resource landing page the title is correct. But discover page still shows old title.

![image](https://cloud.githubusercontent.com/assets/10070599/11789244/82f6c94a-a252-11e5-9619-25247a23937e.png)

![image](https://cloud.githubusercontent.com/assets/10070599/11789282/b53236d8-a252-11e5-9311-a85bb9c8e66f.png)

**Comment by hyi** [comment] 2015-12-14 18:10
@zhiyuli @dtarb @alvacouch This error is caused by non-on-demand solr index update as well. We are currently doing solr index update each midnight, which means new changes made will not get picked up by discovery page until the next day after solr index update is run. This will be resolved once on-demand solr index update is implemented which I plan to do after AGU.

**Comment by dtarb** [comment] 2015-12-14 22:37
Would it be possible to run solr index more frequently (e.g every hour) during AGU to mitigate this

**Comment by hyi** [comment] 2015-12-14 23:44
@dtarb @alvacouch @zhiyuli Have just updated cron job on www to run solr index update every 30 minutes. Let me know if you notice any issues with it.

**Comment by dtarb** [comment] 2015-12-15 13:24
There is still quirkiness that appears more than waiting for a solr update.  I just checked (5:20 am San Francisco time) and did a search on netcdf.  A resource created with Jon Pollak during AGU demos yesterday appears with the title untitled in the discover listing, but if you click in the link to it you see that its title is "Rapid Result".  This title was automatically populated when it was loaded from a netcdf file that has this title.

**Comment by alvacouch** [comment] 2016-05-02 14:20
Seems to be addressed in current release.

**Comment by hyi** [comment] 2016-05-17 14:59
@zhiyuli Can you verify on www and see if this issue has been resolved? If so, please close it.

**Closed** 2016-06-02 14:32 UTC
Labels: Close Me!, Discovery
