### ISSUE TITLE
Discovery only shows most frequent 100 options for author, contributor, subject, etc. 

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2599] opened 2018-02-01 19:58 UTC
@dtarb @Lizabrazil @ChristinaB Unbeknownst to most people, SOLR faceting only returns the 100 most frequent options by default. The current labels for facets do not capture that. See PR #2578. 

The impact of this is that if I create a resource, and then search for my own name in the owners, I won't see it in the facet marked "Filter by owner". Since there are now 400+ Authors, the situation is worse there.  This makes for a poor user experience. 

The options and their pros and cons: 

1. label `author` facet as "frequent authors" instead of "Filter by author" 

  * Pros: easy to do. 
  * Cons: not as clear a text as "Filter by"

2. expose all authors by frequency. This is a lot of authors. 

  * Cons: unwieldly. Can't figure out how to locate a specific author.  Not workable. 

3. sort all authors by last name. This is again a very long list. This entails not sorting by frequency. 

  * Pros: all authors are listed. 
  * Cons: loading all authors causes performance degradation on the discovery page that only gets worse with time and the number of contributing authors!

4. Get rid of `authors` facet entirely, and instead, autocomplete queries of the form `author:Tar` 

  * Pros: loading is fast, auto-completion subsumes facet functions. Easy to program in SOLR.  
  * Cons: difficult to program in JavaScript. 

Same disparaging comments apply to facets `owner`, `contributor`. 

For facets `subject` and `variable`, the situation is worse, because there are meaningless subjects in the list, as well as variable codes instead of variable names.  

Facets `resource type`, `coverage type`,  and `availability` are not problematic because their values range over controlled vocabularies. 

I think that in order for the interface to scale with the number of contributing authors, we need option 4.

**Comment by cuahsimarko** [comment] 2020-12-15 18:22
@martinseul can you close this if the Issue is covered by the design decision to limit to a set number of items, while sorting by alphabetical order within the checkbox facets? Otherwise, will need a design conversation with people.

**Comment by cuahsimarko** [comment] 2021-02-02 16:04
@alvacouch @martinseul I think we can close this. The design of current Discover caps at a set quantity of authors.

**Closed by cuahsimarko** 2021-02-02 16:04 UTC
Labels: Discover, Naming, design phase needed, in progress
