### ISSUE TITLE
Unable to Formally Publish Resource

### ISSUE THREAD

**Issue by AmberSJones** [hydroshare/hydroshare#1436] opened 2016-09-06 16:42 UTC
I attempted to formally publish a resource and received an error. This is a dataset for which we need a formal publication/DOI in the next few days for citation in a journal article. Screenshots are below:

1. The Resource:
![image](https://cloud.githubusercontent.com/assets/5023186/18282410/472a3ade-741e-11e6-8253-39cf156dde97.png)
2. Clicked on the Publish icon and agreed to the HydroShare Publishers' agreement:
![image](https://cloud.githubusercontent.com/assets/5023186/18282448/677cd648-741e-11e6-9be4-081226078569.png)
3. Received this error:
![image](https://cloud.githubusercontent.com/assets/5023186/18282475/7a1930e4-741e-11e6-9406-efb41aa285c8.png)

**Comment by mjstealey** [comment] 2016-09-06 16:55
Error as found in the log files:

```python
[06/Sep/2016 16:38:11] ERROR [django.request:256] Internal Server Error: /hsapi/_internal/7ce47150ee344d4e95f2fd7bb4f660ac/publish/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/docker/hydroshare/hs_core/views/__init__.py", line 424, in publish
    hydroshare.publish_resource(request.user, shortkey)
  File "/home/docker/hydroshare/hs_core/hydroshare/resource.py", line 1100, in publish_resource
    response = deposit_res_metadata_with_crossref(resource)
  File "/home/docker/hydroshare/hs_core/hydroshare/resource.py", line 1062, in deposit_res_metadata_with_crossref
    files = {'file': (xml_file_name, res.get_crossref_deposit_xml())}
  File "/home/docker/hydroshare/hs_core/models.py", line 1480, in get_crossref_deposit_xml
    etree.SubElement(depositor, 'email_address').text = settings.DEFAULT_SUPPORT_EMAIL
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'DEFAULT_SUPPORT_EMAIL'
...


[06/Sep/2016 16:41:06] ERROR [django.request:256] Internal Server Error: /hsapi/_internal/7ce47150ee344d4e95f2fd7bb4f660ac/publish/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/docker/hydroshare/hs_core/views/__init__.py", line 424, in publish
    hydroshare.publish_resource(request.user, shortkey)
  File "/home/docker/hydroshare/hs_core/hydroshare/resource.py", line 1100, in publish_resource
    response = deposit_res_metadata_with_crossref(resource)
  File "/home/docker/hydroshare/hs_core/hydroshare/resource.py", line 1062, in deposit_res_metadata_with_crossref
    files = {'file': (xml_file_name, res.get_crossref_deposit_xml())}
  File "/home/docker/hydroshare/hs_core/models.py", line 1480, in get_crossref_deposit_xml
    etree.SubElement(depositor, 'email_address').text = settings.DEFAULT_SUPPORT_EMAIL
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'DEFAULT_SUPPORT_EMAIL'
```

**Comment by horsburgh** [comment] 2016-09-06 17:05
@hyi - this one's a bit of a big deal because the owner of this resource is about to get proofs back on a paper that is citing this dataset. He would like to cite the dataset with a published DOI.  @AmberSJones and I also have another paper that is about to get submitted that is in a similar situation - citing resources in HydroShare.

**Comment by hyi** [comment] 2016-09-06 17:11
@AmberSJones @horsburgh @mjstealey From the error log, I found the issue which is specific to www deploy. The setting for ```DEFAULT_SUPPORT_EMAIL``` is missing on www, but is present on other test VMs such as beta, hence we have not been able to discover this setting issue until this first formal publication attempt. I have manually added this setting in ```local_settings.py``` on www. @AmberSJones could you retry this process to see if you can publish it now?

**Comment by AmberSJones** [comment] 2016-09-06 17:55
No change- I'm experiencing the same error.

**Comment by mjstealey** [comment] 2016-09-06 18:03
@AmberSJones - if you don't mind giving it one more go it would be appreciated.

There was a question as to whether or not the application required a restart to pick up the new settings. We initially wanted to try without issuing a restart, which appears to not work, so we've now restarted the server.

**Comment by AmberSJones** [comment] 2016-09-06 18:55
No problem testing. Looks like it was successful!

![image](https://cloud.githubusercontent.com/assets/5023186/18286693/32e9dd28-7431-11e6-9126-7bdee24a5baf.png)

**Comment by hyi** [comment] 2016-09-06 19:00
@AmberSJones @horsburgh Looks like it has been successful indeed. I have also seen an email coming from admin@crossref.org indicating metadata deposition into crossref is successful, so the nightly running celery task should pick up the updated status tonight and you should see a "Published" sharing status without the note regarding DOI registration, and the DOI should be registered and activated in crossref system.

**Comment by horsburgh** [comment] 2016-09-06 19:23
The crowd goes wild...

Looks like Steven Hall is the owner and the Author of the very first formally published resource in HydroShare.

@hyi - if you are confident that this issue is solved, I'll let you close it.  Thanks for the quick response!

@dtarb

**Comment by hyi** [comment] 2016-09-06 19:27
@horsburgh @AmberSJones I'll close this issue tomorrow after confirming the nightly running celery task picks up the updated status and updates the landing page appropriately for this first formally published resource.

**Comment by dtarb** [comment] 2016-09-06 19:40
Thanks for sorting this out.  It underscores the importance of having testing environments as identical as possible (if identical can be a relative concept) to www, to catch these errors in testing.

**Comment by hyi** [comment] 2016-09-07 13:43
@dtarb @horsburgh @mjstealey @AmberSJones The nightly running celery task checked against crossref API and confirmed this resource has been deposited and registered successfully in crossref system, and updated Django DB and resource landing page to remote the pending note, so everything looks good and this serves as our first formally published resource. Way to go! I am closing this issue now.

**Closed by hyi** 2016-09-07 13:43 UTC
Labels: bug
