### ISSUE TITLE
SUPPORT - Error adding resource

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#375] opened 2015-05-15 13:56 UTC
Email to: support@hydroshare.org
Subject: Error adding resource

I was uploading resources to Hydroserver and a couple times got this funny error. I just wanted to let you guys know that this was happening.

![screen shot 2015-05-15 at 9 54 37 am](https://cloud.githubusercontent.com/assets/5332509/7654092/70c28208-fae8-11e4-9247-8ab1993dfe05.png)

**Comment by ironfroggy** [comment] 2015-05-15 14:06
If you see it again please switch to the copy and paste view and add a
stacktrace to this ticket.

On Fri, May 15, 2015 at 9:56 AM, Michael J. Stealey <
notifications@github.com> wrote:

> Email to: support@hydroshare.org
> Subject: Error adding resource
>
> I was uploading resources to Hydroserver and a couple times got this funny
> error. I just wanted to let you guys know that this was happening.
>
> [image: screen shot 2015-05-15 at 9 54 37 am]
> <https://cloud.githubusercontent.com/assets/5332509/7654092/70c28208-fae8-11e4-9247-8ab1993dfe05.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hydroshare/hydroshare/issues/375>.
>



-- 


*Calvin Spealman*Lead Front-end Developer

calvin@caktusgroup.com <calvin@caktusgroup.com>
www.caktusgroup.com

**Comment by ironfroggy** [comment] 2015-05-15 14:06
This is a duplicate of #374

**Closed by ironfroggy** 2015-05-15 14:06 UTC
Labels: bug
