### ISSUE TITLE
Raster resource creation using files from user federated zone fails

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1771] opened 2017-01-21 22:21 UTC
This problem was first noticed from a failing unit tests that uses user zone federated files for creating a raster resource.

**Comment by alvacouch** [comment] 2017-01-22 13:29
@pkdash. This has come up in my ResourceFile testing. I think I might have even fixed it. But it's part of PR #1687 and not easily separable.

**Comment by pkdash** [comment] 2017-01-30 17:13
@hyi Can you test at the UI level to see if this has been fixed? I know I did a fix to fix the failing test. But I was not able to test for creating raster resource using a file from the user federated zone. I assume you can do this kind of testing. If you let me know that you are able to create a raster resource using a federated file (tif) then I will close this issue.

**Comment by hyi** [comment] 2017-01-30 18:31
@pkdash Just done some testing on www. Creating a raster resource using files from the user zone works as expected. However, when I create an empty raster resource, then add a tif file from the user zone, although extended resource specific metadata is extracted correctly, one extra temporary tif file is added into resource file content which should not happen. See the screen capture below for an example:

![raster_add_file_issue](https://cloud.githubusercontent.com/assets/476302/22436009/468e2578-e6f0-11e6-8f2a-1e8924369dc2.png)

Can you look into this regression issue to see if you can fix it?

**Comment by pkdash** [comment] 2017-01-30 18:49
@hyi Thanks for doing the test. I will look into this additional file issue.

**Comment by pkdash** [comment] 2017-02-01 18:52
@hyi I tried to add a unit test to see if this problem shows up in the test. However, it doesn't. Somehow in the local development environment I need to be able to add a file from user zone to an existing raster resource to be able to debug it.

**Comment by hyi** [comment] 2017-02-01 20:06
@pkdash I will try to see if I can reproduce this issue in my local dev env using dockerized irods containers, and see if I can fix this issue if I can reproduce it.

**Comment by pkdash** [comment] 2017-02-01 20:24
Thanks @hyi . Just to let you know that I was running the unit test using local irods containers which did not reproduce the issue.

**Comment by hyi** [comment] 2017-02-01 21:23
@pkdash I can reproduce this issue in my local dev env using irods containers. Will see if I can find out the cause and make a fix.

**Comment by hyi** [comment] 2017-02-08 21:38
@pkdash I have tested on beta and all appears to be working as expected now. I am leaving it up to you whether you want to close now or you want to do more testing before closing this issue.

**Comment by mjstealey** [comment] 2017-02-16 16:41
presumed to be done

**Closed by mjstealey** 2017-02-16 16:41 UTC
Labels: in progress
