### ISSUE TITLE
Depositing metadata during publication will fail if resource metadata contains invalid characters

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5306] opened 2024-01-11 17:11 UTC
**Description of the bug**
`get_crossref_deposit_xml` will fail if there are non Unicode chars in the abstract, title, etc of the resource.
```
Traceback (most recent call last):
  File "/hydroshare/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/hydroshare/hs_core/management/commands/update_crossref_deposit_all_published_resources.py", line 16, in handle
    response = deposit_res_metadata_with_crossref(resource)
  File "/hydroshare/hs_core/hydroshare/resource.py", line 1029, in deposit_res_metadata_with_crossref
    files = {'file': (xml_file_name, res.get_crossref_deposit_xml())}
  File "/hydroshare/hs_core/models.py", line 4077, in get_crossref_deposit_xml
    etree.SubElement(dataset_node, 'description').text = self.metadata.description.abstract
  File "src/lxml/etree.pyx", line 1042, in lxml.etree._Element.text.__set__
  File "src/lxml/apihelpers.pxi", line 748, in lxml.etree._setNodeText
  File "src/lxml/apihelpers.pxi", line 736, in lxml.etree._createTextNode
  File "src/lxml/apihelpers.pxi", line 1541, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```
[Example run on beta](https://new-hs-ci.hydroshare.org/view/02-Deployment/job/Beta%20deployment/job/beta-hsctl-command/489/console)

**Expected behavior**
We should either sanitize the XML at time of deposit, or better sanitize it in the resource.
We should also notify that metadata contains non-accepted chars (if we don't already)

**Additional information**
Command run using rc-2.12 at 0a5b64cfed01de08478548072d8bc3bd4aae71fe

**Comment by devincowan** [comment] 2024-01-11 17:12
perhaps sanitize with something like
https://stackoverflow.com/questions/1707890/fast-way-to-filter-illegal-xml-unicode-chars-in-python

**Comment by devincowan** [comment] 2024-01-11 17:14
example failing resource:
https://www.hydroshare.org/resource/1a7dc5d6b9fa4253bca442341eef500d/

**Comment by devincowan** [comment] 2024-01-11 17:51
related to #5225

**Comment by dtarb** [comment] 2024-01-13 22:43
Beyond the approach taken in #5307 which seems to be notification at the time publication is requested I think there should be an effort to prevent invalid characters getting in to the metadata in the first place, perhap with a check when metadata is saved that warns a user about characters that will block publication because the metadata can not be published in crossref. We've discussed a lot the special characters problem, so I am hesitant about opening it up again too broadly. We want to respect special characters in peoples names wherever possible, but we now have a definitive case where using some special characters limits a key goal of hydroshare - namely resource publication, and is thus a good reason for keeping them out (or warning users).  In the example resource given https://www.hydroshare.org/resource/1a7dc5d6b9fa4253bca442341eef500d/ it would be good to determine if the issue is characters in the abstract "δ2H and δ18O" or the expression later on "7 h1." that does not display correctly (and I will be interested to see how github renders these strings cut and paste from the resource abstract)

**Comment by devincowan** [comment] 2024-01-19 15:01
Actually for the [example resource](https://www.hydroshare.org/resource/1a7dc5d6b9fa4253bca442341eef500d/), the invalid character is a null between the "h" and "1" in the following section of the abstract:
> "greater than 7 **h1**. The soil"

I agree that it would be best to notify users at the time of entry when they have invalid characters, but I thought it would be very difficult to communicate to them programmatically via the UI, what characters in particular are causing the issue. Taking the example resource I provided, we could write an automated check that finds invalid chars and then provides a message to the user containing the text surrounding the invalid char. In this case it is particularly confusing because the offender is null so they don't actually see any characters (likely they copy/pasted from Word or a PDF). I thought it might just be easier to handle as part of the Human in the Loop review, as it might be easiest communicated by a human rather than programmatically. But we can take a go at it!

The alternative is just to programmatically sanitize any offending characters and provide a notification that we have done so. It feels heavy handed, but we would have to eventually remove the chars anyway. I'm going to explore this option further.

Also, I got to wondering why this resource (and others like it) wasn't having issues when we serialize its metadata into RDF in the bagit. We use [rdflib](https://rdflib.readthedocs.io/en/stable/intro_to_parsing.html#saving-rdf) to create the bag xml files, and that serializer will write a "" into the XML when there's an invalid char. Conversely, [our new Crossref XML generation ](https://github.com/hydroshare/hydroshare/blob/rc-2.12/hs_core/models.py#L4077) uses [lxml.etree](https://lxml.de/compatibility.html)

**Comment by devincowan** [comment] 2024-01-23 16:44
partially mitigated in release 2.12 by https://github.com/hydroshare/hydroshare/pull/5307 which notifies at time of publication. Leaving this open as more work can be done to sanitize the XML at entry/save and notify in the UI

**Comment by pkdash** [comment] 2024-02-06 17:02
@devincowan Have you looked at this helper function (https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L57)? This may be used to sanitize data entry/save and notify in the UI.

**Comment by devincowan** [comment] 2024-02-06 21:40
good call @pkdash I hadn't seen that function. Looks like just what we need!

**Closed** 2024-02-09 13:38 UTC
Labels: bug, Publishing
