### ISSUE TITLE
New Resource Creation: Adding authors enhancement - return to "authors" portion of the page after adding an author

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#2729] opened 2018-04-26 11:57 UTC
I am trying to add multiple authors to my resource. Each time I add one, the page reloads back to the beginning of the page. This is somewhat inconvenient. Suggest changing to either:

1) Switch to an AJAX type function so that the full page doesn't reload with every author add? 

OR

2) Use an Anchor link to reload the page directly scrolled down to the portion about authors, so that I can easily add the next author

**Comment by engineSound** [comment] 2018-06-26 21:29
Editing an author and deleting an author both behave the same way as adding an authror. Taking  feedback from Mark, I am changing them in a batch so they behave consistently to go back to authorship.

**Comment by engineSound** [comment] 2018-07-24 19:40
Adding an anchor broke the Jenkin's test script test_metadata_CRUD.py under hydroshare/hs_core/tests/api/views

**Comment by engineSound** [comment] 2018-10-08 20:20
See also #2556 and #2557 and #1099

**Comment by engineSound** [comment] 2019-04-23 19:09
I've decided to close this one for the sole reason that the behavior doesn't exist any longer due to resource landing page redesign. However I make a note here:  other issues  #2556 and #2557 and #1099 which don't share the same root cause still exist.

**Closed by engineSound** 2019-04-23 19:09 UTC
Labels: Medium Priority
