### ISSUE TITLE
Discover map is slow and behavior awkward

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1479] opened 2016-10-04 14:27 UTC
I am testing discover on beta.hydroshare.org.  I have zoomed to a certain map extent and clicked on the map to get a list of resources at the bottom.  I then click on a filter facet (e.g. time series under filter by subject).

The display first flashes to the list display.  Then the map comes back and is zoomed to a different extent and location, with no resources in the list below the table.  It is counter-intuitive to me that selecting a filter facet on the left should change the map extent.  I was expecting that it may filter the resources selected in the table using the facet.

If I then uncheck the facet I selected the display first flashes to the list view.  Then it goes to the map view and shows me a blank screen for what seems like an awkwardly long time.  Then it is back on a map, with yet another extent that is different from what I started with or from what was there when I selected the facet.

I think that the map extent should only change when a user does something to change it, like zoom or pan or click on a show on map button.  It seems odd for it to change at random in response to selecting or unselecting a facet.

I know we have iterated on this discover interface a lot, but quirky behavior like this keeps coming up, and if it is awkward to us, it will be awkward to users.

**Comment by xuezhaokun** [comment] 2016-10-04 15:02
@dtarb Whenever you make a faceting search, it actually sends the new faceting query back to SOLR and makes a back-end update. SOLR will send back a updated resources list satisfying our new query. This back-end update will force the map to reinitialize. This reinitialization will cause the map extent change, since we always initialize the map extent based on resources we get from SOLR. Whenever users make a faceting search, they need to restart their discovery process. I think the use case you mentioned should be a front-end update. If we want to realize that, I do not think we should use the faceting search feature from SOLR anymore. All we have to do is to a simple front-end filtering. And we only update our resources list when the search text changed. @alvacouch I am not sure whether this is what we want to modify.

The long loading time is caused  by so many polygon overlays we add on our map. Actually the performance is much better than rectangle overlays as we used before. Maybe we can add a loading icon to inactivate the page until the map is completely loaded.

I will take a look on the awkward action that it switches back and forward between list view and map view when refreshing the page.

**Comment by alvacouch** [comment] 2016-10-04 15:29
@xuezhaokun I think the switching back and forth is an artifact of how REST is implemented internally to make the change. 

The problem is not SOLR faceted search, but what one does with it. 

If the SOLR search is executed as an XMLHTTPRequest rather than a global update, you can do what you want with the results. Including leaving the local context alone.

**Comment by xuezhaokun** [comment] 2016-11-30 17:34
I think we have fixed almost all the awkward behaviors in the merged PR.  We do not have a good solution for the slowness issue so far.

**Comment by Lizabrazil** [comment] 2019-04-10 20:25
The map has other issues, like overlapping bounding boxes and messiness in general. We will address this when we redesign the page. @martinseul closing

**Closed by Lizabrazil** 2019-04-10 20:25 UTC
Labels: Discovery, enhancement, geo and maps, in progress, low priority
