### ISSUE TITLE
Composite Resource: Enable Adding Referenced File Content via User Interface

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2796] opened 2018-06-22 21:39 UTC
Add the ability to add references to content file(s) stored outside of HydroShare but available via an HTTP or FTP URL to a HydroShare resource. Detailed description of this functionality is in the discussion Google Doc: https://docs.google.com/document/d/1739C59tEO4SErKidCbYRsZDJYWkpJk4T1Ir07HICVMg/edit 

**NOTE**: We will add references to map services later as part of another issue.

* [x] **Add button to toolbar of the file browser interface** in edit mode on the resource landing page to "Add content from the web." This should display a modal window for adding content from the web. The user will input a URL for the reference in the modal window. The modal window should look like the following.  References to files can be located anywhere within the folder hierarchy of a resource (except nested within other aggregations). 

![image](https://user-images.githubusercontent.com/3485902/44939029-87f00880-ad3f-11e8-9834-c0905026207e.png)

**NOTE**: Initially there will be only one option for content type (add reference to file or website using an FTP or HTTP URL), but we will add additional content types (web services) via additional issues.

* [x] **Create validation for URLs**. When a user specifies a URL as a reference to external content, HydroShare should validate the URL to ensure that a 400 error (content not found) is not returned and that a 401 error (user not authorized) is not returned.

* [x] **Create .url file to store reference.** For each reference, a .URL file will be created that stores the URL of the referenced content. The .url files will be named using the name of the remote file with a .url appended to the end. When displaying .url reference files in the file browser interface, the .url file extension should be removed so the user doesn't see it.

* [x] **Display referenced files in file browser with unique icon(s).** Referenced files (.url files) should show up in the file browser interface with a unique icon that visually indicates that they are referenced from another location.

* [x] **Verify ability to create metadata for a single referenced file (.url file)** (e.g., create a single-file aggregation from the .url reference file). The user should be able to right click on a single .url file and select "Add metadata to file". This will have the same effect as the existing functionality for this action when initiated on any other file stored within HydroShare's file system - an OAI-ORE resource map and aggregation metadata document will be created. See notes for how the OAI-ORE resource map document should be encoded in the Google Doc.

* [ ] **Verify ability to create metadata for a folder containing referenced files** (e.g., create a file-set aggregation from .url reference files in a folder). The user should be able to right click on a folder containing any .url files and select "Add metadata to folder". This will have the same effect as the existing functionality for this action when initiated on a folder with files stored within HydroShare's file system - an OAI-ORE resource map and aggregation metadata document will be created within the folder. See notes for how the OAI-ORE resource map document should be encoded in the Google Doc.

* [x] **Add messaging to user interface for referenced content**. When a resource contains referenced content (of any type), add the following text directly below the Content browser:
>Please note: This resource contains links to external content. Linked content is NOT stored in HydroShare, and we can't guarantee its availability, quality, or security. 

* [x] **Implement packaging rules for download** of resources or parts of resources containing referenced content.
1. Right clicking on an individual .url file and selecting "Download" should download the .url file.
2. Double clicking on an individual .url file should result in the user receiving the following warning, after which HydroShare will redirect a new browser tab to the URL contained in the file.
>The content you have requested to access is not stored in HydroShare, and we can’t guarantee its availability, quality, security, or size. If the externally linked content is large, access may take time.
3. Right clicking on a folder that contains one or more .url files and selecting "Download" should result in the user receiving a zipped file containing the folder's contents as is current behavior.
4. Double clicking on or right clicking on a single referenced file aggregation should be the same as individual referenced files (above).
5. Requesting download of a fileset aggregation containing .url files should be the same as requesting download of a folder except that the zipped file delivered to the user should contain the OAI-ORE resource map and aggregation metadata documents (as is current functionality).
6. Requesting download of an entire resource containing referenced content should return a zipped BagIt bag with all resource map documents, metadata documents, any content files stored within HydroShare's file system, and any .url files (as is current functionality).

* [x] **Disable publication of resources containing referenced content**. As soon as referenced content has been added to a resource, disable the "Publish" button. If all referenced content has been removed from a resource, it can be publishable again. We may also want to remove the message about permanent publication with the URL-encoded DOI below the "How to Cite" for resources that can't be published.

* [x] **Implement an option for modifying the URL for referenced content**. Once a reference has been created and a .url file exists in a resource, an option should be created in the file browser interface to right click on the .url file and select "Edit reference URL."

**Check that the following still work once complete:**
* [x] Copying resource
* [x] Creating a new version of a resource

**Comment by hyi** [comment] 2018-08-13 14:28
@horsburgh I don't see adding referenced content from create resource page mentioned in the task list on this issue. I assume in addition to allowing users to add referenced content from resource landing page after a resource has been created, we should also allow users to create resource using referenced contents initially. Want to confirm with you whether this is the case or not.

**Comment by horsburgh** [comment] 2018-08-13 14:33
@hyi - this is a good question. I debated a bit about whether we should add this to the resource creation page. Once we have consolidated resources on a single resource type (composite), I think the create resource page will go away entirely. So, I'm not sure we want to add new functionality to that page. On the other hand, we've still got some work to do before we no longer require users to select a resource type, which is really the only reason to have that page at the moment.

**Comment by hyi** [comment] 2018-08-13 16:06
@horsburgh Got it. If we got rid of resource creation page, it'd mean the resource would always be created with the default "Untitled resource" and empty contents initially. So there might still be merit to have a resource creation page initially even if we got rid of resource type selection, but that is a UX issue, and it'd most likely work better if we got rid of resource creation page and streamline resource landing page to make editing much easier for users. Agreed we should not consider adding any more feature into resource creation page at this point.

**Comment by horsburgh** [comment] 2018-08-31 03:56
I modeled the messages after those that I had seen on other websites. If you want to change them go ahead. I added the text about clicking on .url files because I'm concerned that users will not know what to do with the .url files once they download them.

**Comment by hyi** [comment] 2018-08-31 13:53
@horsburgh This is not urgent, but if you could ask @Maurier to create an icon for referenced .url files in file browser when he has time, that'd come in handy for me to use while working on this issue.

**Comment by hyi** [comment] 2018-08-31 14:00
@horsburgh Regarding this message: ```The file you have requested to access has a size of XXXX. It is not stored in HydroShare, and we can’t guarantee its availability, quality, or security.``` I suggest to remove the size info as we most likely will not know the size info from the external URL. We could make the message as ```The file you have requested to access is not stored in HydroShare, and we can’t guarantee its availability, quality, or security.```

**Comment by horsburgh** [comment] 2018-08-31 14:42
@hyi - sure, given our conversation the other day I think it's OK to remove the size info. I suggested providing size info so that a user would know what they were asking for. I originally thought that HydroShare could do a header request to get the size info when the reference was created so we could present that information to users. But, I understand that there are reasons that we may not want to do that. Some referenced files may be quite large - as large files stored elsewhere is one of the use cases for referenced content.

**Comment by horsburgh** [comment] 2018-08-31 15:28
@Maurier will work on an icon for you @hyi

**Comment by Maurier** [comment] 2018-08-31 17:36
@hyi 

Here is how you can add the icon:
on https://github.com/hydroshare/hydroshare/blob/develop/theme/static/css/hs-file-icons.css add the following rules:
```
.fb-stack-url {
    color: #607D8B;
}

.fb-view-grid .fb-stack-url .fa-link, .dz-details .fb-stack-url .fa-link {
    top: 4px;
    font-size: 19px;
}

.fb-view-list .fb-stack-url .fa-link {
    top: -4px;
    font-size: 11px;
}
```

on https://github.com/hydroshare/hydroshare/blob/develop/theme/static/js/hs-file-icons.js add the following entry:
```
    fileIcons.URL =
        "<span class='fa-stack fb-stack fb-stack-url'>" +
        "<i class='fa fa-file-o fa-stack-2x'></i>" +
        "<i class='fa fa-link fa-stack-1x'></i>" +
        "</span>";
```

This should give you an icon that will be used for .url files:

![image](https://user-images.githubusercontent.com/2448568/44927404-ab03c380-ad11-11e8-942c-29b60c6ea2f4.png)

![image](https://user-images.githubusercontent.com/2448568/44927420-b9ea7600-ad11-11e8-9493-913753772ef2.png)

![image](https://user-images.githubusercontent.com/2448568/44927434-c969bf00-ad11-11e8-91ac-6e6894637a22.png)

**Comment by hyi** [comment] 2018-08-31 18:16
@Maurier Got it. Many thanks for the quick and detailed response.

**Comment by hyi** [comment] 2018-09-04 18:33
@horsburgh A quick question regarding your comment: ```References to files can be located anywhere within the folder hierarchy of a resource (except nested within other aggregations)```
Does it mean if a folder can be created within the folder hierarchy of a resource, then references to files can be created as well? I am trying to see whether I can leverage existing flag for enabling or disabling folder creation action in a folder hierarchy of a resource to enable/disable adding reference content to resource as well, and it appears to me the folder creation enabling/disabling flag applies to adding reference content to a specific folder in a resource folder hierarchy as well. Let me know whether it is safe to make this assumption, i.e., use folder creation enabling/disabling flag to control enabling/disabling for adding reference contents as well. If the answer is yes, I can rename that flag to make it cover both cases; otherwise, if the answer is no, I'll create a new flag for adding reference contents, but I'll need to know what is different between actions of creating a new folder and adding reference content, so I can set the flag accordingly.

**Comment by horsburgh** [comment] 2018-09-04 18:42
@hyi - I *think* the answer is yes. The point of this comment was that you can put references in any folder anywhere in the hierarchy - *except* within specific aggregation folders that do not permit it. For example, you should not allow creation of a reference file within a geographic feature aggregation folder or within a geographic raster aggregation folder. I believe that the same rules that have been implemented for creating new folders *should* apply to referenced files as well - if they have been implemented correctly.

@dtarb, @sblack-usu, and @pkdash - am I getting this right. Best to have more than one set of eyes before Hong uses her proposed method. I think it works, but let us know if not.

**Comment by sblack-usu** [comment] 2018-09-04 19:12
yes, this makes sense to me.  Perhaps name that flag to something more general or comment it well so the next person to come along isn't confused why a folder flag is used for reference content.

**Comment by hyi** [comment] 2018-09-04 20:16
@sblack-usu Yes, that is what I intend to do, to rename that flag to cover both cases to eliminate confusion.

**Comment by Maurier** [comment] 2018-09-05 21:50
@hyi maybe we could use this one for .url files:
https://fontawesome.com/v4.7.0/icon/external-link

This one would indicate better that the file opens outside of HydroShare.

**Comment by hyi** [comment] 2018-09-06 13:20
@Maurier Agreed that external-link icon looks like a better fit to ```add content from the web```. Will update the code to use that icon. Thanks!

**Comment by hyi** [comment] 2018-09-11 18:09
@horsburgh What is the rationale behind ```When displaying .url reference files in the file browser interface, the .url file extension should be removed so the user doesn't see it```? Special logic will be needed to handle hiding .url file extension from the file browser interface. Before I add any such special logic, I am wondering whether this is really needed. For me personally, having .url extension in the file browser interface is preferable as it clearly indicates the file is actually a .url file. Let me know whether we can treat .url extension in the same way as any other uploaded files without hiding the .url extension.

**Comment by hyi** [comment] 2018-09-11 18:47
@horsburgh Regarding the task ```The user should be able to right click on a folder containing any .url files and select "Add metadata to folder". This will have the same effect as the existing functionality for this action when initiated on a folder with files stored within HydroShare's file system - an OAI-ORE resource map and aggregation metadata document will be created within the folder.```, I confirmed with @sblack-usu that ```Add metadata to folder``` functionality is not in for 1.16 release yet but @pkdash may be planning on adding that after 1.16. This "Add metadata to folder" is a generic functionality for composite resource overall without any special handling needed for .url web reference file. So I suggest to remove this task from this issue but treat "Add metadata to folder" as a generic feature for composite resource. When that generic feature is implemented after 1.16 release, it will work for .url web reference file as well.

**Comment by horsburgh** [comment] 2018-09-11 19:11
Add metadata to folder is generic Composite resource functionality and not specific to referenced content at all. But, I thought it had already been added to composite resource functionality? @pkdash can set us straight.

**Comment by hyi** [comment] 2018-09-11 19:42
@horsburgh A update regarding the task: ```Verify ability to create metadata for a single referenced file (.url file) (e.g., create a single-file aggregation from the .url reference file). The user should be able to right click on a single .url file and select "Add metadata to file". ``` What I have done is to automatically create a generic logical file aggregation for the .url file at the time it was added to the resource. The reason for this is that I need to record url into a generic logical file field (not metadata per se, but only a generic extra_data field for internal use) for doing redirecting to the url when, e.g., double-clicking on the .url file. The result of this is that you can directly see and add metadata to .url file generic aggregation from content metadata tab after selecting the file, i.e., it skips the step to click on ```Add metadata to file``` and this menu item is actually disabled for .url file. I don't think this minor difference would matter much, and in fact, I like the current implementation since it saves one extra step from users, and thus more streamlined. Want to update you on this, though, just in case.

**Comment by pkdash** [comment] 2018-09-11 19:59
"Add metadata to folder" is not part of 1.16. I am currently working on this as part of the new FileSet aggregation/file type.

**Comment by horsburgh** [comment] 2018-09-12 14:26
Thanks for the reminder @pkdash - I'll look forward to that functionality after 1.16.

@hyi - if you are automatically creating an aggregation for the .url files, I think that's fine unless there are any performance implications. I suspect that's not an issue.

**Comment by horsburgh** [comment] 2018-09-12 14:28
@hyi - the purpose of my suggesting that we remove the ".url" part of the extension was that it is going to be confusing to users, most of whom will not know what a ".url" file is. If you want to leave it for now for the first implementation, I'm fine with that.

**Comment by hyi** [comment] 2018-09-12 15:42
@horsburgh I don't notice performance implications resulting from automatically creating a generic aggregation for .url files since the generic aggregation creation is fast as it does not involve time-consuming metadata extraction for other specific aggregation types. Regarding keeping the ".url" extension, we may add a brief message about .url with a link such as https://fileinfo.com/extension/url after .url file is added to educate the user a bit on .url file we are using to encode web reference content.

**Comment by horsburgh** [comment] 2018-09-12 16:17
@hyi - my concern with performance wasn't with auto-creating an aggregation for an individual .url file, but rather what would happen if I had a whole bunch (say hundreds) of .url files in a resource. If that's not a problem, then this is great.

**Comment by hyi** [comment] 2018-09-12 16:53
@horsburgh That is a good question and valid concern. I don't anticipate performance issues on the server side even with hundreds of .url files in a resource, as long as the client can display all those files efficiently in file browser UI. We can do some stress testing perhaps after the REST API is also implemented so we can have an idea whether we need to address any potential performance impact.

**Comment by hyi** [comment] 2018-09-14 19:04
@horsburgh Regarding ```Double clicking on an individual .url file should result in the user receiving the following warning, after which HydroShare will redirect a new browser tab to the URL contained in the file```, since .url file is auto-aggregated into a generic logical file, double clicking on an .url file will download the single file aggregation as the current default behavior. I suggest we keep this default behavior, and add a menu entry ```redirect to referenced URL``` when right clicking on a .url file. Let me know what you think.

**Comment by hyi** [comment] 2018-09-14 20:33
@horsburgh I took back my suggestion above after giving it a bit of more thought and after seeing your subsequent bullet point ```Double clicking on or right clicking on a single referenced file aggregation should be the same as individual referenced files (above)```. I will implement as you specified, i.e., doubling clicking on a .url file will result in the user receiving the warning and then redirecting a new browser tab to the referenced url.

**Comment by sblack-usu** [comment] 2018-09-17 18:08
@hyi - I'm not sure what your plan for implementation of the redirect will be, but I think it's worth building it in a way that a user can share the link to the referenced resource in hydroshare, where hydroshare will then redirect to the url in the .url file.  I actually believe that the download link would be good for this because it doesn't make much sense to ever download a .url file. 

If you don't agree with the download link being repurposed for .url file redirection, I propose we setup a different url that is standalone from the UI, that gives the redirect warning with a continue button.

For example, I think if a user pastes a reference to the url file in the browser `https://www.hydroshare.org/resource/4db3e81d3ccb4826b3c5451995ca2882/data/contents/example.url` it should take you to the hydroshare redirect warning page and then redirect.  That same url could be opened into a new tab when double clicking the url file in the file browser.  This will give an easy way to access these referenced resources through hydroshare.  It would also encourage people to share the hydroshare link rather than the link inside the url, which could give us some useful metrics to track.

**Comment by hyi** [comment] 2018-09-17 19:50
@sblack-usu That is a good point. Since .url file is auto-aggregated into a generic file aggregation, the download of the url file currently actually downloads a zipped aggregation with metadata included similarly as other aggregations. We allow users to add metadata into .url aggregation anyway, so this is consistent with aggregation design as detailed in this issue by @horsburgh. When users double click on the .url file, it will bring up a dialog and ask users for redirect. I think having a reference URL that allows to directly redirect to the referenced URL is a good idea, but having the download URL to download an aggregation with metadata included is also useful and consistent with HydroShare aggregation behavior across the board. Perhaps we can have a ```redirect``` parameter in the URL to inform doing redirect or not specific to .url files. For example, ```https://www.hydroshare.org/resource/4db3e81d3ccb4826b3c5451995ca2882/data/contents/example.url``` downloads a zipped aggregation, but ```https://www.hydroshare.org/resource/4db3e81d3ccb4826b3c5451995ca2882/data/contents/example.url/redirect``` redirects to the referenced URL? @horsburgh what do you think?

**Comment by horsburgh** [comment] 2018-09-18 15:40
@hyi - I discussed this a bit with @sblack-usu yesterday. I think having one way to handle both of these situations would probably be best. In HydroShare's resource landing page, we have proposed changing the behavior of a double click on a ".url" file so that instead of downloading the .url file (as is done with all other files), the user is redirected to the URL contained in the .url file after receiving a warning. There should also be a right click menu item on a .url file that says something like "Open referenced content" or something like that.

As @sblack-usu suggests, instead of the warning being a modal window or pop up message on the resource landing page, could we precede the redirection with a separate page that opens in a new tab, warns the user about the redirection, and allows the user to choose whether they want to continue with the redirection? We could also give them the option to just download the .url file on this page. 

The reason for having a separate page rather than a modal or pop-up of some sort on the resource landing page is that it would work for all cases: 1) when a user double clicks on a .url file on the resource landing page, 2) when a user right clicks on a .url file and selects "Open referenced content", or 3) when a user pastes a HydroShare link to a .url file into their browser (e.g., ```https://www.hydroshare.org/resource/4db3e81d3ccb4826b3c5451995ca2882/data/contents/example.url```).

**Comment by hyi** [comment] 2018-09-18 17:29
@horsburgh @sblack-usu A couple of comments:
- The current spec does mention ```Double clicking on an individual .url file should result in the user receiving the following warning, after which HydroShare will redirect a new browser tab to the URL contained in the file```. However, when users right click on the .url file and select download, the aggregation zip file will be downloaded similarly to other aggregations. I think this is reasonable. We can add a right click menu item like "Open referenced content" on a .url file that will do the redirect similarly to double clicking on the .url file. Will this be sufficient?
- I like a modal popup warning better than a separate page since it is more tightly integrated with resource landing page. Opening up a separate page on a separate tab is a little distracting in my opinion. The modal pop up dialog can be shared between different actions as well, except when a user pastes a HydroShare link to a .url file into their browser. However, this is a different issue since this HydroShare link to a .url file is currently behaving as downloading the file or aggregation just like other files. Even if we want to replace modal pop up with a separate page, we have the same issue how to handle this URL link to a .url file. Our current URL mapping just maps this to download view function, we can easily add some logic to check for .url file extension and do redirect for .url file as needed in the download view function, if this makes more sense. If we want to support both download and redirect via the same URL, we can create such a page where both download and redirect button are added. However, I think having a modal popup warning to work with file browser on resource landing page is better in terms of consistency with rest of file browser UI. The only drawback as I can see is to replicate the warning language in both modal popup dialog (where only redirect button (i.e., no download button) is included) and the redirect page (where both redirect and download buttons will be included). Given more seamless UI in file browser, I feel this drawback is acceptable. Although replacing the modal popup dialog with redirect page is easy to do, I just like modal popup better when working within file browser and that is already implemented in my local branch.

**Comment by horsburgh** [comment] 2018-09-19 03:43
@hyi - on your first point, yes, that would be great to have a right click option on a .url file to "Open referenced content"

On your second point - a single redirect page seems simpler and would be consistent across both use cases. If you feel strongly about the modal window for the HydroShare user interface, that's fine. But, we would still have to handle the case where a user pastes a HydroShare URL to a .url file into their browser. This would need to be a separate HydroShare page that handles those requests to see whether the user wants to download the .url file or be redirected to the referenced content. That page should probably have a message that says something like:

> You are accessing referenced content that is not stored in HydroShare. Do you want to download an Internet Shortcut File that contains a link to the referenced content or have your browser redirected to the location of the referenced content?

**Comment by aphelionz** [comment] 2018-09-19 03:50
@horsburgh We have a URL already that tracks external activity. @Castronova wrote it and uses it for tracking app opens. You could easily reuse that work @hyi 

https://github.com/hydroshare/hydroshare/blob/develop/hs_tracking/views.py

**Comment by hyi** [comment] 2018-09-26 14:28
@horsburgh @sblack-usu I believe I have implemented all tasks covered in this issue and I am deploying the first pass of the implementation to playground right now. Will let you know when the deployment is done and playground is up and running. One thing I want to bring up is that instead of implementing a separate page asking users to either download or redirect for a url file, I implemented redirecting to the referenced url directly if the URL file encodes a valid referenced URL. Since users can download the file or aggregation from within HydroShare file browser interface, I think it is acceptable to directly redirect if a file URL is put in URL field on web browser directly. Hopefully you have time to take a look on the first pass implementation on playground when it is up before our team call meeting today so we can discuss any comments/issues as needed.

**Comment by horsburgh** [comment] 2018-09-26 14:43
Thanks @hyi - I'll have a look as soon as you are ready for testing.

**Comment by hyi** [comment] 2018-09-26 15:09
@horsburgh - playground is up and running now. I have done a quick testing and everything appears to work as expected. You will have to sign up and create a user account first since it is not deployed with existing www resource data.

**Comment by hyi** [comment] 2018-09-26 18:52
@horsburgh @sblack-usu @ChristinaB @danames  I have fixed the redirect bug when putting a file URL on a web browser on playground.hydroshare.org, discovered during the demo today. It now works regardless where the URL file is in the folder structure. Feel free to give a test drive on playground and chime in with any suggestions/comments/feedback.

**Comment by horsburgh** [comment] 2018-10-09 17:09
@hyi - I just did some testing on playground. Here's some issues I encountered:

1. I tried to edit the URL for a reference (right click, edit referenced URL) to an invalid URL. I got a huge, long, red error message on the page. We need to handle this more gracefully. I suggest an error message that says: 
> "The URL that you entered is not valid. Please enter a valid URL."
2. Updating the URL for a referenced file removes all file/content level metadata. Was this by design? I don't think we should do this. I think the URL should be edited in the .URL file, but the file-level metadata should remain.
3. For some reason when I download the whole resource I created, the tagmanifest-md5.txt file is incorrect. It contains all of the Bagit tag files (which it should), but it also contains a listing of all of the content files (which it should not). This may be a separate issue that needs to be addressed.
4. For the window that pops up when you click on the "Add content from the web" button, can we add some additional text to the label above the "Name" field? I suggest: 
> Create a name for the referenced content. This name will be displayed in the file content area of the resource.
5. I create a new folder and dropped a shapefile into it. That automatically converted that folder to a geographic feature aggregation. I then dragged one of my .url file onto this folder, and it let me drop the .URL file in that folder. This should not be possible. I should not be able to nest a referenced file aggregation within a geographic feature aggregation. It also let me upload files to this same folder. There should be logic preventing this from happening right?

Implementation of the metadata file and the resource map document file at the single-file aggregation level looked good. It also looked good at the resource level. I was able to move .URL files into and out of folders no problem.

I also tried right clicking and selecting "Get file URL", which gave me a HydroShare URL for the .URL file. I pasted that into my browser window and it immediately redirected me to the remote URL, so that also looks good. 

I did not do any testing via the API and there may need to be additional considerations there.

**Comment by hyi** [comment] 2018-10-12 19:57
@horsburgh I believe I have addressed all your comments and updated playground for you to test again with one caveat regarding your comment item No. 3 about tagmanifest-md5.txt. First, the tagmanifest-md5.txt is generated by iRODS rule, which has not been changed for a long time. Second, I cannot reproduce it locally. Third, I tested on testservices.hydroshare.org which does not have my code, and it has exactly the same issue with tagmanifest-md5.txt content. I believe this is iRODS-related since all test VMs deployed automatically using Jenkins uses hydrotest41.renci.org iRODS host and thus exhibit same issue with content in tagmanifest-md5.txt. It may be related to iRODS server upgrade, but I have no plausible explanation how come the same iRODS rule (which does not write content file manifests into tagmanifest-md5.txt) somehow put content files into tagmanifest-md5.txt probably only when being executed on this hydrotest41.renci.org iRODS host. I tested on www and https://dev-hs-1.cuahsi.org/ which @sblack-usu deployed with latest develop branch and this tagmanifest-md5.txt problem does not occur there. I merged latest develop into my branch so what is deployed on playground now has latest develop content along with my referenced content work. Anyway, I don't think this tagmanifest-md5.txt issue is introduced by my referenced content work, it looks like a deployment-specific/irods-specific issue although I have no idea what could have caused that. Also, your comment item No. 5 is a generic bug in composite resource phase 2 implementation which I have fixed in my branch. Please test again when you have a chance and let me know any further issues you find.

**Comment by horsburgh** [comment] 2018-10-23 19:29
@hyi - i went through all of the tests I described in my last comment above. Everything checked out fine except for number 3 - the BagIt tag manifest file still contains all of the resource content files. Since you have indicated that this is a configuration setting specific to the testing server, I won't worry about it.

One other minor note - I can no longer drop a ".URL" file into a folder that is a geographic feature aggregation. When I try to do that, I get an error message. But, if I open that folder and try to drag and drop a file from my machine onto the resource, it doesn't work (which is good), but I don't get an error message (or any message at all). I think this is unrelated to your functionality and so I think what you have done is great. Just noting that there's an inconsistency here.

**Comment by dtarb** [comment] 2018-11-06 22:46
Deployed with 1.16.1.  Thanks team.

**Closed by dtarb** 2018-11-06 22:46 UTC
Labels: (2) Medium Effort, Composite, Medium Priority, Resource Model, enhancement
