### ISSUE TITLE
Why can't I +1 Christina?

### ISSUE THREAD

**Issue by cbev** [hydroshare/hydroshare#1217] opened 2016-05-17 17:59 UTC
Hello- I tried to "+1" a comment on a collection but an error occurred. Specifically, it took me to a new page that says "Error-- Sorry, an error occurred." This happens on multiple levels of the resource (the main resource page, inside the collection, etc.).

Thanks for looking into this!

**Comment by hyi** [comment] 2016-05-17 18:06
@jbradberry This issue has the same cause as #1137 - primary key clash. After several erroneous trials, this error will go away. Assigning to you now so that we can verify the fix once you get a chance to look into it and get to the bottom of it. Feel free to reassign it to me as needed.

**Comment by jbradberry** [comment] 2016-07-21 17:20
@hyi @mjstealey My prediction was that this was caused by destroying and then reconstructing the database during deployments.  I believe that we've fully switched over to using a persistent volume for the database at this point; have these errors gone away?

**Comment by hyi** [comment] 2016-07-21 18:03
@jbradberry I think your prediction was very possible to be the cause of this issue. I am not sure whether we've fully switched over to using a persistent volume for the database at this point, I'd say it probably has not happened yet, but will defer to @mjstealey for the final words and details.

**Comment by pkdash** [comment] 2016-10-12 20:53
@hyi Should this be closed?

**Comment by hyi** [comment] 2016-10-12 21:00
Since the issue https://github.com/hydroshare/hydroshare/issues/1137 has been closed and this issue has the same cause as that one, I am closing this as well.

**Closed by hyi** 2016-10-12 21:00 UTC
Labels: bug, Low Priority
