### ISSUE TITLE
Unable to take any action on a resource, cannot add authors, delete the resource, or share. 

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#4621] opened 2022-05-16 14:31 UTC
**Description of the bug**
After I changed the username of an account for a user who is turning over the account, she went to try to edit a resource the already existed, but found that all authors and owners were gone and she could not add any new ones. The content is not loading and in edit mode this occurs:
<img width="566" alt="Screen Shot 2022-05-16 at 10 27 38 AM" src="https://user-images.githubusercontent.com/90924476/168615903-59e211d8-edaa-42f5-b1b0-022f1d5f0ca3.png">

The resource does not have that much content in it. 

Steps to reproduce the bug:
1. Go to [https://www.hydroshare.org/resource/27e888b041c749f89e06abcf3732f2de/]
2. put the resource in edit mode and try to add authors, or try to add authors via the green plus button
3. you will see that no actions can really be taken on the resource, and options in the share menu are rendering weirdly. 

**Expected behavior**
User should be able to add authors and owners without issue via the sharing menu

**Additional information**
I have told the user to create a new resource in the meantime and we will investigate the old version

**Comment by sblack-usu** [comment] 2022-05-17 14:10
Relevant console logs
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/35820390/168829186-eedea2d6-c3a3-427b-96ed-96c847cebf91.png">

I can see USERS_JSON defined on the page.  
```
      const USERS_JSON = [{"user_type": "user", "access": "owner", "id": 9672, "pictureUrl": "/static/media/profile/Riverkeeper-logo-square-400_jenniferlepstein_9e7bd1ea8e944acd9a45aa6943d3e325.png", "best_name": "Riverkeeper", "user_name": "Riverkeeper", "can_undo": false, "email": "info@riverkeeper.org", "organization": "Riverkeeper", "title": "Riverkeeper", "contributions": 2, "viewable_contributions": 2, "subject_areas": "Hudson River, Hudson River Tributaries, Drinking Water", "identifiers": {}, "state": "NY", "country": "US", "joined": "20 Apr, 2021"}];
```

**Comment by dtarb** [comment] 2022-05-24 10:36
@ClaraCogswell @martinseul there is no interface to change username in the user profile editing page.  I suspect this is by design because the system is not designed to support changes of username.  Did you change the username as an administrator in Mezzanine.  If you did this and this is what caused the problem, then we should not do this. I think you should change it back and we should inform all who are system administrators to never change a username.  In fact we should almost never do anything on the Mezzanine panel without fully understanding the ramifications which should be determined by testing on beta first.

**Comment by dtarb** [comment] 2022-05-24 10:41
The way an account can be "turned over" if the new user does not like the old username should be to create a new account with the new name, transfer ownership of the resources to the new account, then delete the old account.  This is a few steps, rather than just 1, but it is a rare event so should not be onerous.  I think username is used as a unique account identifier pretty deeply throughout the system and that this action has reminded us that changing deeply embedded unique identifiers should be avoided as unexpected problems can result.

**Comment by ClaraCogswell** [comment] 2022-05-24 13:08
I did change the username on Mezzanine, I was unaware that it had never been attempted. It is a changeable field, so I assumed it could be changed safely, since the actions you take to change it are the same as email or password. I will try changing the username back. I will need to inform the user first though as it may break any new resources she has made on the account since the username change.

**Comment by dtarb** [comment] 2022-08-11 12:14
The Mezzanine interface is only supposed to be used by system administrators who "know" the system. Logging in and working as system administrator should only be done with great care.  It is good to test out system administrator actions on beta first, or on an internal team user first, before doing them on another user, because of unintended consequences such as this.

Looking at the resource mentioned https://www.hydroshare.org/resource/27e888b041c749f89e06abcf3732f2de/ it appears correct from not logged in and a user without permissions (me), but logged in as system admin, author and owner do not display correctly.  I suggest working on beta to figure out a way to get this right, and then when figured out, do the actions on www.

I do not think there is a practical way to identify and limit all potentially harmful actions when logged in to the mezzanine interface as a system administrator, though I would be interested in the opinion of @martinseul and @sblack-usu.  There needs to be documentation for system administrators "A hydroshare system administrators manual" that needs to record these sort of things and how to accomplish, in this case, a user name change.

**Comment by martinseul** [comment] 2022-08-11 14:16
in general the mezzanine interface is not meant to mirror the functionality that is provided by Hydroshare, e.g. you can't create a HS user in mezzanine it needs to be done through the app even thought here is a function to add a user in mezzanine. There are certain task we use it for (afaik) : 

- manually approve account request in case the activation failed
- manually reset passwords
- elevate rights for user
- delete accounts (deletes also HS objects)
- application approval (approved apps)
- store application registration
- provide list of universities for Organization field, (should reconsider that approach)
- store Oauth tokens
- show messages on homepage, e.g downtime notices
- store Quota messages
- increase and monitor User quota

all of these are fairly straightforward tasks in the UI.

@sblack-usu anything i forgot?

**Comment by ClaraCogswell** [comment] 2022-10-10 15:23
Conclusion: Add content to help to specify that usernames cannot be changed, internal policy will be that usernames cannot be changed, work with @sblack-usu to see how easily that mezzanine form can be changed.

**Comment by ClaraCogswell** [comment] 2022-10-17 15:07
She made a new version of the resource under the new username so the old version will work if we change the username back but the new version of the resource will break. I assume the link she has used to disseminate the resource is the new version, so changing the username back will break the resource in circulation. I suggest that we do not change the username back in this case, and remove the ability to change usernames going forward.

**Comment by ClaraCogswell** [comment] 2022-10-18 13:48
@sblack-usu once your PR is merged and reflected in prod mezzanine we can probably close this ticket, right?

**Comment by sblack-usu** [comment] 2022-10-18 14:49
correct

**Comment by devincowan** [comment] 2022-10-25 17:49
closing per #4794

**Closed by devincowan** 2022-10-25 17:49 UTC
Labels: bug, Resource Landing Page
