### ISSUE TITLE
Make apps link open in new tab in production (automate)

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1020] opened 2016-02-27 12:39 UTC
This [line](https://github.com/hydroshare/hydroshare/blob/2a7b1f6aee485b465ca681267538ee90a3642487/theme/static/js/custom.js#L115)

From

``` bash
// Make apps link open in new tab
 $('a[href^="https://appsdev.hydroshare.org/apps"]').attr('target', '_blank');
```

To

``` bash
// Make apps link open in new tab
 $('a[href^="https://apps.hydroshare.org/apps"]').attr('target', '_blank');
```

**Comment by dtarb** [comment] 2016-11-11 04:34
Seems to be working as intended so closing.

**Closed by dtarb** 2016-11-11 04:34 UTC
Labels: Medium Priority
