### ISSUE TITLE
Develop systematic fix for resources without a bag zip file but bag_modified=false

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2354] opened 2017-10-18 20:47 UTC
I suggest we need a systematic fix for the problem of #2347.  An error occurs if a bag zip file is missing but bag_modified is false.  The code that attempts to download a bag should catch when there is no bag and then instead of giving an error, set the bag_modified code to true and restart the process so that a bag is generated.

**Comment by alvacouch** [comment] 2017-10-25 18:38
@dtarb @hyi @phuongdm has documentation on a management command `check_bag` that will reset the bag system. I wrote this command a long time ago, but documented it for Phuong **yesterday.** 

```./hsctl managepy check_bag --reset {resource-id}``` 

will fix the problem for a specific resource.

**Comment by horsburgh** [comment] 2017-10-25 18:58
@alvacouch and @hyi - will this fix #2365 ? We are under the gun to get that resource fixed so we can publish it and cite it in a paper that is in press (proofs need to go back to the journal ASAP).

**Comment by hyi** [comment] 2017-10-25 19:00
@alvacouch Yes, I know your management command can do that, but this issue @dtarb created is to automatically fix this issue without amending the fix after the user finds that a resource cannot be downloaded due to the bag_modified flag issue. I can take care of this relatively quickly when I get a chance to work on it.

**Comment by hyi** [comment] 2017-10-25 19:02
@horsburgh This issue will not fix your issue #2365, the cause for that issue is different from this one. This download issue is caused by bag_modified flag being wrong, which can be fixed easily, but that issue was caused by out-of-sync issue between Django database and irods. See details of my investigation on that issue. Looping in @alvacouch as well since @alvacouch 's management command might be able to fix Django ResourceFile fields based on iRODS truth to make them in sync again.

**Comment by aphelionz** [comment] 2017-11-29 18:27
@hyi @dtarb This can be closed after 1.14 goes out

**Comment by dtarb** [comment] 2017-12-02 22:25
@hyi can close when she has verified.  I do not know how to test this fix.

**Comment by hyi** [comment] 2017-12-02 23:42
verified on beta, closing.

**Closed by hyi** 2017-12-02 23:42 UTC
Labels: bug, File System, Medium Priority
