### ISSUE TITLE
Cannot zip a folder containing aggregations

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3777] opened 2020-03-02 11:55 UTC
I tried to zip a folder containing aggregations and received the following message.  Is there a good reason why a folder containing aggregations can not be zipped.
![image](https://user-images.githubusercontent.com/3456833/75674269-f7e79380-5c41-11ea-8e65-ce1422497667.png)

**Comment by hyi** [comment] 2020-04-03 16:52
@dtarb This issue is a duplicate of https://github.com/hydroshare/hydroshare/issues/2979 from which you can find explanation from @pkdash about this behavior.

**Comment by sblack-usu** [comment] 2020-04-07 22:26
closing, duplicates #2979

**Closed by sblack-usu** 2020-04-07 22:26 UTC
