### ISSUE TITLE
Unexpected results when searching for Model Instance resource through "Filter by Resource Type" table 

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#1142] opened 2016-04-21 03:27 UTC
the search should show only one Model Instance resource, however it shows four resources (see below)

![image](https://cloud.githubusercontent.com/assets/5543781/14697306/744bc4dc-0750-11e6-877a-613bfdd3615e.png)

**Comment by xuezhaokun** [comment] 2016-04-21 06:38
It seems this happens for resource types' names have common part, like "Model Instance Resource" vs "SWAT Model Instance Resource" and "Time Series" vs "HS Referenced Time Series". I think this is caused by the way I am using to index resource type field. This is what I am having now:
```
    def prepare_resource_type(self, obj):
        return obj.get_content_model()._meta.verbose_name
```
It seems SOLR does not index and search for this correctly,
If I index the resource type as:
```
    def prepare_resource_type(self, obj):
        return obj.resource_type
```
We will not have this issue. And if you search the resource_type field value in search box, we will not have the issue mentioned in #1143 
But in this way, we cannot have the easily readable verbose names in resource type filtering panel. And we have to search the exactly resource_type field value, for instance "TimeSeriesResource".

I think if we could have a better and easier way to access the verbose name for resource type, we can solve this issue easier.
@alvacouch Do you have any suggestion for this issue?

**Comment by hyi** [comment] 2016-04-21 12:49
@xuezhaokun @alvacouch @ironfroggy I see the dilemma here, and wondering whether we can do "filter by resource type" via direct database filtering rather than via solr search filtering since resource type is uniquely defined with its verbose name not required to be unique. I think it is better to use resource type verbose_name for solr index so that it can find resources without requiring exact match to resource type field in the database, but we can make an exception to "filter by resource type" so that it resorts to database direct filtering to get those resources with exact match for resource type.

**Comment by xuezhaokun** [comment] 2016-04-21 15:06
@hyi Do you know how can I access resource type verbose name from out database? If I can include the resource type verbose name filed in our basereource_text.txt template, we can make it searchable.  "obj.get_content_model()._meta.verbose_name" dose not acceptable by the text template. Is there any other way we can get the resource type verbose name?

**Comment by hyi** [comment] 2016-04-21 15:09
@xuezhaokun You can get verbose name using obj._meta.verbose_name where obj is a resource object.

**Comment by xuezhaokun** [comment] 2016-04-21 15:12
@hyi I tried this way, but  when I tried to do reindex, it told me that variables cannot start with underscores in the text template.

**Comment by hyi** [comment] 2016-04-21 15:17
@xuezhaokun The verbose_name is one of the model meta option in Django, and I don't know any other way to access this verbose_name other than obj._meta.verbose_name. @pkdash @ironfroggy Any ideas or suggestions on @xuezhaokun 's question?

**Comment by xuezhaokun** [comment] 2016-04-21 15:27
Basically, the reason why we have this issue is that we index and facet on resource_type verbose name, but we cannot have a proper way to make resource_type verbose name searchable. For now, we can only search resource_type field in the database not the verbose name in Meta class. 
@mohamedmorsy When you tried to search "model instance resource", it actually did a full text search in other searchable fields where we have the term "model instance resource". For now, if users want to search "model instance resource" resource type, they have to search"ModelInstanceResource".

**Comment by pkdash** [comment] 2016-04-21 15:43
Not sure I fully understand the issue from this threaded discussion. But if @xuezhaokun having problem using ```obj._meta.verbose_name```, then one can add a property ```verbose_name``` to the Resource class and use it as ```obj.verbose_name```

**Comment by xuezhaokun** [comment] 2016-04-21 15:45
@pkdash I think if anyone can offer a help to add obj.verbose_name to Resource class, that would be great.

**Comment by mohamedmorsy** [comment] 2016-04-21 16:04
@xuezhaokun I think you missplaced the text here. This should be related to issue#1143. For this issue I did not write anything in the search box but I used the filter table only.

**Comment by xuezhaokun** [comment] 2016-04-21 16:18
@mohamedmorsy From my understand about SOLR and Haystack, I think these two issues are actually caused by the same problem. When you try to filter anything, that is actually a search query, sqs.filter(SQ(resource_type = "something")), which is a filter process just as what we do for search box. For search box, we actually do sqs.filter(content="something"). If we cannot get resource_type verbose name searchable, we cannot have correct results for both actions on resource type.

**Comment by pkdash** [comment] 2016-04-21 16:22
@xuezhaokun  add this code to BaseResource class:

    @property
     def verbose_name(self):
         return self._meta.verbose_name

**Comment by mohamedmorsy** [comment] 2016-04-21 16:22
@xuezhaokun got it. Thanks.

**Comment by xuezhaokun** [comment] 2016-04-21 17:32
@pkdash I add this code to BaseResource:
```
    @property
    def verbose_name(self):
        return self.get_content_model()._meta.verbose_name
```

It seems that code you just provided can only return 'Generic'.

@mohamedmorsy Now, when you filtering on "Model Instance Resource", both will show four results, three for "SWAT Model Instance Resource" and one for "Model Instance Resource". I guess this is because we are doing SOLR full text search, it will show you all the results related to the search or filtering term. For the faceting count numbers in the filtering panel, it just tells users how many resources are exactly in this resource type. I am going to discuss about this with Alva to see whether my understanding is correct.

**Comment by pkdash** [comment] 2016-04-21 18:46
@xuezhaokun Why you think it only return "Generic"?

**Comment by xuezhaokun** [comment] 2016-04-21 18:59
@pkdash I guess since we only add it in BaseResource, it only returns the verbose name for BaseResource class. If we  want to get it return verbose name for all kinds of resources, we need to include this code in all resources classes. I think that's why we want to do a get_content_model() first.

**Comment by pkdash** [comment] 2016-04-21 19:01
@xuezhaokun All resource type classes inherit from BaseResource class. So the appropriate verbose_name for each resource type will be returned.

**Comment by xuezhaokun** [comment] 2016-04-21 20:48
@pkdash I tested your solution again. It still only returns "Generic". I cannot get other resource type. I am not sure why.

**Comment by pkdash** [comment] 2016-04-21 21:04
@xuezhaokun can you show me the line where you using this?

**Comment by xuezhaokun** [comment] 2016-04-21 21:11
@pkdash [https://github.com/hydroshare/hydroshare/blob/discovery-issue-fix/hs_core/models.py#L1384-L1387](url)

**Comment by pkdash** [comment] 2016-04-21 21:34
@xuezhaokun I mean where you using ```obj.verbose_name```

**Comment by xuezhaokun** [comment] 2016-04-21 21:37
@pkdash sorry.https://github.com/hydroshare/hydroshare/blob/discovery-issue-fix/hs_core/search_indexes.py#L104-L105

**Comment by pkdash** [comment] 2016-04-21 22:04
@xuezhaokun I can see the problem now. Your ```obj`` is always an instance of  ```BaseResource``` class. That's why you always get 'Generic'.

**Comment by xuezhaokun** [comment] 2016-04-22 01:41
@pkdash Yes. I see the problem now. I think that's why I need to do get_content_model first.

**Comment by pkdash** [comment] 2016-04-22 03:31
@xuezhaokun Do you get different value for ```obj.resource_type``` or always 'GenericResource`?

**Comment by xuezhaokun** [comment] 2016-04-22 03:36
@pkdash I get different values.

**Comment by pkdash** [comment] 2016-04-22 03:40
@xuezhaokun Then we may have a solution to this problem. In few minutes I will write some code for you to try.

**Comment by xuezhaokun** [comment] 2016-04-22 03:41
@pkdash OK. Thanks!

**Comment by pkdash** [comment] 2016-04-22 03:53
@xuezhaokun here is the code to try:

    from hs_core.hydroshare.utils import get_resource_types

    def prepare_resource_type(self, obj):
	   res_cls = None
	   for tp in get_resource_types():
		  if obj.resource_type == tp.__name__:
			res_cls = tp
			break
	  if res_cls is not None:
		res_obj = res_cls()
		return res_obj.verbose_name
	  else:
		return obj.verbose_name

**Comment by xuezhaokun** [comment] 2016-04-22 04:00
@pkdash Thanks! Trying it...

**Comment by xuezhaokun** [comment] 2016-04-22 04:20
@pkdash This can show verbose name correctly. But I just realize that in order to make verbose name searchable, we also need a way to access verbose name from object directly and include it in our text template file.  [https://github.com/hydroshare/hydroshare/blob/discovery-issue-fix/hs_core/templates/search/indexes/hs_core/baseresource_text.txt#L14](url) Sorry for missing this part.

**Comment by xuezhaokun** [comment] 2016-04-22 04:26
@pkdash I think it is better to find a way to solve this in models.py, when we define the verbose name property.

**Comment by pkdash** [comment] 2016-04-22 04:37
@xuezhaokun In that case change the code for ``prepare_resource_type``` as it was before. Then change the code for the property in BaseResource class as follows:

    from hs_core.hydroshare.utils import get_resource_types
    @property
    def verbose_name(self):
	  res_cls = None
	  for tp in get_resource_types():
		if self.resource_type == tp.__name__:
			res_cls = tp
			break
	 if res_cls is not None:
		res_obj = res_cls()
		return res_obj._meta.verbose_name
	 else:
		return self._meta.verbose_name

**Comment by xuezhaokun** [comment] 2016-04-22 05:02
After moving this to models.py, when I try to rebuild or restart the containers, it gives me this error:
```
dockerworker_1  |     from hs_core.models import Bags, ResourceFile
dockerworker_1  | ImportError: cannot import name Bags

```

**Comment by pkdash** [comment] 2016-04-22 05:18
@xuezhaokun Yeah it's a circular import problem. Move this import inside the property verbose_name

    @property
    def verbose_name(self):
         from hs_core.hydroshare.utils import get_resource_types

**Comment by xuezhaokun** [comment] 2016-04-22 05:44
@pkdash It is working now. Thanks for help!

**Comment by alvacouch** [comment] 2016-05-02 14:05
@xuezhaokun There are two different issues here.

1. the filtering on resource type as discussed in detail above. 
2. whether filtering is exact or approximate based upon facets. 

The original anomaly comes from clicking on a facet, expecting an exact match, and getting an approximate (rank order) match. This is a general problem. We should come up with a general solution to that problem, independent of the specific facet.

**Comment by hyi** [comment] 2016-05-16 14:30
@mohamedmorsy Please close this issue if it has been resolved.

**Comment by xuezhaokun** [comment] 2016-05-16 14:34
@hyi This issue has not been resolved. We need to find a way to do exact matching filter in Haystack.

**Comment by cuahsimarko** [comment] 2019-03-28 22:03
These UI Elements no longer exist

**Closed by cuahsimarko** 2019-03-28 22:03 UTC
Labels: Discovery, Medium Priority, bug

**Comment by dtarb** [comment] 2019-03-29 13:50
These UI elements are there - see below, and the problem still exists.  A filter on "Model Instance" still identifies "Model Instance", "SWAT Model Instance", "MODFLOW Model Instance" etc, resulting in a difference between the facet count and number of resources returned.  This is one of many Discovery issues, indicative of the fact that "Discover" is in need of some care.

It may be that we choose not to fix this when holistically looking at Discover, as this could be interpreted as a feature.  Sub instances are part of instances.  It could also be resolved as resource types are removed.  
 
![image](https://user-images.githubusercontent.com/3456833/55237106-fa05ce80-51f6-11e9-8dff-ec5ed349c29e.png)
![image](https://user-images.githubusercontent.com/3456833/55237199-376a5c00-51f7-11e9-91f3-f01f19aab6f6.png)

![image](https://user-images.githubusercontent.com/3456833/55237147-0e49cb80-51f7-11e9-9318-13f1972bf030.png)
