### ISSUE TITLE
Edge Browser Display of resource level temporal coverage for composite resource in edit mode is not correct

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#2949] opened 2018-10-21 23:22 UTC
In edit mode the resource level temporal coverage is always displayed as the current date. Seems like a bug in JavaScript code.  This occurs in Edge browswer, but not in Firefox and Chrome.

![image](https://user-images.githubusercontent.com/2523434/47273677-a5369b80-d566-11e8-9fa3-77f9792c610b.png)

**Comment by dtarb** [comment] 2018-10-22 13:05
I am not able to reproduce a bug here.  I get correct/expected behavior on beta.  For a resource without temporal coverage set it shows empty.  For a resource with temporal coverage set, it shows the temporal coverage.

**Comment by pkdash** [comment] 2018-10-22 14:53
Never mind it seems like a browser issue with Edge. It works with other major browsers. I guess I can close this issue.

**Comment by dtarb** [comment] 2018-10-22 14:55
If it is a browser issue with edge we should still fix it.  Just not hold up 1.16.  Is it a problem with edge in earlier deployments on www.

**Comment by engineSound** [comment] 2019-01-29 16:25
What's the version of the edge browser? Is it still reproducible?

**Comment by dtarb** [comment] 2019-01-29 21:57
Yes it is still reproducible.  Look at https://www.hydroshare.org/resource/6d9704e6168c4b969c56271d6692a770/ in Edge and in Firefox.  The edge version I have (windows 10 current update) is 
![image](https://user-images.githubusercontent.com/3456833/51943201-214a4600-23d6-11e9-8725-dce8bce967d1.png)

**Comment by dtarb** [comment] 2019-01-29 22:03
Note that the problem only appears in edit mode.

The problem appears on Internet explorer too - so both Microsoft browsers.  Note also that on IE in edit mode there is a width formatting problem in the how to cite area of a resource landing page

![image](https://user-images.githubusercontent.com/3456833/51943602-18a63f80-23d7-11e9-95ca-c8c88ecfe2ac.png)

**Comment by engineSound** [comment] 2019-01-29 22:48
@dtarb Thank you! I will debug it on the microsoft browsers.

**Comment by cuahsimarko** [comment] 2019-05-13 22:31
This will wait until migrations to Composite are complete.

**Comment by dtarb** [comment] 2019-05-16 03:17
There is no reason to wait until migrations to composite resources are complete.  This has nothing to do with the migrations.  If we are going to support these browsers, this is a bug to fix.

**Comment by martinseul** [comment] 2021-06-18 13:58
tested on latest edge browser and Chrome, I can't reproduce the issue, older dates <1900 save correctly, closing

**Closed by martinseul** 2021-06-18 13:58 UTC
Labels: Resource Landing Page, bug
