### ISSUE TITLE
Changes necessary for SOLR realtime updates 

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1164] opened 2016-04-26 14:46 UTC
@xuezhaokun @dtarb @rayi113 @hyi @pkdash 

Turning on real-time updates in SOLR doesn't work at all. Neither do any of the patterns for queueing updates. Changes need to be made so that this will work properly. 

Here is the crux of the problem as I see it now: 

By default, RealtimeSignalProcessor.setup only schedules responders for the subclasses of SearchIndex that you register in haystack. Since we only have a subclass for BaseResource, this means – in particular – that it only registers responders for BaseResource, and that is not what is being deleted. What is being deleted is a proxy class, but haystack does not understand that a proxy class has no other data to harvest, so that it does not automagically harvest changes in BaseResource relative to the proxy classes. 

One fix is to do the following;  
1.	Create a custom subclass of RealtimeSignalProcessor.
2.	Override RealtimeSignalProcessor.setup to register the proxy classes and other classes that influence resource content, e.g., ResourceAccess. These should also trigger updates to BaseResource SOLR data. 
3.	Override RealtimeSignalProcessor.update and delete to appropriately harvest or delete from the BaseResource SearchAPI instead of the proxy classes (by using super()).
4.	Override RealtimeSignalProcess.teardown to delete BaseResource rather than proxy classes.

**Comment by alvacouch** [comment] 2016-04-28 16:31
@dtarb @rayi @pkdash @jsadler2 @mjstealey 

Status report on this issue: 

We have correctly configured real-time delete using this method. 

*Update still doesn't work* due to a much deeper problem. 

When updating a single record using the haystack update API, haystack looks for -- and does not find -- fields in the AbstractResource class that is an abstract base class for BaseResource. Thus the update crashes with a field not found error, which is expressed as a template not found error for the base class Page (which we're trying *not* to index).  If we put in an empty SOLR template for Page, it becomes a field not found error for real. 

This is quite curious because these fields are found properly when using the command-line rebuild_index command. 

So, we've likely found a bug in haystack. 

One possibility is to switch to using haystack-celery, which queues all updates and probably uses the command-line interface :)

**Comment by alvacouch** [comment] 2016-04-28 16:34
@jbradberry See the above.... what is your view on this bug?

**Comment by jbradberry** [comment] 2016-04-28 16:48
@alvacouch taking a look...

**Comment by xuezhaokun** [comment] 2016-04-28 16:49
I pushed the latest changes for real time processor in PR: #1152 . And there are also some other fixed discovery issues in this PR.

**Comment by jsadler2** [comment] 2016-04-28 16:59
We got mixed up with issue numbers. So I am actually not part of this one. Sorry about the mix up.

**Comment by alvacouch** [comment] 2016-04-28 18:52
Note: the final fix was a bit different than the above suggestion: 
1. We left the events coming in from the various subclasses of BaseResource. 
2. We cast the superclass instance to BaseResource and update or delete that subclass instance.

**Comment by alvacouch** [comment] 2016-04-28 20:32
@dtarb @jbradberry @xuezhaokun @rayi113 @mjstealey 
Suggestion from Jeff was that the super() call may be messing up Haystack due to the unusual way that super() is implemented. We tried omiting the super call to cast from proxy class to BaseResource and -- instead -- trust Haystack to descend into subclasses (the way it has been observed to do during testing). This did not work. Same symptoms as before. However, the theory that super() messes things up in haystack is quite reasonable. I read up on it in detail and Jeff’s hypothesis is quite likely.  

Based upon this hypothesis, we managed to do something quite silly but actually completely effective:: 
    `newinstance = BaseResource.objects.get(pk=instance.pk)` 
(where instance is GenericResource or other proxy subclass of BaseResource). 

And that does work, because **proxy classes and their base classes share the same object keys!** Thus this simple hack hands a real instance of BaseResource to the indexer, which wants a real instance of BaseResource. Since the indexer is a post-save hook, this object is guaranteed to be saved so that this query will always succeed. **So, the indexer is happy now!**  

**So, it looks very much like Jeff’s theory was correct.**

At this point the main issue is that there is a writers’ race between GenericResource.create and ResourceAccess.create in hydroshare.create_resource. First the resource is created and gets implicitly indexed, before the ResourceAccess.create occurs. This fires off an index request before the access control object attribute exists. Solution is to make harvesting tolerant of the non-existence of the ResourceAccess attribute (“newinstance.raccess”).  The code will update the index again upon access control object creation.

Will write when this is done.

**Comment by jbradberry** [comment] 2016-04-28 20:36
@alvacouch Doing a read immediately after a write in this manner is going to cause problems by intermittently giving the indexer stale data.  I recommend against taking this course of action.

**Comment by alvacouch** [comment] 2016-04-28 21:07
@jbradberry We live in a very imperfect world and I must choose between undesirable alternatives. It is not practical -- at this time -- to redesign the BaseResource class so that the race does not exist. I could -- however -- skip the indexing the first time, knowing that the indexer will be called again upon raccess instantiation. This makes sense because the resource cannot be made public until the raccess object exists.

**Comment by alvacouch** [comment] 2016-04-28 21:08
@xuezhaokun Please see note above. Trick would be to simply not call index unless hasattr for 'raccess' returns True.

**Comment by alvacouch** [comment] 2016-04-29 14:24
@dtarb @rayi113 @jbradberry @xuezhaokun @mjstealey 

Current status report. 

1. Real-time updates of resource metadata seem to be working now. 
2. Real-time updates of public/discoverable flags are problematic and are not always logged. Even though the exact same object is used in both cases! Worse, it is possible to do this: 

* change to discoverable. 
* doesn't appear in discoverable list. 
* change title
* appears in discoverable list. 

We haven't posted the changes yet because of this bug. We are very close to having this working. 

We'll resume work on this this afternoon.

**Comment by alvacouch** [comment] 2016-04-29 20:59
@mjstealey @dtarb @jbradberry @xuezhaokun @rayi113
 
By George, I think we've got it! Current PR #1152 contains a real-time harvester that works. 

Solution and issues were truly bizarre. The super() problem (that there is no such thing as a real superclass in Django) bit us twice. 

First, recall that we installed SOLR by indexing the BaseResource class of which all real resource classes are proxy subclasses. Thus, BaseResource contains all metadata that the subclasses might expose. This means that we only need one SOLR indexing class for all kinds of resources. But this presents its own difficulties when we try to update or delete a resource in real time, because we receive an event that a subclass has been deleted and have to translate it to a superclass. 

1. We had to use the BaseResource upcast hack 
`newinstance = BaseResource.objects.get(pk=instance.pk) `
to upcast from an arbitrary resource subtype as a proxy class to the `BaseResource` class. This got updates working properly. 

2. Getting deletes working was even more tricky, because super() again failed us and the upcast trick above doesn't work because **the resource has already been deleted from Django** at the time of SOLR's handle_delete. This took some inventiveness: 

* We noted that a pre-cast version of the resource as a `BaseResource` exists in ResourceAccess.resource as a back-reference from the access control system. 
* So, instead of handling the delete event for the Resource,** we handled the delete event for the ResourceAccess object** (which is deleted as a result of deleting the resource), recovered the BaseResource pointer from it, and deleted that object (which still exists at that time) from SOLR!

(this took about 8 hours of Zhaokun and I working together; neither of us could have found this alone)

**Comment by alvacouch** [comment] 2016-04-29 21:13
Perhaps the proper way to do this is to insert a pre-delete signal. We can do that later. For now, it works properly.

**Comment by dtarb** [comment] 2016-04-30 02:23
I truly appreciate your persistence.  Let's hope this fix holds.

**Comment by mjstealey** [comment] 2016-04-30 14:37
@dtarb, @alvacouch - Took the latest updates to the [discovery-issue-fix](https://github.com/hydroshare/hydroshare/tree/discovery-issue-fix) branch and merged them with the release-candidate-1.6.10 branch.

This is running on: [https://alpha.hydroshare.org](https://alpha.hydroshare.org)

Results were the that merged branch passes all tests, but the PR to merge this into master failed one test. [Reference](http://ci.hydroshare.org:8080/job/pull-request-builder/798/testReport/junit/hs_core.tests/TestCreateResource/test_create_resource_without_content_files/)

More specific output:
**Error Message**
```bash
False is not true
-------------------- >> begin captured logging << --------------------
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'django.contrib.auth.models.Group'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'django.contrib.auth.models.User'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'theme.models.UserProfile'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'django.contrib.auth.models.User'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'hs_access_control.models.UserAccess'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'hs_labels.models.UserLabels'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: update SOLR for <class 'hs_core.models.GenericResource'> with short_id 330890f14b4549eab738d933b2d3d11c
hs_core.HydroRealtimeSignalProcessor: DEBUG: Skipped premature change to <class 'hs_core.models.GenericResource'>
hs_core.HydroRealtimeSignalProcessor: DEBUG: update SOLR for <class 'hs_core.models.GenericResource'> with short_id 330890f14b4549eab738d933b2d3d11c
hs_core.HydroRealtimeSignalProcessor: DEBUG: Skipped premature change to <class 'hs_core.models.GenericResource'>
hs_core.HydroRealtimeSignalProcessor: DEBUG: update SOLR for <class 'hs_core.models.GenericResource'> with short_id 330890f14b4549eab738d933b2d3d11c
hs_core.HydroRealtimeSignalProcessor: DEBUG: Skipped premature change to <class 'hs_core.models.GenericResource'>
hs_core.HydroRealtimeSignalProcessor: DEBUG: update SOLR for <class 'hs_core.models.GenericResource'> with short_id 330890f14b4549eab738d933b2d3d11c
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'hs_core.models.CoreMetaData'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: update SOLR for <class 'hs_core.models.GenericResource'> with short_id 330890f14b4549eab738d933b2d3d11c
hs_core.HydroRealtimeSignalProcessor: DEBUG: baseresource should_update is True
hs_core.search_indexes: ERROR: resource object does not have metadata field
hs_core.search_indexes: ERROR: resource object does not have metadata field
pysolr: DEBUG: Starting to build add request...
pysolr: DEBUG: Built add request of 1 docs in 0.00 seconds.
pysolr: DEBUG: Starting request to 'http://172.17.0.5:8983/solr/update/?commit=true' (post) with body 'u'<add><do'...
requests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None
pysolr: INFO: Finished 'http://172.17.0.5:8983/solr/update/?commit=true' (post) with body 'u'<add><do' in 0.033 seconds.
hs_core.search_indexes: ERROR: resource object does not have metadata field
hs_core.search_indexes: ERROR: resource object does not have metadata field
pysolr: DEBUG: Starting to build add request...
pysolr: DEBUG: Built add request of 1 docs in 0.00 seconds.
pysolr: DEBUG: Starting request to 'http://172.17.0.5:8983/solr/update/?commit=true' (post) with body 'u'<add><do'...
requests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None
pysolr: INFO: Finished 'http://172.17.0.5:8983/solr/update/?commit=true' (post) with body 'u'<add><do' in 0.140 seconds.
hs_core.HydroRealtimeSignalProcessor: DEBUG: baseresource should_update is True
hs_core.search_indexes: ERROR: resource object does not have metadata field
hs_core.search_indexes: ERROR: resource object does not have metadata field
pysolr: DEBUG: Starting to build add request...
pysolr: DEBUG: Built add request of 1 docs in 0.00 seconds.
pysolr: DEBUG: Starting request to 'http://172.17.0.5:8983/solr/update/?commit=true' (post) with body 'u'<add><do'...
requests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None
pysolr: INFO: Finished 'http://172.17.0.5:8983/solr/update/?commit=true' (post) with body 'u'<add><do' in 0.024 seconds.
hs_core.search_indexes: ERROR: resource object does not have metadata field
hs_core.search_indexes: ERROR: resource object does not have metadata field
pysolr: DEBUG: Starting to build add request...
pysolr: DEBUG: Built add request of 1 docs in 0.00 seconds.
pysolr: DEBUG: Starting request to 'http://172.17.0.5:8983/solr/update/?commit=true' (post) with body 'u'<add><do'...
requests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None
pysolr: INFO: Finished 'http://172.17.0.5:8983/solr/update/?commit=true' (post) with body 'u'<add><do' in 0.055 seconds.
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'hs_access_control.models.UserResourcePrivilege'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'hs_labels.models.ResourceLabels'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'hs_core.models.Title'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'hs_core.models.Language'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'hs_core.models.Rights'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'hs_core.models.Identifier'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'hs_core.models.Type'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'hs_core.models.Date'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'hs_core.models.Date'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class 'hs_core.models.Creator'> excluded from SOLR index
hs_core.HydroRealtimeSignalProcessor: DEBUG: update SOLR for <class 'hs_core.models.GenericResource'> with short_id 330890f14b4549eab738d933b2d3d11c
hs_core.HydroRealtimeSignalProcessor: DEBUG: baseresource should_update is True
pysolr: DEBUG: Starting to build add request...
pysolr: DEBUG: Built add request of 1 docs in 0.00 seconds.
pysolr: DEBUG: Starting request to 'http://172.17.0.5:8983/solr/update/?commit=true' (post) with body 'u'<add><do'...
requests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None
pysolr: INFO: Finished 'http://172.17.0.5:8983/solr/update/?commit=true' (post) with body 'u'<add><do' in 0.025 seconds.
pysolr: DEBUG: Starting to build add request...
pysolr: DEBUG: Built add request of 1 docs in 0.00 seconds.
pysolr: DEBUG: Starting request to 'http://172.17.0.5:8983/solr/update/?commit=true' (post) with body 'u'<add><do'...
requests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None
pysolr: INFO: Finished 'http://172.17.0.5:8983/solr/update/?commit=true' (post) with body 'u'<add><do' in 0.027 seconds.
--------------------- >> end captured logging << ---------------------
```

**Stacktrace***
```bash

  File "/usr/local/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/docker/hydroshare/hs_core/tests/api/native/test_create_resource.py", line 82, in test_create_resource_without_content_files
    self.assertTrue(res.created.strftime('%m/%d/%Y %H:%M') == res.updated.strftime('%m/%d/%Y %H:%M') )
  File "/usr/local/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
'False is not true\n-------------------- >> begin captured logging << --------------------\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'django.contrib.auth.models.Group\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'django.contrib.auth.models.User\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'theme.models.UserProfile\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'django.contrib.auth.models.User\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'hs_access_control.models.UserAccess\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'hs_labels.models.UserLabels\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: update SOLR for <class \'hs_core.models.GenericResource\'> with short_id 330890f14b4549eab738d933b2d3d11c\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Skipped premature change to <class \'hs_core.models.GenericResource\'>\nhs_core.HydroRealtimeSignalProcessor: DEBUG: update SOLR for <class \'hs_core.models.GenericResource\'> with short_id 330890f14b4549eab738d933b2d3d11c\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Skipped premature change to <class \'hs_core.models.GenericResource\'>\nhs_core.HydroRealtimeSignalProcessor: DEBUG: update SOLR for <class \'hs_core.models.GenericResource\'> with short_id 330890f14b4549eab738d933b2d3d11c\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Skipped premature change to <class \'hs_core.models.GenericResource\'>\nhs_core.HydroRealtimeSignalProcessor: DEBUG: update SOLR for <class \'hs_core.models.GenericResource\'> with short_id 330890f14b4549eab738d933b2d3d11c\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'hs_core.models.CoreMetaData\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: update SOLR for <class \'hs_core.models.GenericResource\'> with short_id 330890f14b4549eab738d933b2d3d11c\nhs_core.HydroRealtimeSignalProcessor: DEBUG: baseresource should_update is True\nhs_core.search_indexes: ERROR: resource object does not have metadata field\nhs_core.search_indexes: ERROR: resource object does not have metadata field\npysolr: DEBUG: Starting to build add request...\npysolr: DEBUG: Built add request of 1 docs in 0.00 seconds.\npysolr: DEBUG: Starting request to \'http://172.17.0.5:8983/solr/update/?commit=true\' (post) with body \'u\'<add><do\'...\nrequests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None\npysolr: INFO: Finished \'http://172.17.0.5:8983/solr/update/?commit=true\' (post) with body \'u\'<add><do\' in 0.033 seconds.\nhs_core.search_indexes: ERROR: resource object does not have metadata field\nhs_core.search_indexes: ERROR: resource object does not have metadata field\npysolr: DEBUG: Starting to build add request...\npysolr: DEBUG: Built add request of 1 docs in 0.00 seconds.\npysolr: DEBUG: Starting request to \'http://172.17.0.5:8983/solr/update/?commit=true\' (post) with body \'u\'<add><do\'...\nrequests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None\npysolr: INFO: Finished \'http://172.17.0.5:8983/solr/update/?commit=true\' (post) with body \'u\'<add><do\' in 0.140 seconds.\nhs_core.HydroRealtimeSignalProcessor: DEBUG: baseresource should_update is True\nhs_core.search_indexes: ERROR: resource object does not have metadata field\nhs_core.search_indexes: ERROR: resource object does not have metadata field\npysolr: DEBUG: Starting to build add request...\npysolr: DEBUG: Built add request of 1 docs in 0.00 seconds.\npysolr: DEBUG: Starting request to \'http://172.17.0.5:8983/solr/update/?commit=true\' (post) with body \'u\'<add><do\'...\nrequests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None\npysolr: INFO: Finished \'http://172.17.0.5:8983/solr/update/?commit=true\' (post) with body \'u\'<add><do\' in 0.024 seconds.\nhs_core.search_indexes: ERROR: resource object does not have metadata field\nhs_core.search_indexes: ERROR: resource object does not have metadata field\npysolr: DEBUG: Starting to build add request...\npysolr: DEBUG: Built add request of 1 docs in 0.00 seconds.\npysolr: DEBUG: Starting request to \'http://172.17.0.5:8983/solr/update/?commit=true\' (post) with body \'u\'<add><do\'...\nrequests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None\npysolr: INFO: Finished \'http://172.17.0.5:8983/solr/update/?commit=true\' (post) with body \'u\'<add><do\' in 0.055 seconds.\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'hs_access_control.models.UserResourcePrivilege\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'hs_labels.models.ResourceLabels\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'hs_core.models.Title\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'hs_core.models.Language\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'hs_core.models.Rights\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'hs_core.models.Identifier\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'hs_core.models.Type\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'hs_core.models.Date\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'hs_core.models.Date\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: Changes to <class \'hs_core.models.Creator\'> excluded from SOLR index\nhs_core.HydroRealtimeSignalProcessor: DEBUG: update SOLR for <class \'hs_core.models.GenericResource\'> with short_id 330890f14b4549eab738d933b2d3d11c\nhs_core.HydroRealtimeSignalProcessor: DEBUG: baseresource should_update is True\npysolr: DEBUG: Starting to build add request...\npysolr: DEBUG: Built add request of 1 docs in 0.00 seconds.\npysolr: DEBUG: Starting request to \'http://172.17.0.5:8983/solr/update/?commit=true\' (post) with body \'u\'<add><do\'...\nrequests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None\npysolr: INFO: Finished \'http://172.17.0.5:8983/solr/update/?commit=true\' (post) with body \'u\'<add><do\' in 0.025 seconds.\npysolr: DEBUG: Starting to build add request...\npysolr: DEBUG: Built add request of 1 docs in 0.00 seconds.\npysolr: DEBUG: Starting request to \'http://172.17.0.5:8983/solr/update/?commit=true\' (post) with body \'u\'<add><do\'...\nrequests.packages.urllib3.connectionpool: DEBUG: "POST /solr/update/?commit=true HTTP/1.1" 200 None\npysolr: INFO: Finished \'http://172.17.0.5:8983/solr/update/?commit=true\' (post) with body \'u\'<add><do\' in 0.027 seconds.\n--------------------- >> end captured logging << ---------------------'
```

**Comment by alvacouch** [comment] 2016-04-30 14:57
@xuezhaokun @dtarb @jbradberry @mjstealy 

This is very, very weird. We don't change the resource at all...! All we do is to read from it....!  We don't execute a single save()...!

The DEBUG messages are all correct. The system is working properly from that standpoint. 
The ERROR messages should probably be warnings: the resource is not indexed until it contains metadata.

**Comment by mjstealey** [comment] 2016-04-30 15:11
> the resource is not indexed until it contains metadata.

The error comes from this [hs_core/tests/api/native/test_create_resource.py](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/tests/api/native/test_create_resource.py)

Unsure as to the specifics of how this particular test operates, but that is what threw the error.

**Comment by jbradberry** [comment] 2016-04-30 15:26
The specific assertion that fails is this one: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/tests/api/native/test_create_resource.py#L82.  As an aside, using more specific assertion calls (in this case `assertEqual`) rather than wrapping a boolean expression in `assertTrue` will result in output that is more useful.

Tracing things over to the `create_resource` function, I find this: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/hydroshare/resource.py#L483.  Since the default value of `create_metadata` is `True`, this `save()` call will be executed.  Presumably `.save()` is overridden to update the updated time field?

**Comment by pkdash** [comment] 2016-04-30 18:06
@alvacouch @mjstealey Any idea how much time it to took for the real time update? I assume it's not more than a minute.

**Comment by alvacouch** [comment] 2016-04-30 22:13
It takes about a second. We can make this faster by skipping indexing of non-public resources.

**Comment by alvacouch** [comment] 2016-04-30 22:17
@jbradberry We certainly didn't call a new save. We've exposed a latent bug. 

The indexer skips any resource that doesn't have metadata and/or access control. So It does nothing at all until metadata is defined. And then, it only reads. 

I am puzzled.

**Comment by pkdash** [comment] 2016-04-30 22:28
The failing test has a comparison of date string value up to the minute. If the indexing upon resource creation is less than a second then that should not cause the mismatch in the test leading to test failure.

**Comment by alvacouch** [comment] 2016-04-30 22:45
@pkdash It takes about 5 seconds to create a new resource on our development instance. This includes indexing.

**Comment by pkdash** [comment] 2016-04-30 22:48
@alvacouch Are you able to reproduce this test failure locally?

**Comment by alvacouch** [comment] 2016-04-30 22:56
@pkdash No time to try right this second.

**Comment by pkdash** [comment] 2016-04-30 22:59
I guess if I pull this branch, I should be able to reproduce it.

**Comment by pkdash** [comment] 2016-04-30 23:26
I could not reproduce the error locally. I am not sure if the real time indexing happening locally.

**Comment by alvacouch** [comment] 2016-05-01 00:59
@pkdash:  

Hmm... It is possible that local indexing (with few resources) is faster! 

I can prevent the error.... but I have zero time in the next two days to test the fix.... The fix is to avoid indexing new resources until discoverable or public is true, as in issue #1183. Then the time for initial resource build will drastically decrease.

**Comment by pkdash** [comment] 2016-05-01 01:53
@alvacouch I used the discovery-issue-fix branch. Is that the right branch?

**Comment by alvacouch** [comment] 2016-05-01 02:20
@pkdash: yes, discovery-issue-fix is the proper branch. 

@xuezhaokun: See branch 1183-discovery-speed for some possible fixes. The basic algorithm is to delete anything that isn't public/discoverable from SOLR and to check whether it's there via a simple SOLR query: 

`self.hydro_resource_is_present(resource)` 

that queries SOLR by the base object id. I don't have time or energy to debug this. This should inform you of the basic pattern to use. **You will need to test this routine carefully.**

If you have time, please take a look, fix any errors, and merge into your PR. 

This implements most of issue #1183 

(I also switched logger.error to logger.debug in search_indexes.py.)

**Comment by xuezhaokun** [comment] 2016-05-01 02:33
@alvacouch I will take a look and do some tests on that branch.

**Comment by alvacouch** [comment] 2016-05-01 16:34
@xuezhaokun one note: 

It is possible that a delete of a non-existent SOLR record will not raise an exception, and that remove_object can safely be called without checking for existence first. This could be faster than checking for existence. I don't know.

**Comment by xuezhaokun** [comment] 2016-05-02 05:20
@alvacouch I do not know why I cannot check out your 1183 branch. I just copied HydroRealtimeSignalProcessor.py and search_indexes.py to my branch for testing. 
I fixed to a minor haystack syntax issue in HydroRealtimeSignalProcessor and did some tests on it. I think it works as we expect.

1. I created a new resource, and filled all the necessary metadata fields for making it discoverable. At this point, the resource was not indexed in SOLR so far.
2. I changed this resource from "Private" to "Discoverable". It was indexed in SOLR now. And we can find it on discovery page.
3. Then I changed it back to "Private". It  was removed from SOLR.
4. I deleted this record. SOLR did not raise any exception.

One thing I notice that if we want this strategy work properly, we can never do `./hsctl managepy rebuild_index`. Once we do a "rebuild_index", all the resources will be indexed in SOLR again.
I pushed the latest changes to my branch

**Comment by mjstealey** [comment] 2016-05-02 10:53
> we can never do ./hsctl managepy rebuild_index

Will need a tighter bounds on what **never** means.
Also, is there any negative effect to the `update_index` call? [Reference](https://github.com/hydroshare/hydroshare/blob/develop/hsctl#L330-L336)
I believe there is presently a nightly cron job that rebuilds the index using one or both of the above calls. (defer to @hyi for specifics)

The `rebuild_index` call is made twice during the `loaddb` portion which is triggered during a new install, or as a standalone command to use a new database: [Reference](https://github.com/hydroshare/hydroshare/blob/develop/hsctl#L256-L260)

**Comment by jbradberry** [comment] 2016-05-02 12:27
The proper way to make sure that your indexing only pulls in the items that you want is to override `index_queryset`, using the exact filter statements necessary.  In this case it sounds like you would want something like

        def index_queryset(self, using=None):
            return self.get_model().objects.filter(discoverable=True)

**Comment by jbradberry** [comment] 2016-05-02 12:29
Once you do this, running `update_index` or `rebuild_index` will be fine.

**Comment by alvacouch** [comment] 2016-05-02 12:58
@xuezhaokun @mjstealey 
I agree with Jeff. However, I think the statement you need is:

def index_queryset(self, using=None): 
    return self.get_model().objects.filter(SQ(raccess__discoverable=True) | SQ(raccess__public=True))

**Comment by alvacouch** [comment] 2016-05-02 13:03
@xuezhaokun 
(You need to put the above code into your SearchIndex subclass.)

**Comment by jbradberry** [comment] 2016-05-02 13:03
`SQ` -> `Q`

**Comment by alvacouch** [comment] 2016-05-02 13:04
Fixed. Was writing queries in SOLR....!

**Comment by hyi** [comment] 2016-05-02 13:37
@alvacouch @xuezhaokun @mjstealey Yes, a nightly running cron job is set up only for update_index call. Do we still need this nightly cron job after this real-time index update working for resource deletion and resource update?

**Comment by alvacouch** [comment] 2016-05-02 14:33
@hyi @mjstealey @jbradberry @xuezhaokun 

A facetious answer: We need to keep running the nightly indexes **only if we screwed up!**

If we did everything correctly, we will not have to update_index overnight ever again.

**The only open question** is whether what we are doing is going to be fast enough that queueing will not be necessary. The next step would be to queue anything we really need to queue.

**Comment by xuezhaokun** [comment] 2016-05-02 14:34
@alvacouch I edited the index_queryset function, and did couple tests on "rebuild_index". I think it works properly now. We only index the discoverable or public resources. I pushed the latest version.

**Comment by dtarb** [comment] 2016-05-03 15:47
Responding to the facetious answer only if we screwed up, it is almost impossible (and I hesitate to say almost) to get things perfectly right the first time in a system like this, so it seems like a periodic index rebuild is the conservative approach.  Perhaps it can be less frequent than nightly, but we need to figure out logging and system monitoring to stay on top of this.

**Comment by jbradberry** [comment] 2016-05-03 17:29
I would like to know why we feel that the indexed resources should be obtained in their `BaseResource` form before indexing.  If these things are all proxies of `BaseResource`, they should all be exposing the same fields and should by-and-large be compatible in the indexer.  In order to support the multiple models using the same indexing code and logic, one would be able to do something like

    class BaseResourceIndex(indexes.SearchIndex):  # note the removal of indexes.Indexable!
        # buik of the indexing logic here...

    class MyProxySubclassIndex(BaseResource, indexes.Indexable):
        def get_model(self):
            return MyProxySubclass

    class MyProxySubclass2Index(BaseResource, indexes.Indexable):
        def get_model(self):
            return MyProxySubclass2

and so on.  This would have the advantage of making Haystack aware of the different types of resources, as well as obviating the need to cast the object back to the plain `BaseResource`.

**Comment by alvacouch** [comment] 2016-05-03 17:40
This is pretty simple to explain: 

1. There are 25+ of these now. 
2. We expect 50+ by end of grant. 
3. These are largely created by people without knowledge of the discovery system. 
4. We don't want to make lots of updates to this file. 

It is a software maintenance issue.

**Comment by hyi** [comment] 2016-05-16 14:09
@alvacouch @xuezhaokun I believe this issue can be closed. Please check it and close if it has been resolved.

**Comment by xuezhaokun** [comment] 2016-05-16 14:32
I think we can close this issue.

**Closed by xuezhaokun** 2016-05-16 14:32 UTC
Labels: Discovery, in progress
