### ISSUE TITLE
MOPEX needs

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1963] opened 2017-03-21 19:17 UTC
@dtarb @aphelionz @pkdash
After conferring with Rick Hooper (@rphtufts) and @Lizabrazil ,  there are several limitations of the current HydroShare that are preventing -- or at least greatly impeding -- publication of the MOPEX data through HydroShare. This is a multi-dimensional issue with deficiencies in three areas: 

- [ ] Composite resource doesn't yet handle geographic features or referenced time series. 
- [ ] REST API doesn't allow editing of composite resource metadata and populating composite resources. 
- [ ] Discovery doesn't react usefully when faced with composite resources. 

This is an ideal scenario. We have considered utilizing collection resources instead, and faced almost identical problems: 

- [ ] REST API doesn't allow populating collection resources or referenced time series? 
- [ ] Discovery doesn't react usefully when faced with collections of resources (or collections of collections of resources). 

-----------------

At a more detailed level, 

* A "MOPEX site" contains six related resources, including a shapefile (geographic feature) and five reference time series (referencing a server at CUAHSI.org). 
* A "MOPEX network" is a series of "MOPEX site"s. 
* It makes sense to us to populate 500 "MOPEX sites" as composite resources, and then organize them into a "MOPEX network".
* Alternatively, we could create "MOPEX time series" and "MOPEX shapefiles", and bind these into collections called "MOPEX sites" and then make an overall collection called "MOPEX network" that contains these.
* Neither of these solutions is currently practical.  

The MOPEX time series server has been built already, but automatically populating the resources that point to it is currently not possible due to unimplemented parts of the REST API. 

---------------------

Using either solution, we face serious limits in terms of discovery and data interpretation. 

* There is no current way to navigate from a resource to the collections in which it appears.

    * Thus, there is no way to relate a "MOPEX site" to the set of "All MOPEX sites" = "MOPEX Network". 

* Collections come up after instances of collections in discovery, based upon the way things are weighted when searching. 

    * Thus, there is no way in discovery to discover and depict that one is matching a hierarchy of things rather than a single thing. Nor is there an easy way to move from the hierarchy to the individual and from the individual to the hierarchy.

**Comment by alvacouch** [comment] 2017-03-22 15:56
@xuezhaokun We have some work to do on this one. The most obvious thing we can do is to boost text matching by placing all of the metadata from a collection or composite resource into the SOLR text field. This will make the collection naturally come up before the individual resources in SOLR order.

**Comment by dtarb** [comment] 2017-03-27 15:00
@danames can you let me know if your group can work on the reference time series and geographic feature file types.  @pkdash could give guidance.

**Comment by aphelionz** [comment] 2017-12-18 19:33
@alvacouch @dtarb Where ware we at on this?

**Comment by Lizabrazil** [comment] 2019-04-09 22:28
@dtarb can we close this? I think we are good except i do not know about the REST API issues.

**Comment by dtarb** [comment] 2019-04-09 22:33
I believe that composite as currently deployed meets the needs of this case so am closing, while mentioning @alvacouch and @rphtufts.  If there are MOPEX needs not met, please reopen and indicate what the problem is.

**Closed by dtarb** 2019-04-09 22:33 UTC
Labels: Architecture, enhancement, low priority
