### ISSUE TITLE
Sorting ~~my resources~~ Discover by last modified date doesn't work

### ISSUE THREAD

**Issue by jirikadlec2** [hydroshare/hydroshare#863] opened 2016-01-06 02:44 UTC
I have resources on HydroShare and I want to sort my resources by the "last modified" date. However when I click on the 'last modified' column heading, the resources get sorted in a random order. Please see the screenshot. After I clicked on 'last modified' (sort descending) the first row should be the resource from Jan. 6, 2016, 2:22 a.m. Instead it's a random resource from 16th October.

![screenshot 2016-01-05 19 39 30](https://cloud.githubusercontent.com/assets/4144642/12133645/77ccdd0e-b3e4-11e5-8d17-9f43ffeb2403.png)

**Comment by mauriel133** [comment] 2016-02-26 22:16
@jirikadlec2, please confirm that the issue is fixed, and if so close this issue.

**Comment by mjstealey** [comment] 2016-05-07 12:39
@mauriel133 - Sort by Last Modified date on the Discover page isn't working as expected.

![screen shot 2016-05-07 at 8 39 40 am](https://cloud.githubusercontent.com/assets/5332509/15092137/1e21fd74-142f-11e6-96c0-8877b7714816.png)

**Comment by dtarb** [comment] 2016-05-07 13:30
The sorting seems to be  alphabetic based on the words of the date.  However I think it needs to work on Discover similar to My Resources where @mauriel133 worked hard to get date-time ordering paying heed to both date and time.  It may be a different challenge in Discover, as for My Resources I believe this in JS on the front end, but for Discover loading the entire resource listing to the front end is not really scalable.

**Comment by mjstealey** [comment] 2016-05-07 13:40
> The sorting seems to be alphabetic based on the words of the date

Yes, perhaps this is what we expected :wink:

Unsure if same methods can be applied to Discover page as the my resources page, but thought it worth  pointing out. (Sorry @mauriel133 for hijacking an old, but not yet closed issue)

**Comment by mauriel133** [comment] 2016-05-07 17:13
I think the same method can be reused. I'll have a look.

**Comment by mauriel133** [comment] 2016-08-05 17:55
Sorting has been mapped correctly and is deployed at www. Please verify and close.

**Comment by dtarb** [comment] 2016-08-06 13:22
Seems correct now.

**Closed by dtarb** 2016-08-06 13:22 UTC
Labels: bug, Close Me!, in progress
