### ISSUE TITLE
JavaScript attachment to account verification email

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#549] opened 2015-07-29 21:42 UTC
I just created a new account on dev.hydroshare.org to do some testing.  The account verification email was delayed and triggered a warning from USU's email spam filters.  Here's the message I received (minus the link to verify my account).

Warning:The JavaScript (.js) attachment from the sender has been replaced with an explanation in ATT00001.c by USU's email filters.  

If the message and attachment were unexpected and unexplained, then the filter might have just saved you from opening a malware-containing attachment.  Spammers are no longer just trying to fool the gullible but are targeting the curious skeptic as well.

If this message was from a known sender and you were expecting the attachment, please direct the sender to use USU's Big File Transfer utility https://bft.usu.edu to deliver executable file types to you.
==== ORIGINAL MESSAGE BEGINS BELOW THIS LINE ====
Hey there, thanks for creating your account.

Please use the link below to activate it.

**Comment by dtarb** [comment] 2015-07-29 22:30
I just created an account on dev and had no issues (no attachments) with the activation email

**Comment by dtarb** [comment] 2015-08-17 16:24
See #565.  @mjstealey can you please test this after addressing 565 and have others test this too to see if it persists.

**Comment by dtarb** [comment] 2015-09-30 16:50
Seems to be a quirk.  Not reproducible. Closing.

**Closed by dtarb** 2015-09-30 16:50 UTC
Labels: Clean up
