### ISSUE TITLE
"Send Invitation" button styling is noticable deviation from site standard

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2821] opened 2018-07-09 19:56 UTC
The button is directly pressed against the search box - no padding.  Additionally, the coloring and lack of border-radius rounded corners make this button really stand out from the others in the HydroShare system

[180709-test-files-005v.zip](https://github.com/hydroshare/hydroshare/files/2177834/180709-test-files-005v.zip)

**Comment by ChristinaB** [comment] 2019-06-11 15:51
@sblack-usu  - I am adding on an additional point to a related issue.  From a group, as an owner, the invite pop up hangs when I try to invite hydroshare users to the group.  With similar issues, the pop up box would execute, but the pop up wouldn't update.  In this case, the invitation is not sent and the box hangs indefinately.  I tried to invite people for a conference workshop this afternoon so if there is a quick workaround, please let me know.

**Comment by sblack-usu** [comment] 2019-06-11 16:41
Thanks for pointing this out @ChristinaB.  We are aware of the problem from a support issue logged a bit ago.  I've identified why it's broken and have asked @Maurier to take a look at it.  This will require a code change, but it should be limited to the frontend so it's likely we could push out a patch release without any downtime.  The bug was likely introduced by some refactoring on the group page with the introduction of the vue.js.

**Comment by Maurier** [comment] 2019-06-12 00:59
I will be using this ticket to fix this and some other bugs caused by some recent work done in the Groups page here: https://github.com/hydroshare/hydroshare/pull/3368

- Unable to send Group invitations.
- Unable to filter members in the "Members" tab or check pending requests.
- Style and layout errors on Shared By panel
![image](https://user-images.githubusercontent.com/2448568/59316218-8cf0c980-8c7a-11e9-97cc-ff12795bebab.png)
- Unable to expand Resource Abstracts.
- First Author not populated in table for some cases
![image](https://user-images.githubusercontent.com/2448568/59316261-c590a300-8c7a-11e9-8feb-5b5bb824a3df.png)

I most of this is caused by the same work done in the PR linked above.

**Comment by eclark-cuahsi** [comment] 2021-08-04 20:27
@Castronova I believe this falls under Pages and General HS Components. Can you please review and reassign if needed.

**Comment by dtarb** [comment] 2022-01-26 19:40
Closing as styling work has been done.

**Closed by dtarb** 2022-01-26 19:40 UTC
Labels: bug, Pages and General HS Components
