### ISSUE TITLE
Use metrics kibana error

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2139] opened 2017-05-27 14:13 UTC
When I go to Kibana from https://pages.hydroshare.org/about-hydroshare/usage-metrics/ the first thing I see is this error.

![image](https://cloud.githubusercontent.com/assets/3456833/26522015/37a98c08-42b4-11e7-89c3-8984c0072af4.png)

**Comment by Castronova** [comment] 2017-05-30 15:46
@dtarb Looks like this is due to a misconfiguration in the logstash parser.  I'm working to fix this now.

**Comment by Castronova** [comment] 2017-05-31 14:20
This was fixed with by adjusting the logstash configuration.

**Comment by dtarb** [comment] 2017-06-16 04:42
Broken.  Again. 6/15/17.
![image](https://user-images.githubusercontent.com/3456833/27212255-eb8bde4e-521b-11e7-8362-934d052df432.png)

**Comment by Castronova** [comment] 2017-06-16 18:26
I get the following.  6/16/17
![image](https://user-images.githubusercontent.com/4822372/27239625-b942c52c-529f-11e7-8c2d-0d9006bb8788.png)

**Comment by Castronova** [comment] 2017-06-16 18:29
@dtarb Are you changing the date range?  This is not supported for the Users and Resources statistics due to the way the log records are stored in elastic search.  This is a limitation that I've mentioned to the team on the Wednesday calls and may be causing your error.   

Changing the date range will be possible when my HydroShare PR gets deployed in the next HS release.

**Comment by dtarb** [comment] 2017-06-16 18:50
I have not (knowingly) changed date range.  (I am not sure I would know how).  Here is a wild speculation.  Could it be time of day and time zone related.  Perhaps Ray and I tried at a time of day when HydroShare was advanced to the next day GMT but Kibana was the previous day EDT and that is causing problems.   Trying again later tonight could test this.

**Comment by Castronova** [comment] 2017-06-17 05:01
@dtarb It certainly could be a time zone related issue.  The `user` and `resource` graphs are generated from a report date that's relative to the current datetime.  The latest HS PR will fix this, but in the meantime I'll see if there's something I can do to prevent this error from occurring.

**Comment by dtarb** [comment] 2017-06-17 11:13
I checked late night (6/16) and early morning (6/17) and was unable to trigger error so speculation about time does not seem to be the case.  

I did notice that if I click on timelion I get the following error 
![image](https://user-images.githubusercontent.com/3456833/27252437-b1692c3e-531b-11e7-8a2c-0b6a1c690ecb.png)
I am not sure if this is new.

**Comment by Castronova** [comment] 2017-06-26 18:19
@dtarb It turns out that this error was caused by a failure in the Jenkins job that assembles the user and resource csv documents, which are then sent to the usagemetrics server and stuffed into elasticsearch.  The error was the result of an irods file not existing and was resolved by deleting the "broken" resource (happened to be a test resource owned by me).  

To prevent django->irods inconsistencies from breaking the usage metrics in the future, I created a new issue to include error checking to the usagemetrics dump scripts. https://github.com/hydroshare/hydroshare/issues/2189

**Closed by Castronova** 2017-06-26 18:19 UTC
