### ISSUE TITLE
Group Membership Request Link Invalid

### ISSUE THREAD

**Issue by AmberSJones** [hydroshare/hydroshare#1816] opened 2017-02-01 22:01 UTC
When a user requests to be a member of my Group, I receive an email with a link to confirm their membership. Sometimes when I click on the link, I receive a message that the link is no longer valid, and the user is not added to my group.

![image](https://cloud.githubusercontent.com/assets/5023186/22528133/27dbad94-e88f-11e6-98eb-8672b167c7a0.png)

**Comment by pkdash** [comment] 2017-02-01 22:35
@AmberSJones There is a time limit during which the link is valid. Did you click the link as soon as you get the email?

**Comment by AmberSJones** [comment] 2017-02-01 23:01
In this case, I clicked on it within a half hour.

**Comment by dtarb** [comment] 2017-04-03 16:50
Unable to reproduce in testing between @pkdash and me.  Closing, but @AmberSJones feel free to reopen if you encounter this again (and check that the email has not somehow corrupted the link).

**Closed by dtarb** 2017-04-03 16:50 UTC

**Comment by AmberSJones** [comment] 2017-04-03 21:31
Sounds good, thanks for following up.
