### ISSUE TITLE
No file size or resolution limits on group images

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2912] opened 2018-09-26 19:07 UTC
100 MB, approx 8k x 11k resolution image is accepted by the system.  Load times for the pages which use the image (e.g. Groups finding page if group is public) become substantially larger due to the large image - so it's not like the image is scaled on the backend and then the scaled image is used.  

[003.zip](https://github.com/hydroshare/hydroshare/files/2421192/003.zip)

**Comment by aphelionz** [comment] 2018-10-01 20:33
Duplicate of #2637

**Closed by aphelionz** 2018-10-01 20:33 UTC
