### ISSUE TITLE
Profile edit fields do not align

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4093] opened 2021-01-09 01:34 UTC
On Chrome v86, the profile edit fields are not consistently sized/aligned.

<img width="616" alt="profile-edit-fields" src="https://user-images.githubusercontent.com/43424907/104079324-74e38200-51f0-11eb-87b3-562f157b6a8b.png">

**Comment by martinseul** [comment] 2021-03-22 16:51
@ndebuhr I checked on beta and this seems fixed, please retest and close if resolved

**Comment by hydrocheck** [comment] 2021-04-03 00:39
Issue is reproducible across all tested Chrome configurations.

Chrome v89 on Windows 10
<img width="984" alt="chrome89-windows10" src="https://user-images.githubusercontent.com/43424907/113463352-46da9c00-93f3-11eb-9e4f-6618c8ac9cdc.png">

Chrome v89 on MacOS 10.15
<img width="996" alt="chrome89-mac10 15" src="https://user-images.githubusercontent.com/43424907/113463358-4d691380-93f3-11eb-98fc-4145b8fc6575.png">

Chrome v86 on MacOS 11.0
<img width="990" alt="chrome86-mac11 0" src="https://user-images.githubusercontent.com/43424907/113463365-535ef480-93f3-11eb-9703-e4f64107c1a7.png">

Chrome v86 on Windows 8.1
<img width="979" alt="chrome86-windows8 1" src="https://user-images.githubusercontent.com/43424907/113463375-5a860280-93f3-11eb-9359-f841f7c569ba.png">

However, it is worth noting that the layout shifts at some (thin) breakpoint.  This is possibly at any resolution below about 1200 (e.g., a 720p monitor).  Full screen profile page on any reasonably modern computer, Chrome v86+, should consistently reproduce the issue, as far as I can tell.
<img width="773" alt="thin-resolution" src="https://user-images.githubusercontent.com/43424907/113463426-928d4580-93f3-11eb-92b1-5d62541dbf95.png">

**Comment by horsburgh** [comment] 2021-08-25 15:54
The layout of the profile editing page is now different than the screen shots in the issue. I can't reproduce this issue in Chrome, Firefox, or Safari browsers. Closing.

**Closed by horsburgh** 2021-08-25 15:54 UTC
Labels: Cosmetic, good-first-issue, User Profile, Pages and General HS Components
