### ISSUE TITLE
Discover Listings Are Not Always Consistent

### ISSUE THREAD

**Issue by eclark-cuahsi** [hydroshare/hydroshare#4030] opened 2020-11-09 15:35 UTC
Reported by @dtarb on 11/1/2020

I just went to HydroShare and noticed an inconsistency in Discover

I first saw 

![Discover Inconsistent 1](https://user-images.githubusercontent.com/64596508/98562216-cc5c8480-2277-11eb-9cf6-6daacacb767c.png)

Notice two resources authored by Salehabadi.  These are what I am working with her on, and there were 3 resources we worked on yesterday.  I was puzzled why the 3rd was not listed in the default last modified listing.   I found the resource by clicking on it – it is a member of the collection.  Then when I went back to discover it is there.

![Discover Inconsistent 2](https://user-images.githubusercontent.com/64596508/98562253-d9797380-2277-11eb-97db-f493b61e5b8b.png) 

This may be hard to reproduce – but there is something causing Discover listings to not always be consistent.

**Comment by cuahsimarko** [comment] 2020-12-15 15:48
Unable to reproduce need more information

**Comment by dtarb** [comment] 2020-12-17 00:55
Closing.  I suspect this may be due to arbitrariness in the way ties are resolved sorting by last modified date.  But as hard to document an error am closing.

**Closed by dtarb** 2020-12-17 00:55 UTC
Labels: BLOCKED, Discover
