### ISSUE TITLE
Enable hydroshare groups and organizations as authors (creators) and contributors of a resource

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1360] opened 2016-07-25 15:54 UTC
If you look at https://www.hydroshare.org/resource/fe1f1b565cbe40b3a57c845a0a55e460/, it is a resource where I intended to have the HydroShare Developers team represented by the group https://www.hydroshare.org/group/2 as an author.  The following enhancements are needed to facilitate this
- [ ] Allow selection of a group when an Author or contributor is added.  Right now we only allow selection of a user and filling out the blank form
- [ ] Require either Name or Organization in the Author dialog box, rather than Name being the only field required.  
- [ ] If Organization is the field provided spell it out fully in citation rather than initials, to avoid stating the citation author as "H Developers"
- [ ] Use the homepage link to establish a link in the presentation of Authors.

**Comment by horsburgh** [comment] 2016-07-27 14:03
Is this a duplicate of #855? Can we consolidate to one issue?

**Comment by hyi** [comment] 2016-08-01 14:06
I believe #855 is a main subset of this issue. Since #855 has a thread of discussions on the citation for groups/organizations, I will not consolidate them for now, but note the relationship between the two issues, so that they can be managed together. Assigning it to @pkdash for now, who may assign to others as needed.

**Comment by pkdash** [comment] 2017-01-30 17:23
@dtarb Is this still an issue? I believe this has been resolved with the work @jsadler2 and @mohamedmorsy did with the citation.

**Closed** 2017-02-01 04:37 UTC
Labels: Medium Priority
