### ISSUE TITLE
Organizations do not update for the resource author metadata

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3651] opened 2019-11-04 02:34 UTC
If you create a resource and check the author metadata, it will show the author's organizations.  If you then update your profile to new organizations, then return to that resource, the author metadata does not show as updated.  Organizations which no longer apply are shown.  This is true for other author metadata as well (e.g. phone, email, etc.)

[003.zip](https://github.com/hydroshare/hydroshare/files/3802543/003.zip)

**Comment by horsburgh** [comment] 2019-11-04 06:03
This one is by design. The author metadata is a snapshot of the information supplied by the user. It can be copied from the profile for existing HydroShare users, but this is a one-time copy. It is only updated if the user chooses to modify author information. When resources are published, the author information represents a snapshot in time of what the authors' affiliations were when the resource was published.

**Comment by martinseul** [comment] 2019-11-18 15:41
i will close the issue

**Closed by martinseul** 2019-11-18 15:41 UTC
