### ISSUE TITLE
When creating new resources, author and owner middle initials are ignored

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2276] opened 2017-08-16 19:06 UTC
My profile includes my middle initial. It should be used in any resources I create or that I am an author of. But, when I create a new resource now, I only see my first and last name. I don't know if this is just a display issue (e.g., on the resource landing page the middle initial is not shown) or if it has also been lost from the resourcemetadata.xml file as well.

This is a regression. It used to work correctly.

**Comment by pkdash** [comment] 2017-08-18 02:26
@horsburgh A quick look at the UI code tells me it's a display issue.

**Comment by engineSound** [comment] 2018-10-03 15:31
The full name including middle initial is retrieved from “name” field a creator object. 
**https://github.com/hydroshare/hydroshare/blob/05dc7e33470691b3727ea9d0f64a34ac7ea9ddd7/theme/templates/resource-landing-page/resource-header.html#L11-L13**
The creator’s fields are populated in serialization.py. As long as the name has middle initial set over there, the view will show the middle initial correctly. @aphelionz ,  a SME (subject matter expertise) in this area may take over.

https://github.com/hydroshare/hydroshare/blob/05dc7e33470691b3727ea9d0f64a34ac7ea9ddd7/hs_core/serialization.py#L485

**Comment by engineSound** [comment] 2019-01-31 16:55
Based on the UI analysis, need backend help to provide some feedback. @cuahsimarko

**Comment by engineSound** [comment] 2019-01-31 19:03
@hyi Can you shed light on this issue? I think the middle name setting is from the backend.

**Comment by hyi** [comment] 2019-01-31 20:02
@engineSound I had never paid much attention to middle name, but just took a look at the code base. It appears we have middle_name in user profile model and is accounted for in profile page display, but only a name field in creator and its parent party model which is used for front end page display. If middle name is not accounted for in the name field, the middle name will not show up. So it looks to me like a back end issue, not a front end issue.

**Comment by hyi** [comment] 2019-01-31 21:32
Feel free to assign it to me or @sblack-usu or @pkdash

**Comment by engineSound** [comment] 2019-01-31 21:33
@hyi I chose the first one on the list.

**Comment by hyi** [comment] 2019-02-01 22:35
@horsburgh After looking into the code base trying to fix this, I am convinced this is not a regression issue. The reason is that the default Django user model does not support middle name at all, but only first name and last name. We use Django's ```get_full_name``` method on the User model in several places to populate the name for authors, creators, and contributors on resource landing page, which is a concatenation of first name and last name with a space separator. Because of this, Our UserProfile model which is linked to User model has one additional customized field `middle_name``` which keeps track of user's middle name and it is displayed on user profile page. To have this `middle_name``` field external to User model displayed on resource landing page, I will have to modify all places where user.get_full_name() is used with a customized method to retrieve middle name from user profile model and put it between the first and last names. Since this is not a regression issue, I want to confirm with you whether we want to make this change before I go ahead to implement it.

**Comment by hyi** [comment] 2019-02-02 00:54
@horsburgh In addition, data migration will be needed to add middle name if it exists in user profile to name field of metadata for all creators and contributors.

**Comment by hyi** [comment] 2019-02-04 17:06
@horsburgh I brought up this issue briefly during the coordination call today and @dtarb chimed in with his input on this issue. Specifically, @dtarb thinks the middle name should be taken into account when the user is creating the resource, but not back-propagate to those resources the user created before he or she updated the middle name from profile page. This means we don't need data migration to migrate the old user party metadata to take care of middle names from UserProfile model as I initially suggested above, but only take care of having middle name accounted for at resource creation phase without involving data migration. This would be a simple fix if we go as @dtarb suggested. @dtarb please correct me if I am not accurate on anything I conveyed here on your behalf. @horsburgh Let us know what you think. If you agree with what @dtarb suggested, I can create a PR quickly to address this issue.

**Comment by dtarb** [comment] 2019-02-04 17:14
That is consistent with what I said.  It is based on resource author and contributor records being separate from the user profile.  They reflect the author and creator at the time they are added to the resource.  Note that this may be after resource creation, in the case of adding a second author or adding a contributor.  Once author and contributor information are part of a resource's metadata, their updating is only by someone editing the resource and is not at all related to what a user does on their profile page (such as maybe change organization, or adjust their name).  As I understand this, this issue is about getting the name right in the first place, and in this case if there is a middle initial there it is not being copied into the resource.

**Comment by hyi** [comment] 2019-02-05 22:09
Thanks @horsburgh. Have created a PR to address this issue and asked @pkdash to code review. Let me know if you want me to deploy the fix to a test VM for you to try out.

**Comment by horsburgh** [comment] 2019-02-05 22:19
@hyi - I'm happy to test whenever. I could do that now, or I guess we could wait until we stack up a few other things that need deployment for testing. It's up to you.

**Comment by hyi** [comment] 2019-02-06 14:35
@horsburgh I have just merged the PR to develop branch. Since the fix is pretty simple and given the fact that we will not do data migration to back-propagate middle name to existing resource creators/contributors/authors, Let me check with @sblack-usu to see if this fix can make into 1.19 release which is scheduled for next Tuesday. If it could make into 1.19 release, you could just test on beta for 1.19 release candidate without deploying it to a separate VM for testing. @sblack-usu This is the PR that just got merged into develop for fixing this issue: https://github.com/hydroshare/hydroshare/pull/3123. Let me know if you think it is appropriate to get this into 1.19 release. I can then create a PR against 1.19 tag to get this fix into 1.19 release candidate.

**Comment by cuahsimarko** [comment] 2019-02-06 14:49
This is already in Beta. I vote for more discipline around releases.

**Comment by dtarb** [comment] 2019-02-06 15:07
I support the vote for more discipline.  The reason for this discipline is for us to be efficient as developers, and once a candidate release (CR) is cut and deployed to beta the only changes to it should be fixes that emerge from the CR testing and that would block or reflect poorly on the deploy.  I think that if we follow this principle we will be able to be more efficient and not have to wait too long for the next release that does include this.

I suggest you deploy this on another staging machine for Jeff to test.

**Comment by engineSound** [comment] 2019-02-06 15:27
@hyi Good job for the quick fix. Thank you for bring this 1.19 timeline up. @dtarb @cuahsimarko I have a couple of candidates in the similar situation. The signal is clear to me that I need to hold them in another place for the next train.

**Comment by hyi** [comment] 2019-02-06 18:04
@horsburgh I have deployed the fix to park for you to test. You will have to sign up to create a new account there and go to https://nginx1-beta.hydroshare.org:8443/webmail/src/login.php to login and find the user account activation email, then click on the link to activate your account. For login credential, you should be able to find them from the latest conversation between my and Phuong on slack develop channel. Let me know if you have issues creating your test account on park.

**Comment by sblack-usu** [comment] 2019-02-06 22:20
Unless it's a regression that requires a hotfix, I'd rather have developments that finish after the release has been cut to wait for the next one.

**Comment by horsburgh** [comment] 2019-02-08 00:27
@hyi - I just tested this on park and it seems to be working correctly for the Author field. When I add a middle name to my profile it gets copied into the author information for the resource I created. I noticed that it didn't get copied into the Owner. I'm assuming we might as well do both?

![image](https://user-images.githubusercontent.com/3485902/52451736-6f112d80-2afd-11e9-8000-81120bd7f90c.png)
 
![image](https://user-images.githubusercontent.com/3485902/52451759-8d772900-2afd-11e9-9b3c-35a31f7a62ec.png)

**Comment by hyi** [comment] 2019-02-08 01:48
@horsburgh agreed middle name needs to be reflected in owners as well. Will look into this further to get this fixed.

**Comment by hyi** [comment] 2019-02-08 15:33
@horsburgh I have made a further fix to address your comment above. Park is updated with the further fix, so you can test it again on park whenever you have a chance. Your user account and resources are all preserved since the issue is purely template display-related. You don't even have to create a new resource to test although you are welcome to do so for more thorough testing. Middle name should be taken into account in all fields including owners when you refresh the resource landing page for the old resource, and all should be working for a new resource as well. Let me know if you notice anything else that I missed regarding this issue.

**Comment by Maurier** [comment] 2019-02-08 16:44
@horsburgh Do we also want the middle name in auto complete inputs? In this case we are not displaying it right now.
![image](https://user-images.githubusercontent.com/2448568/52492281-19cd2e80-2b86-11e9-8e90-2a6e9eccc1c8.png)

**Comment by horsburgh** [comment] 2019-02-08 16:48
It is certainly possible as HydroShare usership grows that we might need disambiguation of users by including their middle names here. If there are two users with the same first and last names, I can usually tell them apart by the middle name (because I might know the middle name of the person I'm looking for), whereas usernames are chosen by the user, could be something completely unrelated to their name, and might not help me tell them apart.

 If it's easy to add it in, I think we should display as much name information as we have for users. 

Is there anywhere else we should also be looking for filling in middle names?

**Comment by Maurier** [comment] 2019-02-08 16:51
@hyi As I am debugging this code already I'll try to add the middle name for the case above. As I'm looking around, it seems that @hyi already took care of all other occurrences.

**Comment by Maurier** [comment] 2019-02-08 17:07
@horsburgh I added the middle name to these autocomplete widgets as well. That should help with disambiguation as you describe.

![image](https://user-images.githubusercontent.com/2448568/52493702-5e0dfe00-2b89-11e9-9085-4a9eac61d4d8.png)

**Comment by horsburgh** [comment] 2019-02-08 20:20
@hyi - I just tried this out on park. It looks good to me with the latest edits to cover author, contributor, and the users autocomplete. Thanks!

**Comment by hyi** [comment] 2019-04-09 19:08
The fix has been deployed a couple of releases back. Closing.

**Closed by hyi** 2019-04-09 19:08 UTC
Labels: (3) Large Effort, High Priority, Resource Model, bug, in progress
