### ISSUE TITLE
Resource Rating Functionality Missing

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#480] opened 2015-06-09 20:13 UTC
In the latest version of HydroShare (hydroshare.org) users can rate comments, but are unable to rate resources.  Users should have the ability to rate (or +1) individual resources.

**Comment by hyi** [comment] 2015-06-09 20:35
This issue is a regression resulting from three lines being dropped off from genericresource.html which was probably caused by merging somewhere along the way. Have added them back and tested on my local 446-feature branch. The lines added can be seen here: https://github.com/hydroshare/hydroshare/commit/4793dba060a58ff3079dff3995c4c52766afe42d. I am including this fix in my 446-feature branch which is slated as a potential hot fix for NFIE release. If vetted by the team for a NFIE hot fix release, this fix will be included together with on-demand bagging implementation for large resource metadata update performance improvement.

**Comment by hyi** [comment] 2015-06-24 15:39
Ready for testing on park.hydroshare.org

**Comment by dtarb** [comment] 2015-07-05 21:26
Tested and appears to be working correctly on both park and www (via the hotfix I assume).

**Closed by dtarb** 2015-07-05 21:26 UTC
Labels: bug, ready for testing
