### ISSUE TITLE
Unable to add file level metadata on geographic raster content/unable to add point geo coverage

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#4823] opened 2022-11-08 21:21 UTC
**Description of the bug**
User unable to add point geographic file level metadata to geographic raster files. Point option greyed out, tif level can't add metadata, is this because it is in an aggregation: is this a feature or a bug? See images:
![Screen Shot 2022-11-08 at 9 47 07 AM](https://user-images.githubusercontent.com/90924476/200677264-dfb69413-bd54-44ff-a642-7f8ac15a37ae.png)
![Screen Shot 2022-11-08 at 9 47 18 AM](https://user-images.githubusercontent.com/90924476/200677326-152b1c01-b78e-4054-b04e-1b02f0e66930.png)

![Screen Shot 2022-11-08 at 9 47 26 AM](https://user-images.githubusercontent.com/90924476/200677343-dfdf5415-0076-41c7-aa70-fcdfb32def1a.png)

Steps to reproduce the bug:
1. Go to https://www.hydroshare.org/resource/a8529ec2281443ebb4b4728d3c5353db/
2. try to add file level geographic coverage in the form of a point

**Expected behavior**
I expected user to be able to add point coverage, but I am unsure if there is a reason for this. I told the user I would investigate whether this was a bug or a feature.

**Comment by ClaraCogswell** [comment] 2022-11-08 21:22
@sblack-usu or @devincowan Does anyone have insight on whether this is a bug or a feature?

**Comment by devincowan** [comment] 2022-11-08 21:27
@ClaraCogswell likely a regression in 1.60 release
I'm checking it out

**Comment by devincowan** [comment] 2022-11-08 21:36
I assumed it was a bug because we had some changes to the file-level coverage in 1.60, but actually, seems like maybe this is a feature:
https://github.com/hydroshare/hydroshare/blob/master/theme/static/js/resourceLandingAjax.js#L1531
Looks like @pkdash was the [last one to edit](https://github.com/hydroshare/hydroshare/pull/3792) this part of HS... Pabitra, do you remember any explanation for this?

**Comment by ClaraCogswell** [comment] 2022-11-08 21:42
I had a feeling it might be a feature associated with the content aggregration type. Just let me know why it is that way and I'll go back and tell the user "you aren't able to add point coverage to geographic rasters because (they inherently represent a non point location ect ect)"

**Comment by devincowan** [comment] 2022-11-08 21:50
here we go, the original issue:
https://github.com/hydroshare/hydroshare/issues/2110

**Comment by ClaraCogswell** [comment] 2022-11-09 15:17
Okay, then to confirm  he will need to add spatial coverage as a box to resolve the message at the top of the page and make the resource public

**Comment by ClaraCogswell** [comment] 2022-11-09 17:31
@dtarb could you confirm or deny?

**Comment by dtarb** [comment] 2022-11-10 05:28
@ClaraCogswell the real problem with the users resource here is that the tif images in the resource are not geographic rasters, they are just plain tif image files.  Here is an image of one of them that I downloaded and viewed in photoshop.

![image](https://user-images.githubusercontent.com/3456833/201006352-8c3adb64-fe5c-4a1f-8aa4-ee5b28fe1aba.png)

Because they are not geographic rasters, it makes no sense to assign them spatial coverage.  The user should remove the aggregation level content type from each of these files by right clicking and selecting remove content type.  This will leave the files as plain files.  If there is a spatial location associated with the data, then it should be added at the resource level.

Now, addressing the question of a point coverage that you and @devincowan have raised, we decided (in 2017) that since a geographic raster covers an area it should only have a box spatial coverage.  At that time this was done for geographic raster resource types.  This functionality transferred through to geographic raster content aggregations.

**Comment by dtarb** [comment] 2022-11-10 05:35
Looking more at the resource, is the user's intent that the point coverage should indicate the location of the NEON site where the sample used in the analysis that produced this image was done.  If this is the case, I think it is awkward to associate a spatial coverage with each image.  It may be better to upload a shapefile with a point at each site with an identifier that can be associated with each image.

**Closed** 2022-11-10 14:58 UTC
Labels: bug
