### ISSUE TITLE
"Edit" message for keywords shows in "view" mode.

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3521] opened 2019-08-14 20:31 UTC
Take a look at just about any public resource to reproduce.  I was able to reproduce this issue on this resource without even being logged in.
https://www.hydroshare.org/resource/5586e9524b114c30a1a29d58f4c98355/

![image](https://user-images.githubusercontent.com/35820390/63053823-e4d8c600-be9f-11e9-92b5-3297ba4b3bd5.png)

**Comment by dtarb** [comment] 2019-08-15 01:28
Duplicate of #3495.  Fixing it will squash two bugs now.  Twice the bang for the buck!

**Comment by Maurier** [comment] 2019-10-14 15:55
This has been addressed and deployed to https://www.hydroshare.org. Closing...

**Closed by Maurier** 2019-10-14 15:55 UTC
Labels: High Priority, Resource Landing Page, bug, in progress
