### ISSUE TITLE
Icons on "Open With" drop down list should match those on the apps themselves

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#1051] opened 2016-03-12 01:18 UTC
For example the raster viewer icon should be used on the drop down list for "open with" raster viewer.

**Comment by shawncrawley** [comment] 2016-07-06 00:07
When a user created a Web App resource, they are able to input an image URL themselves, which is then saved as resource metadata. In the case that this metadata is not specified, the default Web App icon is used. The problem is that this metadata is not required in order to make the resource public. Thus, it is likely that valid web app resources will not have their appropriate icon if the user did not know/notice to specify one. Thus, one way of fixing this issue is to make the icon a required piece of metadata before publicizing the resource.

The only other option that I foresee would require the web scraping of either the app's own page or the tethys apps library page to extract the icon image URL. This is the only other option since there is not a standard name/location for tethys app icons. This option can be implemented since there exist many helpful python libraries for web scraping, but this option will add some slight run-time overhead and be a bit harder to code. What are your thoughts?

**Comment by danames** [comment] 2016-07-06 13:21
I prefer to just show a default icon if the user doesn't supply one, rather
than trying to scrape for one.

**Comment by shawncrawley** [comment] 2016-07-12 22:33
@danames Well in that case, this issue is already resolved. If you are satisfied, you may close it.

**Closed** 2016-07-13 09:16 UTC
