### ISSUE TITLE
REST API for Referenced Time Series Res Type

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1238] opened 2016-06-02 16:58 UTC
Looks like current rest api does not support CRUD operations on RefTS res type yet. 

@alvacouch Please review current code base. We think changes to both sides (REST API and RefTS) are necessary to get them working together. We would like to work closely with you on this. Thanks

**Comment by alvacouch** [comment] 2016-06-15 18:11
As mentioned in the call today, I need much more data to act. 

There are two REST APIs: one inside ref_ts and one outside ref_ts. To which are you referring? Or, are there functions in the exterior one that aren't in the interior one, or vice versa? 

You noted on the call that the REST create call isn't working. Are you referring to the one inside ref_ts?

Please give more details. I am confused as to what to do.

**Comment by alvacouch** [comment] 2016-06-15 18:15
@zhiyuli @pkdash @dtarb Is part of the problem that the science metadata -- handled for non-ref_ts resources by Brian's code -- is not handled by the ref_ts REST interface?

**Comment by alvacouch** [comment] 2016-06-15 18:42
@zhiyuli @pkdash @dtarb I've reviewed the two REST interfaces.
* `ref_ts/urls.py` (branch develop) currently contains only `_internal` calls. 
* the other (exterior) REST contains the "rest" of the REST interface (pun intended). 

Am I looking at the proper branch? 

If so, then the problem is that we have `_internal` REST for `ref_ts` but it doesn't link properly to external REST in `hs_core`?

Am I closer to understanding the problem? 

Am I now understanding the problem properly?

**Comment by zhiyuli** [comment] 2016-06-15 18:49
@alvacouch @pkdash 
I apologize I didnt make it clear on the call.
Currently user is able to create a RefTS resource from the UI by providing: 
1) hydroserver url + site code + variable --> backend makes soap call to get the wml
or
2) a rest url to hydroserver that returns a wml --> backend querys this rest url to get the wml

The frontend and backend are all working. Now we need to expose them as REST APIs. 
I dont know how many rests endpoint have been implemented in hs_core. Maybe there is already a rest endpoint that can create a RefTS res. But all our apps are using the python client (hs_restclient) and looks like there is no way to create a RefTS res using current python client.

Currently we could use the following code to create other res types (generic, raster...)
from hs_restclient import HydroShare, HydroShareAuthBasic
auth = HydroShareAuthBasic(username='myusername', password='mypassword')
hs = HydroShare(auth=auth)
abstract = 'My abstract'
title = 'My resource'
keywords = ('my keyword 1', 'my keyword 2')
rtype = 'GenericResource'
fpath = '/path/to/a/file'
resource_id = hs.createResource(rtype, title, resource_file=fpath, keywords=keywords, abstract=abstract)


I would like to have it allow to pass in a json variable "refts_json", it contains info to create a RefTS res. 

rtype = "RefTimeSeriesResource"
refts_json = {
              "type": "soap", 
              "url": "http://worldwater.byu.edu/interaLctive/gill_lab/services/index.php/cuahsi_1_1.asmx?WSDL"
              "sitecode": "mysitecode",
              "varaiblecode": "myvariable"
             }
resource_id = hs.createResource(rtype, title, resource_file=None, keywords=keywords, abstract=abstract, refts_json)
Then a RefTS res is created on hydroshare with all metadata extracted from the wml

**Comment by zhiyuli** [comment] 2016-06-15 18:52
@alvacouch 
yes, from my understanding we should somehow expose the urls in ref_ts/urls.py as external rest apis, or expose those view functions as external rest apis.

**Comment by alvacouch** [comment] 2016-06-15 19:12
Actually, I suggest something different. 

1. Leave the current REST functions internal. 
2. Wrap them in compliant REST endpoints, e.g., POST /resource/...., GET /resource/{uuid}, PUT /resource/{uuid}, etc. 

Now I understand a lot more about the situation. 
* Brian's calls are all "REST compliant" in the sense that the nouns and verbs are used properly.
* The proper create call for a thing is of the form `POST /noun/{noun data}`.
* The calls in `ref_ts` are `_internal`. These are not required to be 'REST compliant' because the outside world won't see them. But they are not suitable for outside consumption, either. 
* The proper REST endpoint to create a `ref_ts` resource is of the form `POST /resource/....` where the `...` tells what to do for a `ref_ts`.  
* The quandary is that the way Brian codes Science Metadata is to utilize a callback on a per-_file_ basis. This makes no sense if there are no files and doesn't do anything at all. Thus, wrapping the work in ref_ts with Brian's pattern doesn't instantiate science metadata.  
* What we need instead is something that invokes a pre-create callback that embodies all of the work of calling up the WOFS service and harvesting the metadata. The per-file callback won't be called. 
* Or we could do this some other way,  by overriding REST create and embedding the code we need directly into the REST create method.

Am I getting closer?

**Comment by alvacouch** [comment] 2016-06-15 19:19
It's no wonder that the python client can't read a resource.... it is trying GET /resource/.... and we aren't servicing that endpoint for ref_ts.

**Comment by zhiyuli** [comment] 2016-06-15 19:28
@alvacouch I think you already hit the point. Then what is the best way to fix it? I could make changes to refts code once you and @pkdash have a plan.

**Comment by alvacouch** [comment] 2016-06-15 19:36
@zhiyuli @pkdash @dtarb Methinks the best way to start is for me to review the current REST wrapper for `ref_ts` and put in a new hook that instantiates science metadata by using your current `_internal` calls. This hook will take a json string (specification of a service) and will call your `_internal` REST endpoints. 

* At this point, leave the `_internal` calls alone and I will try to use them.  
* If I get to the point where there is more to do than I can just do, I will get back to you with things to do. 

At this point, it seems that the main work is to force Brian's pattern to do an update based upon something other than a file, e.g., a json string. I had better do that myself. 

Note that I have to modify the file update hook anyway, for the "file metadata" project. It has to be able to cope with multiple files(!).  

So there's no time like the present to understand Brian's code.

**Comment by zhiyuli** [comment] 2016-06-15 19:41
@alvacouch The plan sounds good to me, thanks!

**Comment by alvacouch** [comment] 2016-06-15 19:45
@zhiyuli @pkdash @dtarb Actually, a post_create/post_update hook might be the easiest for this. That way, the metadata describing the referenced service will have been stored already. I won't have to pass it an argument. We just read the reference metadata and update the science metadata from it.  

This hook can be used for other analogous tasks as well; anything that requires metadata to be inserted before doing something.

**Comment by pkdash** [comment] 2016-06-15 19:54
@alvacouch @zhiyuli To make things less confusing I won't classify or treat any ```_internal``` endpoints as REST endpoints because they are not designed to be so.

As I understand the issue, the existing REST endpoint for creating a resource needs to be modified so that the additional parameters needed for creating a ref timeseries can be passed when calling this endpoint.

**Comment by pkdash** [comment] 2016-06-15 19:56
Obviously this change to the create resource endpoint would also require appropriate changes to the REST client library.

**Comment by alvacouch** [comment] 2016-06-22 20:00
Actually, note to self: there are five places that need to be modified for any change in the REST API:
1. The API code itself. 
2. The REST Client. 
3. The Wiki page with overview documentation. 
4. The ReadTheDocs documentation on the REST API. 
5. The test suite.

**Comment by pkdash** [comment] 2016-07-01 22:44
Note to self. 

1. Include a new parameter 'extra_data' to resource create REST API endpoint which can be used to pass optional data as json string. 
2. The pre_resource_create signal needs to take an additional parameter 'extra_data'.
3. The ref_ts resource type needs to change its pre_resource_create handler function to be able to use the additional data passed as 'extra_data' and generate the metadata (the code for generating metadata is in a view function which needs to be refactored so that it can be used in multiple places). 
4. This change to the REST endpoint will require change to the rest client createResource().

**Comment by alvacouch** [comment] 2016-07-06 16:02
A suggestion: what I was going to do was to completely populate metadata with no files, and then use the post-create and post-update hooks to call up the REST call and populate the "rest" (pun intended) of the metadata.

**Comment by pkdash** [comment] 2016-07-08 19:39
@zhiyuli Once my PR #1328 gets merged, you should be able to  pass metadata for any of the ref_ts specific metadata elements using the 'metadata' parameter.

**Comment by pkdash** [comment] 2016-10-10 20:59
@zhiyuli can you close this?

**Closed** 2016-11-16 16:12 UTC
Labels: Close Me!, in progress, Reference Resources, REST API
