### ISSUE TITLE
Failed to create a new version for the Model Instance resource type when linked to a specific Model Program resource

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#1140] opened 2016-04-21 01:23 UTC
If a new Model Instance resource type is created with all metadata except the "ExecutedBy" metadata elements which links the Model Instance resource to a specific Model Program resource, the user would be able to create a new version of the resource. Once the user links the Model Instance with a Model Program by selecting the Model Program from the ExecutedBy drop list on the resource specific landing page and then try to create a new version of the Model Instance resource, the user will get the failed error (see below). 

![image](https://cloud.githubusercontent.com/assets/5543781/14695056/569e22b8-073c-11e6-9f63-c3194b02a8a5.png)

The same for the SWAT Model Instance resource type

**Comment by dtarb** [comment] 2016-05-01 16:42
@mohamedmorsy please check if this is still an issue and if it is deploy blocking (i.e. not already a problem in www).  If it is not deploy blocking please set to a later milestone.

**Comment by mohamedmorsy** [comment] 2016-05-02 17:32
@dtarb the issue still exists, and I can reproduce it on www (see below):

![image](https://cloud.githubusercontent.com/assets/5543781/14961888/070f2558-1051-11e6-8d77-22e5a00bf445.png)

**Comment by hyi** [comment] 2016-09-13 18:12
@mohamedmorsy This problem is caused by your model instance metadata ExecutedBy implementation. Specifically, in the create classmethod here: https://github.com/hydroshare/hydroshare/blob/develop/hs_modelinstance/models.py#L61, ```shortid = kwargs['model_name']``` actually gets model program name rather than short_id, so the following statement ```obj = ModelProgramResource.objects.filter(short_id=shortid).first()``` returns None, which results in the error from the subsequent statement ```title = obj.title```. When creating a new version of a resource, all resource metadata is copied to the new versioned resource by calling create method of each metadata element, in this case, model instance resource ExecutedBy metadata only stored model program name, rather than short_id, and the create method assumes it is short_id, hence the error. When adding a model program to ExecutedBy metadata, your form retrieves short_id from model program name, then pass short_id into kwargs parameter of this create method, hence it passes without issues, but this conversion cannot be done when creating a new version of a resource, or at least is convoluted and inconsistent even if I found a way to do this conversion, since new version metadata replication is done in a uniform way for all resources without special handling. So my suggestion is for you to change ExecutedBy class to add short_id or replace model_name with model_shortid or something so short_id will be included when creating the model program foreign key reference. I am reassigning this PR to you since the fix is specific to ModelInstance resource ExecutedBy class create() method.

**Comment by pkdash** [comment] 2016-10-10 21:26
@mohamedmorsy Should this be closed?

**Comment by hyi** [comment] 2016-10-10 21:28
@mohamedmorsy This is still an issue. For details, see my comments above that pinpointed the line in your code that causes this issue.

**Comment by Castronova** [comment] 2016-10-11 18:42
@mohamedmorsy can you check that this has been resolved by running branch **1485-executed-by-unspecified-fails** locally?

**Comment by mohamedmorsy** [comment] 2016-10-11 18:53
@Castronova I am doing this now

**Comment by mohamedmorsy** [comment] 2016-10-11 19:13
@Castronova  I got the following error with my first attempt to select a model program and click on the save button (in the create method):

![image](https://cloud.githubusercontent.com/assets/5543781/19284651/d1272456-8fc4-11e6-8435-de28e632d378.png)

Also I see that under the ExecutedBy class you added "null=True" for the "model_name" element. Does this require to generate new migration file?

**Comment by Castronova** [comment] 2016-10-12 15:20
@mohamedmorsy I reverted the `model_name` back to `null=False`.  I also updated the `create` method to handle foreign key creation (via form submission) and model instance versioning separately.  Can you see if this fixes the issue?

**Comment by Castronova** [comment] 2020-12-10 20:02
No longer relevant

**Closed by Castronova** 2020-12-10 20:02 UTC
Labels: Medium Priority, Resource Model, bug, design phase needed
