### ISSUE TITLE
Resource copy/new version not copying resource specific metadata for Timeseries resource

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1827] opened 2017-02-03 20:13 UTC
Resource specific metadata doesn't get copied when creating a copy or a new version of a timeseries resource that has a CSV file.

**Comment by pkdash** [comment] 2017-02-03 20:15
@hyi Would you look into this issue?

**Comment by hyi** [comment] 2017-02-03 20:24
@pkdash Have you tested to see whether the same issue happens also when you create a new version of a time series resource?

**Comment by pkdash** [comment] 2017-02-03 20:28
@hyi Yeah it is the same issue with creation of a new version.

**Comment by hyi** [comment] 2017-02-07 19:20
@pkdash I cannot find a time series with csv file on www, so I cannot reproduce this issue. Can you create a time series resource on www and point me to it so that I can reproduce this issue or directly send me a csv file for me to create a time series resource trying to reproduce this issue?

**Comment by horsburgh** [comment] 2017-02-07 19:23
@hyi - I just gave you owner access to this resource:

https://www.hydroshare.org/resource/5d952304c16d4955bdc36acf4e83d56e/

I believe it has a CSV file.

**Comment by hyi** [comment] 2017-02-07 19:46
@horsburgh Thanks! I tested that resource and have not run into issues reported here with resource copying - specific resource type metadata are indeed copied over based on my testing. Can you do a quick test to see if you observe any issue with resource copy of this specific resource? Also, I tried to upload the single csv file in my local development environment and I don't get all specific metadata elements as shown for your resource on www. When I download the resource bag, I got a prompt that metadata is out of sync. What extra steps are required beyond uploading the single csv file in order to extract all specific metadata? @pkdash I see you shared a copied time series resource with me on www, but I don't have access to the original time series resource to test against. If you can give me access to the original test resource that can reproduce this issue, I can take a look. Let me know if there are extra steps required beyond just simply uploading the csv file to create the time series resource.

**Comment by pkdash** [comment] 2017-02-07 20:12
@hyi This is the original timeseries resource (https://www.hydroshare.org/resource/fa7c6187144943168c5c751937512e4f/) that I have given you edit permission. 

When you upload a CSV file no resource specific metadata is created. You have to enter resource specific metadata.

**Comment by hyi** [comment] 2017-02-07 21:38
@pkdash I can reproduce the issue and debugged and it looks like https://github.com/hydroshare/hydroshare/blob/develop/hs_app_timeseries/models.py#L146 _create_site_related_cv_terms() does not create cv terms as expected. The pass in parameters, element and data_dict, all look correct, but cv terms may not get created correctly? The Site metadata elements appear to be all copied over and created correctly by https://github.com/hydroshare/hydroshare/blob/develop/hs_app_timeseries/models.py#L142 call. I don't know time series metadata implementation enough to quickly diagnose what is the reason the metadata elements don't show up for the new copied resource even if the debug shows the elements are copied over, at least before the call to  _create_site_related_cv_terms(element=element, data_dict=kwargs). I think at this point you are much more equipped to further debug and diagnose the issue than me since based on my debugging, it appears it is an time series specific implementation issue rather than a resource copy issue. Can you debug further to see if you can fix the issue?

**Comment by pkdash** [comment] 2017-02-07 22:11
@hyi I will look at this. Thanks for the initial debugging.

**Comment by pkdash** [comment] 2017-02-07 23:52
@hyi I have almost fixed the bug. Will be creating a PR soon.

**Comment by hyi** [comment] 2017-02-21 21:06
@pkdash The fix to this issue should have made into 1.9.5 release, right? Can you test it out and close it if it works now?

**Comment by pkdash** [comment] 2017-02-21 23:47
@hyi On www it is working only partially. In the edit mode, the copied resource doesn't populate the CV terms. I thought I had fixed that. I guess I have to lookin into it again.

**Comment by pkdash** [comment] 2017-02-21 23:55
@hyi It is working on dev though. May be it didn't make to 1.9.5.

**Comment by pkdash** [comment] 2017-03-16 03:23
It has been addressed. Closing.

**Closed** 2017-03-16 18:08 UTC
Labels: in progress
