### ISSUE TITLE
[NWM] Snow-Cover Forecast Chart Units

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2417] opened 2017-11-10 17:23 UTC
The units for the snow-cover variable is fraction. Fraction is an ambiguous term and we do not know what the numerator or denominator are for this variable.

![image](https://user-images.githubusercontent.com/22031618/32670502-f5d1a342-c611-11e7-96dc-689b04c9fba9.png)

**Comment by Castronova** [comment] 2017-11-21 14:39
duplicate of https://github.com/hydroshare/hydroshare/issues/2419

**Closed** 2017-11-21 16:44 UTC
Labels: Apps, enhancement, Medium Priority
