### ISSUE TITLE
Without resource logos, the Discover table can look messy

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3268] opened 2019-03-24 18:00 UTC
Some of the resources don't have resource type logos, which makes the table look somewhat messy.

[009.zip](https://github.com/hydroshare/hydroshare/files/3000661/009.zip)

**Comment by Maurier** [comment] 2019-03-25 01:47
I believe this a duplicate of https://github.com/hydroshare/hydroshare/issues/3259

**Comment by pkdash** [comment] 2019-03-25 13:54
PR #3260  should also fix this issue.

**Comment by dtarb** [comment] 2019-03-27 12:44
Fixed on 1.21 RC

**Closed by dtarb** 2019-03-27 12:44 UTC
Labels: Low Priority
