### ISSUE TITLE
Make Extended Metadata clickable when value is a URL

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#1895] opened 2017-02-23 15:33 UTC
Request to make the value in HydroShare resource Extended Metadata directly clickable in the UI when that value is a URL:

![hs_extmeta_url](https://cloud.githubusercontent.com/assets/2846017/23265717/7c6feb6a-f9b3-11e6-8dda-254c436647a8.png)

**Comment by hyi** [comment] 2017-02-23 15:56
@rayi113 @mauriel133 I can easily add this enhancement with one line change. I am currently rebuilding my development environment with latest develop, but should be able to create a PR for this shortly.

**Comment by hyi** [comment] 2017-02-23 16:52
@aphelionz While working on this issue, I found "Add new entry...``` popup is not displayed any more so I cannot really test whether my fix works or not. This is caused by your recent addition of content security since I can see the error on refusing to execute inline event handler because it violates the following content security plicy directive... triggered by this line: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/templates/pages/genericresource.html#L1058 I don't see any provided hash though to add to settings.py. So can you advise on where to find the provided hash and what needs to be done to get this fixed?

**Comment by aphelionz** [comment] 2017-02-23 17:40
@hyi Ah, in that case we need to refactor to not use the inline event handler. Assign this ticket to me and I will take care of it.

**Comment by hyi** [comment] 2017-02-23 17:45
@aphelionz Sounds good, just reassigned this ticket to you. There may be other cases of inline event handlers being used, looping in @mauriel133 and @pkdash to keep them informed as well.

**Comment by hyi** [comment] 2017-02-23 17:47
@aphelionz BTW, this becomes a high priority item due to its regression nature.

**Comment by pkdash** [comment] 2017-02-23 18:00
All most all metadata related forms have the inline even handler. Some in the html templates others (in particular resource/file type specific metadata) are in dynamically generated form classes.

**Comment by pkdash** [comment] 2017-03-23 15:14
@aphelionz Was wondering if @mauriel133 should work on this.

**Comment by dtarb** [comment] 2017-05-10 02:48
Great!

**Closed by dtarb** 2017-05-10 02:48 UTC
Labels: Close Me!, enhancement, High Priority, in progress, pull request merged
