### ISSUE TITLE
Failing when trying to download a resource's Zipped BagIt Archive

### ISSUE THREAD

**Issue by shawncrawley** [hydroshare/hydroshare#1156] opened 2016-04-21 21:59 UTC
Here is the error I'm receiving:
```bash
Received status 500 Internal Server Error when accessing https://www.hydroshare.org/hsapi/resource/b7822782896143ca8712395f6814c44b/ with method GET and params None.
```
This was discovered when trying to retrieve the Zipped BagIt contents through the REST API, however the "Download" link itself on the resource landing page yields the same error. The resource in question is Public and Shareable. See it here: https://www.hydroshare.org/resource/b7822782896143ca8712395f6814c44b.

**Comment by shawncrawley** [comment] 2016-04-21 22:04
@mjstealey @dtarb @hyi

**Comment by dtarb** [comment] 2016-04-22 10:25
This is due to the bug #1092.

**Comment by hyi** [comment] 2016-05-16 14:20
I am copying comments from this issue to issue [#1092] to consolidate issues since they are duplicate of each other, and closing this one.

**Closed by hyi** 2016-05-16 14:20 UTC
Labels: bug
