### ISSUE TITLE
Add capability to edit and delete comments

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1369] opened 2016-08-01 14:51 UTC
Add capability to delete comments and replies on a resource.  Comments should be deletable by the original commentor and the owner of the resource.  If a comment is deleted, any replies associated with that comment get deleted too.  A user deleting a comment that also deletes replies should be warned that this is the going to happen.  +1 associated with comments or replies deleted, also get deleted.

We could also consider allowing editing of comments, but I am a bit conflicted about whether to allow this as it edits the conversation history.  If someone makes a mistake, they should just delete their comment and write it again, or write a new clarifying comment and reply.

**Comment by hyi** [comment] 2016-08-01 15:00
This is kind of a duplicate of #1213, but will keep both open and linked for now. Assigning it to me for now, but may not be able to work on this until other higher priority items get resolved first.

**Comment by cuahsimarko** [comment] 2019-04-19 19:23
spoke with Hong CUAHSI will take this on

**Comment by cuahsimarko** [comment] 2019-04-23 15:47
It seems that we need the following functionality

    The commentor can delete their own comment
    If an owner or anyone else does not like that comment they can not delete it but they can comment back

**Comment by cuahsimarko** [comment] 2019-04-23 15:49
Related Issue: Report Inappropriate Comments https://github.com/hydroshare/hydroshare/issues/1213

**Closed** 2020-05-11 18:12 UTC
Labels: High Priority, design phase needed
