### ISSUE TITLE
Login shown on all tabs but Help and About.

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3271] opened 2019-03-24 18:02 UTC
The login disappears on the Help and About tabs.

[012.zip](https://github.com/hydroshare/hydroshare/files/3000664/012.zip)

**Comment by engineSound** [comment] 2019-03-29 00:18
The help and About are from a different domain. @dtarb Is this a designated behavior?  Launching it into a separate tab could make the hydroshare more like within itself.  @dtarb @Lizabrazil @martinseul @Maurier Please chime in.

**Comment by dtarb** [comment] 2019-03-29 03:00
The different domain for help and about came about as a historical accident of using a separate server and plain Mezzanine CMS for this content.  It was easier to do separately than in HydroShare, but it was styled to look the same.  It does not worry me that much that there is no login button there and I think there are many more important problems on the site to fix, before I would put effort on this, like Discover, Search all of HydroShare, working quotas, DOI registration etc.

**Comment by engineSound** [comment] 2019-03-29 11:18
@dtarb should I close it?

**Comment by dtarb** [comment] 2019-03-29 12:37
If you ask me, yes.  I would not spend my money on this.  However I want to delegate, empower and trust you (@martinseul @engineSound @Lizabrazil) with the responsibility for deciding on relatively small UX questions like this.  If you have resources (time, which is money) to change and test this, that is higher priority than all the other things that need to be done, or can do this very quickly and simply, or feel that it is a real important issue to fix for UX, then use the resources you have to fix this.  It was pointed out by @hydrocheck and we do not want to ignore his advice.

**Comment by Castronova** [comment] 2021-02-01 16:31
@martinseul is this something that you want to implement. If not, please close.

**Comment by dtarb** [comment] 2021-04-20 17:37
This is by design

**Closed by dtarb** 2021-04-20 17:37 UTC
Labels: Help and Training, design phase needed, enhancement
