### ISSUE TITLE
Improve Resource Landing page formatting of versions

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3783] opened 2020-03-07 17:05 UTC
I think that additional line spacing is needed below the version indicator on the resource landing page
![image](https://user-images.githubusercontent.com/3456833/76147601-29ee6080-605b-11ea-8238-fda8bb3774af.png)

**Comment by pkdash** [comment] 2020-08-08 20:50
@dtarb I can't reproduce this issue.  It seems there is already enough spacing as shown below:

![image](https://user-images.githubusercontent.com/2523434/89719518-34f54600-d997-11ea-8588-10366aedac99.png)

**Comment by dtarb** [comment] 2020-08-08 21:51
I just looked at it more carefully and the insufficient space seems to only occur when not logged in (and thus viewing a public resource).  See https://www.hydroshare.org/resource/82a2ba1a767742cca39d4959f10b2a9e/

**Comment by Castronova** [comment] 2021-02-26 19:57
Closing as resolved.

**Closed by Castronova** 2021-02-26 19:57 UTC
Labels: Resource Landing Page
