### ISSUE TITLE
{% block extra_js %} and {% block extra_css %} scripts are being generated (and thus executed) twice

### ISSUE THREAD

**Issue by shawncrawley** [hydroshare/hydroshare#869] opened 2016-01-07 20:19 UTC
It appears that any JavaScript code that is added to the `extra_js` django html block is getting generated twice somehow, and thus is executing twice. This will not only slow down rendering time, but it also created a problem for me when adding code to the `extra_js` of toolresource.html that dynamically creates a new html element (since two elements are being created, instead of just the one expected).

Though this issue was discovered on my localhost instance, it is happening on www. To see what I'm talking about, open up the landing page for any resource. Open up the DevTools window and click on the Sources tab. Find the file called (index) that appeaers under the directory named "resource/[res_id]". Do a 'Ctrl+f' to find all of the instances of ".ready(". It will be observed that the JavaScript in the extra_js block from both the specific_resource_type.html (if applicable) and the genericresource.html pages is repeated.

**Comment by shawncrawley** [comment] 2016-01-07 20:20
@pkdash @mauriel133 Do either of you have any idea why this is happening and feel confident addressing it?

**Comment by shawncrawley** [comment] 2016-01-07 20:30
I did notice that it only happens with the JavaScript actually hard-coded directly in the .html file. If an external script is added to the `extra_js' block, then it is not generated twice. So one possible fix is creating a `.js` script for genericresource.html and requiring the same for all additional resource types (in the case that they need it).

**Comment by shawncrawley** [comment] 2016-01-22 21:28
@ironfroggy Do you have any idea why this is happening? @zhiyuli Drew said the same problem is giving him issues now, too.

**Comment by mauriel133** [comment] 2016-01-22 21:34
I think it's because we have 
> {% block extra_js %}{% endblock %}

in our base.html

For example, when I'm testing ajax calls they fire twice and the html is included twice in the source code passed to the client.

If I remove that empty block from base.html then it will only be included once and everything works as intended.

**Comment by shawncrawley** [comment] 2016-01-22 21:35
@mauriel133 Would you mind taking care of that?

**Comment by mauriel133** [comment] 2016-01-22 21:36
I need confirmation that this is actually the case and that it won't affect other uses. If that is the case I can take care of it.

**Comment by hyi** [comment] 2016-01-22 22:20
@mauriel133 I'd suggest to remove the empty block from base.html if everything works as intended according to your testing. We can always patch things up if things break afterwards.

**Comment by mauriel133** [comment] 2016-01-23 17:55
Check if the problem is solved now. You may close this issue if it is.

**Comment by ironfroggy** [comment] 2016-01-24 16:29
Removing that block from `base.html` is not the right solution. That's exactly where its supposed to be. You need the empty block in the base template so that extending templates can override it and insert your JS there.

**Comment by shawncrawley** [comment] 2016-01-25 16:11
@mauriel133 Yeah, @ironfroggy is right. And I actually found what the problem is. The base.html template defines the extra_js and extra_css blocks as un-nested blocks that stand alone. However, in the genericresource.html file, the extra_css and extra_js blocks were nested within the body block. Thus, their content was being duplicated (once where they were nested within the head block, and once outside of it where their django blocks actually appear in the base.html). Does that make sense? I tested moving the extra_css and extra_js blocks out of the head block and it worked. If you could do the same on branch #869 and then re-commit and push, it should be good.

**Comment by hyi** [comment] 2016-01-25 16:19
@mauriel133 @shawncrawley @ironfroggy Yeah, I agree, keeping the empty extra_js block in base.html but moving the extra_js and extra_css blocks outside the head block in genericresource.html is the right solution to resolve this issue.

**Comment by mauriel133** [comment] 2016-02-10 00:35
@shawncrawley, the fix has been merged now. Please verify and close if everything works.

**Closed** 2016-02-10 17:59 UTC
Labels: Close Me!, pull request merged
