### ISSUE TITLE
Error creating resource with non-ascii characters and accents

### ISSUE THREAD

**Issue by jirikadlec2** [hydroshare/hydroshare#248] opened 2015-03-19 02:23 UTC
I tried to create a "Referenced Time Series" resource. I entered the resource title: "Temperature at Žatec". Immediately I get an error: 

'ascii' codec can't encode character u'\u017d' in position 47: ordinal not in range(128)

![image](https://cloud.githubusercontent.com/assets/4144642/6723327/f42a8038-cdab-11e4-9b50-36c7ef3dd495.png)

![image](https://cloud.githubusercontent.com/assets/4144642/6723344/3fbc28bc-cdac-11e4-9377-0fa09538cb49.png)

**Comment by dtarb** [comment] 2015-04-01 15:36
Same as #267

**Comment by dtarb** [comment] 2015-04-20 14:19
Closing this.  Will resolve this with #267

**Comment by jsadler2** [comment] 2015-04-20 20:11
This issue is separate from #267 which was dealt with locally in the ref_ts app. This issue deals with the more global problem, accented characters in the title. The solution to #267 does not directly apply to this one.

**Comment by dtarb** [comment] 2015-04-20 20:32
@jsadler2 or @danames can you test if this is then still an issue with other resource type titles.  Also check with @hyi.  There was work to have the storage of all fields unicode and to remove generation of the optional bagit file that triggered this issue.

**Comment by hyi** [comment] 2015-04-20 20:47
Yes, I did run into this issue initially and fixed it in my new access control branch by setting up database with unicode UTF-8 and remove title field from bag-info.txt file. So you may test this to make sure this issue is fixed for all resource types once my new branch is deployed to dev.

**Comment by jsadler2** [comment] 2015-04-20 21:10
Okay. Will do. Thanks Hong.

**Comment by ironfroggy** [comment] 2015-04-21 11:40
I'd like to note that reading the bagit library it clearly is expected to support UTF-8 for those txt files it generates, so it should be possible to resolve this without changing the data you create.

**Comment by hyi** [comment] 2015-04-21 13:20
I believe the bagit problem was caused by our use of earlier version of bagit library which probably did not support UTF-8 fully, hence the error when saving a title with special characters into bag-info.txt. Since we are planning to revamp bagit workflow to have bagit done on iRODS side that does not create optional bag-info.txt (we have decided we don't need bag-info.txt), so it should be fine just to take title off from bag-info.txt for now rather than upgrading our bagit library to newer version to resolve this specific issue.

**Comment by dtarb** [comment] 2015-07-08 03:28
@jsadler2 is this still an issue.  If not, please close

**Comment by jsadler2** [comment] 2015-07-08 15:30
Resolved.

**Closed by jsadler2** 2015-07-08 15:30 UTC
Labels: Clean up
