### ISSUE TITLE
[RC-1.21] Unable to search by Author or Subject in My Resources page

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#3274] opened 2019-03-24 23:57 UTC
@sblack-usu, @pkdash  
I was able to narrow down this error to a problem with a context variable not reaching the frontend:
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/templates/pages/my-resources.html#L269

However, this only happens in our current deployment on beta. I tried to reproduce this error locally with no success. We might need to investigate directly in the VM in order to find out what's going on.

Testing locally:
![image](https://user-images.githubusercontent.com/2448568/54888005-aa25b100-4e5e-11e9-94e2-15306063099d.png)

Testing beta deployment:
![image](https://user-images.githubusercontent.com/2448568/54888047-2e783400-4e5f-11e9-82f6-b955faff30f0.png)

Since this data doesn't make it to the template in beta, the DataTables' scripts can't use the information to filter correctly. The same happens with the Subjects column.

**Comment by Maurier** [comment] 2019-03-26 23:41
@pkdash, I was able to reproduce this issue locally today. Could you pull the most recent changes and try again? We might be able to debug and find the problem now.

**Comment by pkdash** [comment] 2019-03-27 01:17
@Maurier I am using the RC-1.21 now locally. Not able to reproduce this issue locally.

**Comment by dtarb** [comment] 2019-03-27 13:05
This is still a problem on the new 1.21 beta RC just deployed.  If I create a resource with a unique keyword "kw123" on www in MyResources if I search on the MyResources search bar for kw123, I find the resource, but on beta I do not.

Also, if I add another author and on www search on that auther in the search bar, I find the resource, but do not on beta.

**Comment by pkdash** [comment] 2019-03-28 01:54
@dtarb and @Maurier I have now created a PR #3282 as a hotfix for this issue.

**Comment by martinseul** [comment] 2019-03-28 20:27
the pr has been merged into the RC and deployed to beta., @Maurier @dtarb @pkdash, We are planning to release 1.21 on Tuesday

**Comment by pkdash** [comment] 2019-03-28 21:13
Filtering on authors and keywords seem to work now on beta.

**Comment by pkdash** [comment] 2019-03-28 21:17
Seems the page loading did not suffer much due to not prefetching the metadata.

**Comment by pkdash** [comment] 2019-04-03 19:47
@Maurier I think this can be closed.

**Closed** 2019-04-03 20:04 UTC
Labels: bug
