### ISSUE TITLE
Broken resource

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2529] opened 2017-12-15 03:41 UTC
The following resource (that happens to contain the AGU presentation I gave on 12/11/17) is broken.  https://www.hydroshare.org/resource/b56e4e9955cc4fef9ecfeef2aa736502/.  

You can find this using discover searching for AGU2017 the pick the one with the title "The HydroShare Collaborative Repository ..."  The message is just "Error - Sorry an error occurred".  If I add debug to the URL it reports no problems.

The particular contents of this resource could be reconstructed if necessary, but the cause for this error should be determined and corrected if possible.  The file content is a single powerpoint file.

**Comment by rayi113** [comment] 2017-12-15 14:18
@dtarb I am able to reproduce this issue on 2 different PC with different browsers on each PC.  The issue for me happens consistently when I'm logged out of HydroShare, otherwise the resource resolves correctly.

**Comment by aphelionz** [comment] 2017-12-16 16:43
@rayi113 @dtarb confirmed.

This may be related to the work @zhiyuli did with the open with button. Drew, can you investigate? It looks a lot like the issue we caught in beta testing, but just localized to this resource.

**Comment by aphelionz** [comment] 2017-12-16 16:50
Yep, looks like it's the tools_resource work. @dtarb Can you work around by using a logged in acct or does this need to be a hotfix? If so, by when?

`
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 125, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/mezzanine/pages/middleware.py", line 107, in process_view
    processor_response = processor(request, page)
  File "/hydroshare/hs_composite_resource/page_processors.py", line 51, in landing_page
    extended_metadata_layout=None, request=request)
  File "/hydroshare/hs_core/page_processors.py", line 79, in get_page_context
    relevant_tools = resource_level_tool_urls(landing_page_res_obj, request)
  File "/hydroshare/hs_tools_resource/app_launch_helper.py", line 32, in resource_level_tool_urls
    is_open_with_app = _check_open_with_app(tool_res_obj, request_obj)
  File "/hydroshare/hs_tools_resource/app_launch_helper.py", line 64, in _check_open_with_app
    return _check_webapp_in_user_open_with_list(tool_res_obj, request_obj) or \
  File "/hydroshare/hs_tools_resource/app_launch_helper.py", line 71, in _check_webapp_in_user_open_with_list
    return tool_res_obj.rlabels.is_open_with_app(user_obj)
  File "/hydroshare/hs_labels/models.py", line 524, in is_open_with_app
    return self.is_flagged(this_user, FlagCodes.OPEN_WITH_APP)
  File "/hydroshare/hs_labels/models.py", line 500, in is_flagged
    assert isinstance(this_user, User)
AssertionError
`

**Comment by aphelionz** [comment] 2017-12-16 16:57
Hmm actually it looks like no resources are available anymore to outside users. @zhiyuli can you confirm your hotfix even made it to www? This is really strange.

**Comment by aphelionz** [comment] 2017-12-16 17:09
@zhiyuli @dtarb Good news and bad news.

This is now fixed on www.hydroshare.org. However there is still significant skew with what's on the server vs what's in the code base. Something  got corrupted during the deploys and we need to dig in to find out what it was. 

This code is definitely in the 1.14.2 tag: https://github.com/hydroshare/hydroshare/blob/1.14.2/hs_tools_resource/app_launch_helper.py#L68 

I will be investigating this starting Monday. Please let me know if other issues arise.

**Closed by aphelionz** 2017-12-16 17:09 UTC
Labels: bug

**Comment by dtarb** [comment] 2017-12-17 14:56
What was actually done to fix this?

**Comment by aphelionz** [comment] 2017-12-17 19:39
@dtarb I cheated again and updated the code on production so that drew's change was implemented. I don't plan on making this a habit and I'm still really concerned about the disparity between what's on github and what ended up on master after a proper deployment where the slate was wiped clean.

What we'll need to do soon is essentially re-deploy 1.14.2 from scratch and see where we're at. I was in emergency mode because of AGU all week, and with the holiday coming I'm sure we can find a night to do it and make sure everything is as it should be.

Again, we obviously dont want to make this routine but I opted to get things fixed ASAP rather than to do a full time-consuming deploy.

**Comment by dtarb** [comment] 2017-12-17 20:37
@aphelionz we have multiple staging platforms (beta, playground etc).  Rather than wait for a quiet night, I suggest that you deploy exactly what 1.14.2 should be on beta, and then put it through thorough testing that includes all the tests we know about.  Have we run Tony's test all download script on our current www deploy.  We should also use code comparison tools to compare the source code base between www and beta with exact 1.14.2 to figure this out.
