### ISSUE TITLE
Make Citation Editable

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#1032] opened 2016-03-07 16:03 UTC
The citation field is not editable. This should be changed to editable because the auto-generated citation is not always correct. i.e. Drew helped Lan create the SWATShare Web App and now he is listed as the first author of the citation for the SWATShare Web App and the citation is clunky looking and it would be nice to be able to clean it up manually.

**Comment by horsburgh** [comment] 2016-03-07 16:20
The opposing argument is - when I publish a paper, I don't get to edit the citation information.  It is what it is.  It's up to me to provide the correct authorship information. What is to stop someone from editing the citation and removing HydroShare as the publisher? Removing the URL or the identifier? The current citation uses DataCite specifications for formatting the citation, so blame DataCite if it's klunky. 

If it's just the order of authorship - Drew and Lan should just edit the metadata so the authors and contributors are listed correctly.

I do agree though that the citation is not always correct.  Another good example is where an organization is the author instead of a user (the first words of the organization name are changed to initials e.g., U.S.G. Survey or A.C. Engineers). We may need a little more flexibility in how the citation is constructed (e.g., some potential options for alternative inputs and citation formats), but I wouldn't advocate for users being able to just do free-form edits on the citation.

**Comment by danames** [comment] 2016-03-07 16:38
OK I've cleaned up the citation by adding/removing/reorering authors but still have a problem that there is no space between the author first and last names: 

![image](https://cloud.githubusercontent.com/assets/3472628/13575889/15b10302-e459-11e5-9003-16262dad6e68.png)

**Comment by horsburgh** [comment] 2016-03-07 16:40
That is a bug. @mauriel133 - Can you fix the space between author names quickly?

**Comment by danames** [comment] 2016-03-07 16:51
How about automatically adding the "Last accessed March 7, 2016." at the end of the citation (with the current date...)?

**Comment by mauriel133** [comment] 2016-08-05 17:44
Looks like the spacing has been fixed.

![image](https://cloud.githubusercontent.com/assets/2448568/17445346/b8d5a348-5b01-11e6-9680-0f04c76bde44.png)

Is there anything else I could change?

**Comment by horsburgh** [comment] 2016-08-05 23:07
@mauriel133 - I think the fix to the spacing between author names should address this.

@danames - adding "Last accessed" and then a date to the citation would say to me that we expect resources in HydroShare to be fleeting and that they might disappear at any time. I don't think that's the message we want to convey.  What do you think?

**Comment by dtarb** [comment] 2016-08-06 13:18
See [owl.english.purdue.edu/owl/resource/747/08/](https://owl.english.purdue.edu/owl/resource/747/08/).  Accessed 8/6/16.  Having the date a web resource is accessed seems to be part of standard citations for web resources.  However I would go with just the word "Accessed" rather than "Last Accessed".  This may alleviate a bit the fleeting message @horsburgh is concerned about.

Also note that MLA advocates not having http or https in citations.  This would address #1374 by sidestepping.

**Comment by horsburgh** [comment] 2016-08-06 14:41
@dtarb - we designed the citation using the DataCite standard. So modifying it as suggested might deviate from an accepted standard. I would like to promote a culture where high quality data products are encouraged and promoted as permanent research products. Adding an access date just says to me that this is a random web resource that could disappear at any point so I need to tell people when I last accessed it in case it does. We don't do this when we cite a journal article so if we are serious about data publication and permanent resources we should stop promoting this practice. 

That said - I think we should probably take another look at the latest DataCite standard (which may allow for an access date) and use a standard that was designed for published datasets.

**Comment by dtarb** [comment] 2016-08-07 12:50
@horsburgh - please do review the DataCite standard.  I am OK not having accessed date in our how to cite box if it is consistent with that standard.  I was merely noting that accessed date is part of other standards, and since it is part of other standards, I do not interpret it as a statement that the resource is fleeting.

**Comment by horsburgh** [comment] 2016-08-09 16:09
@dtarb - short story - the **best** way to do citations might be as follows:.  

- For unpublished resources:  follow the preferred DataCite format, but add the access date (because there is no guarantee that the resource will persist or ever be published)
- For formally published resources:  follow the preferred DataCite format without the access date (because there should be a reasonable expectation that a formally published resource will persist forever)

Longer story - We still also need to resolve the way organizations listed as authors show up in the citation.  Might want to put this one in a separate issue.

Here is the important information from the latest DataCite metadata kernel, which you can access at:

https://schema.labs.datacite.org/meta/kernel-4.0/doc/DataCite-MetadataKernel_v4.0.pdf 

From page 8:

> "...DataCite encourages rather than requires a particular citation format."
> 
> "...the following is the preferred format for rendering a DataCite citation for human
> readers using the first five properties of the schema:"
> 
> Creator (PublicationYear): Title. Publisher. Identifier

> "It may also be desirable to include information from two optional properties, Version and
> ResourceType (as appropriate). If so, the preferred form is as follows:"
>   
> Creator (PublicationYear): Title. Version. Publisher. ResourceType. Identifier
> 

DataCite also includes a note regarding the citation of dynamic datasets (e.g., datasets that are continuously or rapidly updated):

> "For datasets that are continuously and rapidly updated, there are special challenges both in citation and preservation. For citation, three approaches are possible:
> a) Cite a specific slice (the set of updates to the dataset made during a particular period of time or to a particular area of the dataset);
> b) Cite a specific snap‐shot (a copy of the entire dataset made at a specific time);
> c) Cite the continuously updated dataset, but add an Access Date and Time to the citation."
> 
> "Note that a “slice” and “snap‐shot” are versions of the dataset and require unique identifiers. The third option is controversial, because it necessarily means that following the citation does not result in observation of the resource as cited."

So, it is allowable to add an Access Date/Time to the citation. However, I would only do this in cases where resources are rapidly changing (not sure we have any yet) or where the content might possibly disappear (e.g., in the case of a referenced resource or an unpublished resource).  Doing an access date with a referenced resource is problematic because just tacking the current system date onto the citation doesn't mean that the content that the referenced resource points at actually still exists because it isn't in HydroShare.

**Comment by dtarb** [comment] 2016-08-09 18:52
There are already two issues #855 and #1360 that address the way organizations are presented in the citation.  I am OK either way on access date.

**Comment by horsburgh** [comment] 2016-08-09 19:56
@dtarb - in the interest of spending time on the issues that we really need to fix, let's let this one go and fix the issues with organizations in the citation.  Closing for now.

**Closed by horsburgh** 2016-08-09 19:56 UTC
