### ISSUE TITLE
Failed to COPY a generic resource

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2540] opened 2017-12-29 17:56 UTC
Got an error when trying to copy this public generic resource:
https://www.hydroshare.org/resource/2fdadb064d6a4d2e925fd9bac3b71a56/

![image](https://user-images.githubusercontent.com/10070599/34443805-d3f55fd4-ec86-11e7-9d40-054f2ba37a50.png)

**Comment by aphelionz** [comment] 2018-01-04 16:11
In my testing this seems localized to this one resource. Downgrading to medium priority.

**Comment by aphelionz** [comment] 2018-01-04 16:47
Furthermore, I created this locally and I am able to copy it. https://dev-hs-2.cuahsi.org/resource/b2de506c60e54b02a18f6bacc411b122/

@zhiyuli is the tar.gz file in iRODS or just HydroShare

**Comment by aphelionz** [comment] 2018-01-04 17:09
This appears to be the line that is throwing the error:

```
[04/Jan/2018 17:05:30] ERROR [hs_tools_resource.utils:27] [WebApp] 'None' cannot be parsed by term_dict {'HS_RES_TYPE': u'GenericResource', 'HS_USR_NAME': u'admin', 'HS_RES_ID': u'2fdadb064d6a4d2e925fd9bac3b71a56'}.
Traceback (most recent call last):
  File "/hydroshare/hs_tools_resource/utils.py", line 24, in parse_app_url_template
    new_url_string = Template(new_url_string).substitute(merged_term_dic)
  File "/usr/local/lib/python2.7/string.py", line 176, in substitute
    return self.pattern.sub(convert, self.template)
TypeError: expected string or buffer
```

I also confirmed that if I change the `parse_app_url_template` function in `hs_tools_resource.utils`  to a noop, it works again.

Looks like your bug, @zhiyuli... reassigning.

**Comment by zhiyuli** [comment] 2018-01-04 17:12
@aphelionz 
It is stored on HydroShare main IRODs zone, not federated zone.
Thanks for sending me the logs. I will take a look .

**Comment by zhiyuli** [comment] 2018-01-08 17:07
@aphelionz 
I was not able to duplicate this error locally. Any suggestion how I should proceed with debugging? Thanks

**Comment by zhiyuli** [comment] 2018-01-09 16:04
So far this error is only specific to this resource on www. We were not able to duplicate it on beta (which has the same code as WWW for now) or local VM. @aphelionz ran a script to detect the integrity of this resource which didnt find any issue.

@dtarb 
I am the owner of this resource. I can either delete it or leave it as is. Please advise.

**Comment by dtarb** [comment] 2018-01-10 21:47
I do not like to ignore things that are symptoms of problems.  Because it is better for us to identify and fix problems, before a user does, and gets discouraged.

If the behavior is not reproducible on beta, then we know that something is different between www and beta.  This could be the code, the database, the content of iRODS, or something else.  I would prefer that this be kept open as a record of a bug, that we should delve into (agreed not critical priority) at some point in time.  We should also be able to exactly replicate www on beta or one of our staging machines to examine things like this in more detail.

Speculating, based on what I am reading above does the Open With functionality add an attribute to a resource, to, for example put an entry on the open with button.  If that attribute changes, or that web app resource is deleted what happens?  Is something set to "none".  Could that have happened here.

**Closed** 2018-09-13 18:42 UTC
Labels: Needs Discussion, Resource Model, bug
