### ISSUE TITLE
No files to display - missing data 

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2431] opened 2017-11-13 23:07 UTC
@alvacouch 
These two resources used to have files, but today they do not.  Both of these resources had data three weeks ago, and there is no reason to suspect a human has cleared the resource contents. 
https://www.hydroshare.org/resource/3a925bd4a5784a38944b1e8b51224de1/
https://www.hydroshare.org/resource/70b977e22af544f8a7e5a803935c329c/
![image](https://user-images.githubusercontent.com/4108369/32754105-4e1e6066-c884-11e7-99f4-53de4fba0966.png)
I've given you edit permissions for both.
C

**Comment by Maurier** [comment] 2017-11-13 23:12
@alvacouch The front end is failing to get the folder structure for these resources through the API call
`/hsapi/_internal/data-store-structure/`

I've seen this error multiple times in the last few weeks.

**Comment by ChristinaB** [comment] 2017-11-13 23:33
Thanks for getting back to me.  I'm mildly distressed because the data and notebooks for one of these if for a paper I am trying to get out by AGU.  This looks like a really bad error.  So the data is there it's just not being displayed?

**Comment by dtarb** [comment] 2017-11-14 01:39
This is widespread, and needs some prompt action.  Here is another resource where this is a problem. https://www.hydroshare.org/resource/64fb0a478974411caea3335e2d07975c/.  An attempt to download a bag results in the following errors
![image](https://user-images.githubusercontent.com/3456833/32758512-07ee548e-c8a2-11e7-80f4-29bef8f4cc57.png)

**Comment by hyi** [comment] 2017-11-14 02:17
@dtarb @cbcunc @phuongdm @aphelionz From the bag download error, I can see the following two issues possibly related to deployment oversight:

- download bag path points to hydrotest41Zone which is the default iRODS setting in local_settings.py, so it appears local_settings.py did not get restored with production settings on production server.

- We can see debug traceback on www, which means debug is set to True, which proved again local_settings.py is wrong, since the local_settings.py on production server should have DEBUG set to False.

Restoring production settings followed by rebuilding Django site could fix this deployment issue.

-

**Comment by alvacouch** [comment] 2017-11-14 02:19
I agree with @hyi. Also make sure to reset the bag_modified flag to cause regeneration of all bags. This should be set in the deploy script.

**Comment by phuongdm** [comment] 2017-11-14 02:25
@hyi, 

You are correct. That's my fault. I'm going to rebuild again with the correct local_settings.py

**Comment by phuongdm** [comment] 2017-11-14 03:14
@ChristinaB, @dtarb, @Maurier, all

I have run rebuild on the www.hydroshare.org. Could you please re-check your resources?

Sorry again,
Phuong

**Comment by Maurier** [comment] 2017-11-14 03:20
I think it worked, at least partially. The resources posted by @ChristinaB have been restored, but I see at least one other instance still showing the behavior:

https://www.hydroshare.org/resource/7a77f525667b42f69cdc3f8db18e1280/

**Comment by dtarb** [comment] 2017-11-14 04:24
We should establish the practice of running Tony's check to download all resources script as a test on each release candidate, and as a test on each production deploy.

**Comment by ChristinaB** [comment] 2017-11-14 14:59
Thanks for the quick response everyone.  Can I suggest that we recreate this 'No files to display' every April 1 for an April Fools joke?    

In other news, it looks like the new release also broke the jupyter hub server.  Should I make a new Github issue for that? I'll email @Castronova first.

**Comment by phuongdm** [comment] 2017-11-15 04:59
@alvacouch 

The resource `7a77f525667b42f69cdc3f8db18e1280` has a file: `data_48.15625_-121.28125.gz` but after run 

`./hsctl managepy ingest_irods_files 7a77f525667b42f69cdc3f8db18e1280`

the file has disappeared. What did I do wrong here?

![image](https://user-images.githubusercontent.com/24579275/32819547-cf57741a-c997-11e7-9807-39d1066ea271.png)

![image](https://user-images.githubusercontent.com/24579275/32819466-6e922d46-c997-11e7-990b-90b32c9f0b7e.png)

**Comment by phuongdm** [comment] 2017-11-15 05:12
@dtarb @ChristinaB 

Sorry for the late response, but we need to avoid to touch to the production server while users access it. And some of you also have presentations/classes today on HydroShare. So, night work might be the best choice.

**Comment by dtarb** [comment] 2017-11-15 12:54
@alvacouch may be able to help as he wrote that ingest_irods code (I think).  I did make a copy of the zipped bag of this resource that includes this file on Monday when the problem was reported and @ChristinaB  bagging seems to be working now if you need to recover the files before we are able to fix the problem.

**Comment by alvacouch** [comment] 2017-11-15 19:54
@dtarb @phuongdm The trace above is correct function of the script `ingest_irods_files`. The error messages always show; they are django messages that happen whenever a command is invoked. The actual output of the script indicates **correct** operation.

**Comment by alvacouch** [comment] 2017-11-15 20:02
@dtarb @phuongdm @aphelionz This may be a UI problem. My command says there are 25 files available but they aren't showing up. Here's what it prints on www: 
```
LOOKING FOR UNREGISTERED IRODS FILES FOR RESOURCE 7a77f525667b42f69cdc3f8db18e1280 
(current files 25)
```

**Comment by phuongdm** [comment] 2017-11-15 20:03
@alvacouch 

The file has gone instead of the behavior of ingest_irods_files is created Django file records.

**Comment by alvacouch** [comment] 2017-11-15 20:05
@dtarb @phuongdm @aphelionz I do not have irods credentials to login to the www repository to check the irods files actually present.

**Comment by alvacouch** [comment] 2017-11-15 20:09
@dtarb @phuongdm @aphelionz 

[hydro-service@www hydroshare]$ ./hsctl managepy check_irods_files 7a77f525667b42f69cdc3f8db18e1280
.....
LOOKING FOR FILE ERRORS FOR RESOURCE 7a77f525667b42f69cdc3f8db18e1280
[hydro-service@www hydroshare]$ 

**This passes the correspondence test between django and iRODS.** 
So there is something very wrong with the ui (or these files have been mis-located outside 7a77f525667b42f69cdc3f8db18e1280/data/contents, which is unlikely)

**Comment by alvacouch** [comment] 2017-11-15 20:41
@aphelionz @phuongdm @dtarb I wrote a custom debugger to list what the system is finding. It is located in www:hydroshare/management/commands/junk.py Its output is as follows: 

```
[hydro-service@www hydroshare]$ ./hsctl managepy junk --verbose 7a77f525667b42f69cdc3f8db18e1280
MANAGEPY:
  - docker exec -u hydro-service -ti hydroshare python manage.py junk --verbose 7a77f525667b42f69cdc3f8db18e1280
...
LOOKING FOR FILE ERRORS FOR RESOURCE 7a77f525667b42f69cdc3f8db18e1280
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/observatory_gridded_hydromet.py
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/Observatory_Sauk_forJenLennon062917Jim.ipynb
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/Observatory_Sauk_forJenLennon071017Jim.ipynb
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/SaukRiver_Sauk_obs_cfs.dly
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/ThunderBasinSNOTEL.txt
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/month_WRF_CIG_1950_2010.csv
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/month_Livneh1915_2011.csv
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/Zdiff.csv
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/12186000.streamflow.daily.cms.txt
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/12189500.streamflow.daily.cms.txt
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/Precip.daily.WRF.m.txt
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/Precip.daily.Liv2013m.txt
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/ChocolateGlacier.streamflow.daily.cms.txt
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/CoolGlacier.streamflow.daily.cms.txt
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/SuiattleGlacier.streamflow.daily.cms.txt
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/ELA_all_6_7.txt
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/VistaGlacier.streamflow.daily.cms.txt
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/DustyGlacier.streamflow.daily.cms.txt
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/HoneycombGlacier.streamflow.daily.cms.txt
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/ErmineGlacier.streamflow.daily.cms.txt
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/gl_cov_glac_6_7.txt
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/Observatory_Sauk_WatershedHydroMetDownload.ipynb
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/Observatory_Sauk_forJenLennon062917.ipynb
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/data_48.15625_-121.28125.gz
check_irods_files: check Django path 7a77f525667b42f69cdc3f8db18e1280/data/contents/USC00455678.csv
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/12186000.streamflow.daily.cms.txt
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/12189500.streamflow.daily.cms.txt
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/ChocolateGlacier.streamflow.daily.cms.txt
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/CoolGlacier.streamflow.daily.cms.txt
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/data_48.15625_-121.28125.gz
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/DustyGlacier.streamflow.daily.cms.txt
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/ELA_all_6_7.txt
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/ErmineGlacier.streamflow.daily.cms.txt
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/gl_cov_glac_6_7.txt
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/HoneycombGlacier.streamflow.daily.cms.txt
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/month_Livneh1915_2011.csv
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/month_WRF_CIG_1950_2010.csv
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/observatory_gridded_hydromet.py
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/Observatory_Sauk_forJenLennon062917.ipynb
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/Observatory_Sauk_forJenLennon062917Jim.ipynb
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/Observatory_Sauk_forJenLennon071017Jim.ipynb
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/Observatory_Sauk_WatershedHydroMetDownload.ipynb
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/Precip.daily.Liv2013m.txt
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/Precip.daily.WRF.m.txt
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/SaukRiver_Sauk_obs_cfs.dly
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/SuiattleGlacier.streamflow.daily.cms.txt
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/ThunderBasinSNOTEL.txt
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/USC00455678.csv
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/VistaGlacier.streamflow.daily.cms.txt
check_irods_files: found iRODS path  7a77f525667b42f69cdc3f8db18e1280/data/contents/Zdiff.csv
```
**It found all files in both Django and iRODS.**

**Comment by phuongdm** [comment] 2017-11-15 22:10
It seems that @alvacouch is correct. This may be an UI problem. 

@hyi  

Could you debug this issue for us? @aphelionz doesn't have access to www.

**Comment by aphelionz** [comment] 2017-11-17 16:34
Some updates, folks:

1. I do have access to www @dtarb @hydroadmin @alvacouch 
2. I noticed that the UI is throwing an error based on this line https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/resource_folder_hierarchy.py#L86

That tells me that this is NOT a UI issue and that Django is having an issue finding that logical file. I need more time to figure out whether or not that's in the db or iRODS, or both, or neither.

@phuongdm and I are doing a deployment on beta this evening to test and we will look at it over the weekend, provided we can recreate the issue on beta.

Thank you for your patience.

**Comment by hyi** [comment] 2017-11-17 17:01
@aphelionz @alvacouch @phuongdm Given the information above, my hunch is that the ingest_irods_files script, which was written before composite resource was deployed if I remember this correctly, does not handle logical files, hence the logical file does not exist for re-ingested irods files in Django DB. In any case, it looks to me like a Django DB issue for this problematic issue.

**Comment by alvacouch** [comment] 2017-11-19 14:20
@hyi @phuongdm @aphelionz It's worse than this. Look at the following: 

```
hydro-service@beta hydroshare]$ ./hsctl managepy fix_missing_logical_files 7a77f525667b42f69cdc3f8d
b18e1280
...
SETTING GENERIC LOGICAL FILE FOR FILES IN RESOURCE 7a77f525667b42f69cdc3f8db18e1280
Logical file missing for file Observatory_Sauk_forJenLennon071017Jim.ipynb
Logical file missing for file data_48.15625_-121.28125.gz
```
This persists when repeated. **The script to fix logical files isn't fixing them.**

**Comment by aphelionz** [comment] 2017-11-19 14:58
@alvacouch That was what I experienced as well... is it possible to manually fix this resource in the DB? just hand jam it for now and then do root cause analysis + fix after AGU?

cc @hyi @phuongdm

**Comment by alvacouch** [comment] 2017-11-19 15:25
@aphelionz @hyi @phuongdm This is a class botch. The fix_missing_logical_files routine is calling the wrong fix routine. It's calling the default fix for BaseResource, which does nothing. Fix is imminent.

**Comment by aphelionz** [comment] 2017-11-19 15:34
aha!

**Comment by pkdash** [comment] 2017-11-19 15:35
I have a fix for it which I am testing now.

**Comment by pkdash** [comment] 2017-11-19 15:35
Should I make it a hotfix?

**Comment by aphelionz** [comment] 2017-11-19 15:35
It's a race!

**Comment by alvacouch** [comment] 2017-11-19 15:42
@pkdash @aphelionz I have fixed this resource -- inelegantly --- and it works properly. The problem was that the set_default_logical_files was being called in the base class BaseResource, which does nothing. 

If you want to take the ticket and make a hotfix, please do. 

The deeper question is why this is happening on a widespread basis for people using jupyter. This seems to be a problem with REST calls that create files.

**Comment by pkdash** [comment] 2017-11-19 15:47
@alvacouch Yeah that's what I found when trying to debug the management script. Was calling the function on BaseResource class. Have now fixed it and testing locally and seems to work. Will make a hotfix today. Also would try to look into the rest call. Thanks

**Comment by aphelionz** [comment] 2017-11-19 15:55
@pkdash Can you hotfix and also run the script on prod? That would be good considering it's the weekend and usage is low.

**Comment by alvacouch** [comment] 2017-11-19 15:55
@pkdash (cc @aphelionz) I will be online today. Let me know when you have something to review. 

Meanwhile I suspect there are code paths where the post-add signals are not being sent. I'll take another look at file creation myself and look for such places. I don't know if they're sent when we copy in from IRODS.

**Comment by alvacouch** [comment] 2017-11-19 15:59
@pkdash @aphelionz Note that I fixed the resource of interest but that there are many others on beta that need the fix, so you can test your hotfix on those.

**Comment by alvacouch** [comment] 2017-11-19 16:11
@pkdash I have reverted my changes on beta, so you can use that for testing. I am moving off beta to my own test servers.

**Comment by alvacouch** [comment] 2017-11-19 16:42
@pkdash @aphelionz @phuongdm FYI: I am checking on the possibility that the exact same thing is happening when we add files that is happening in the management script, i.e., we get an instance of BaseResource rather than CompositeResource. 

There is some crazy mezzanine stuff going on in hs_core/models.py that affects the routines that get resource type. I do not trust it. 

Many of the REST calls use `authorize`: 

https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/utils.py#L159

which calls `get_resource_by_shortkey`: 

https://github.com/hydroshare/hydroshare/blob/develop/hs_core/hydroshare/utils.py#L68

which uses a rather funky mezzanine type conversion in `models.py` here: 

https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L3472

which might not properly account for proxy classes. The type returned by this is passed as the object when sending post_add_files signals. 

If this type is incorrect, logical files won't get created.

**Comment by aphelionz** [comment] 2017-11-19 17:12
All the more reason to gut mezzanine. However, the AGU mandate remains - we need to make sure things are functioning as smoothly as possible in the next ~2 weeks before we go in and get surgical on the system. For now we need to live with a working fix_missing_logical_files function that we run periodically. In the meantime, let's continue to catalog code paths that are affected by this to tackle after the conference.

Thank you for your looking into this @alvacouch @phuongdm @pkdash @hyi

**Comment by alvacouch** [comment] 2017-11-19 17:36
@aphelionz I don't agree. If my theory is correct, we can safely patch the responders in the REST API.

**Comment by alvacouch** [comment] 2017-11-19 17:47
@aphelionz @pkdash Theory incorrect. Still looking. Whatever it is seems quite systemic, though.

**Comment by pkdash** [comment] 2017-11-19 18:10
@alvacouch The only purpose of having this function ```get_resource_by_shortkey``` is to get a typed resource instance given a resource id. So I don't think the problem is with this function.

**Comment by dtarb** [comment] 2017-11-19 18:11
See #2456 that I just filed.  This may (or may not) have a similar root cause, but it is a presently reproducible way to create a resource that has content files that do not show in the display.

**Comment by pkdash** [comment] 2017-11-19 18:55
@alvacouch Here is the PR https://github.com/hydroshare/hydroshare/pull/2458 for you to review.

**Comment by pkdash** [comment] 2017-11-19 18:57
I will be online again in couple of hours.

**Comment by pkdash** [comment] 2017-11-19 21:24
@alvacouch The ingest_irods_files management command seems to have the same bug as the one I fixed for the missing logical file management command.  Have a look at this line: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/management/commands/ingest_irods_files.py#L154

**Comment by alvacouch** [comment] 2017-11-20 15:16
@pkdash Yes. Could you patch. it properly?

**Comment by alvacouch** [comment] 2017-11-20 15:20
@aphelionz This behavior is probably caused by a one-line bug. So if we can find it, we should squash it.

**Comment by aphelionz** [comment] 2017-11-27 22:02
Between @pkdash , @alvacouch , @phuongdm , and a tiny bit of deployment help from me… it looks like this is fixed. Please review at https://beta.hydroshare.org/resource/7a77f525667b42f69cdc3f8db18e1280/

**Comment by ChristinaB** [comment] 2017-11-27 23:34
Nice work!! Thanks everyone. HydroShare gets better every day.

**Closed** 2017-12-18 18:29 UTC
Labels: bug, High Priority, in progress, Possible Hotfix
