### ISSUE TITLE
Composite Resource: Bagit Manifest duplicating files

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2404] opened 2017-11-08 06:09 UTC
The Bagit manifest file is supposed to list each file within a resource along with its checksum value so that each file's integrity could be verified upon download. For some reason, some of the files in the Bagit manifest for composite resources are being duplicated. For example, here is an example of the Bagit manifest for this resource:

https://www.hydroshare.org/resource/9cc7a28a95cb4ecdbb258b10847e429d/

![image](https://user-images.githubusercontent.com/3485902/32533816-ccd966ea-c40f-11e7-9a45-e43a1a9911a8.png)

Also concerning is that the checksum values on the two entries for the resourcemetadata.xml file are not identical.

@hyi and @pkdash - I'm assigning this one to you two. If you decide who is gong to work on this, then one of you can un-assign yourself.

**Comment by pkdash** [comment] 2017-11-08 13:42
@hyi  I have not worked with the code that generates this manifest file. Can you work on this? Otherwise, let me know I will try to resolve it. Thanks.

**Comment by hyi** [comment] 2017-11-08 14:06
@pkdash OK. I can take a look at this.

**Comment by hyi** [comment] 2017-11-13 16:06
@horsburgh The manifest file is created by an iRODS rule file, and I looked at this resource and the rule file, but cannot figure out what could have caused this duplication. It does not happen for all composite resources, for example, the manifest file looks correct for this composite resource: https://www.hydroshare.org/resource/87e215f7e37e4fa1ad309e70e092c5e5/. Is there a particular workflow you can share that could have something to do with this duplication error? I guess you can start from recreating this resource and see where and when this duplicate files in the manifest file issue starts to occur to isolate which specific action that have caused this issue.

**Comment by horsburgh** [comment] 2017-11-13 16:16
@hyi - I can try to get to this soon. I'm traveling this week to a workshop and so trying to get ready. I suspect it has something to do with adding files, removing them, and then adding them again to the resource.

**Comment by pkdash** [comment] 2018-05-09 15:44
@horsburgh Is this still an issue?

**Comment by horsburgh** [comment] 2018-05-09 17:42
This is still an issue on production (www). Here's the workflow I used to duplicate it:

1. Create a new composite resource with only a title
2. Enter edit mode
3. Add a readme.txt file to the resource
4. Download the resource bag - up to this point everything is OK and the manifest file is correct.
5. Add all of the files for a shapefile to the resource
6. Right click on the ".shp" file to convert to geographic feature file type 
7. Download the resource bag - up to this point everything is OK and the manifest file is correct.
8. Go back into Edit Mode for the resource
9. Upload a zip file containing a geographic raster (two .tif files and a .vrt file)
10. Right click on the .zip file and covert to raster file type
11. Download the resource bag, and now there are duplicate entries for some of the files in the BagIt manifest.  It looks like the files for the readme.txt file and the shapefile are duplicated, but not the raster files.

My testing resource is here: 

https://www.hydroshare.org/resource/82204e59185b4ed9bd0117a0e0dc0a11/ 

I made this resource public so anyone can grab the files for testing, but will eventually delete. While this is still an issue on www, it may not be an issue with @pkdash 's phase 2 implementation of composite resource, so the phase 2 implementation may just fix this.

**Comment by aphelionz** [comment] 2018-05-15 21:13
@pkdash or @hyi  Can you please add a 1,2,3 point estimate label to these tickets?

**Comment by pkdash** [comment] 2018-05-29 13:17
@hyi Did you try to reproduce this on park? I couldn't reproduce this issue on park.

**Comment by hyi** [comment] 2018-05-29 19:13
@pkdash I have not tried. @horsburgh It'd be great if you could try on park to see if you can reproduce this issue on park. @pkdash cannot reproduce this issue on park, and suspect this issue has been fixed in his composite phase 2 implementation.

**Comment by horsburgh** [comment] 2018-05-30 05:33
@pkdash and @hyi - I am unable to test this. When I upload a zipped file containing a .vrt file and two .tif files, I get the following error when I right click on the zipped file and try to convert it to a geographic raster aggregation:

![image](https://user-images.githubusercontent.com/3485902/40700828-7a730568-6398-11e8-9a40-214d393b9e4a.png)

If I create a new folder and then drop in the .vrt and the two .tif files and then right click on the folder to convert it to a geographic raster aggregation, it works, and the BagIt manifest files looks correct.

**Comment by pkdash** [comment] 2018-05-30 12:59
@horsburgh I used this zip file (contains one vrt and two tif files) and was able to create raster aggregation from it.
[Raster.zip](https://github.com/hydroshare/hydroshare/files/2053969/Raster.zip)

**Comment by dtarb** [comment] 2018-10-29 20:10
Done in 1.16

**Closed by dtarb** 2018-10-29 20:10 UTC
Labels: (2) Medium Effort, Composite, File System, High Priority, Resource Model, bug
