### ISSUE TITLE
Word wrap needed in display of aggregation metadata text

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3804] opened 2020-04-02 13:02 UTC
I have a raster aggregation in a resource with method metadata that does not word wrap.  It should
https://www.hydroshare.org/resource/877bf9ed9e66468cadddb229838a9ced/
![image](https://user-images.githubusercontent.com/3456833/78252352-f19e3e80-74af-11ea-899b-750cfe7709d2.png)

**Comment by sblack-usu** [comment] 2020-04-08 21:52
This was caused by #2063, the word-break is no necessary to get the wrapping for the coordinate string and causes the word break in the method described here.

**Comment by horsburgh** [comment] 2020-04-24 16:32
@sblack-usu - if this is just a display issue do you want to reassign this one to Mauriel?

**Comment by sblack-usu** [comment] 2020-04-24 16:39
This one is done and part of 1.32 which is going out next week.

**Closed** 2020-04-29 15:07 UTC
