### ISSUE TITLE
Sign up failing on www

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2527] opened 2017-12-12 12:58 UTC
Attempts to create an account on www.hydroshare.org are failing with the message.  
![image](https://user-images.githubusercontent.com/3456833/33885679-474adeac-df01-11e7-8ce1-431d6bfa03f2.png)

**Comment by hyi** [comment] 2017-12-12 15:00
@aphelionz Just checked log and here is the error for account signup:
```
[12/Dec/2017 14:46:14] ERROR [django.request:256] Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/hydroshare/theme/views.py", line 168, in signup
    new_user = form.save()
  File "/hydroshare/theme/forms.py", line 273, in save
    active=False,
  File "/hydroshare/hs_core/hydroshare/users.py", line 87, in create_account
    University.objects.get(name=dict_item)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
**ProgrammingError: relation "hs_dictionary_university" does not exist**
LINE 1: ...ty"."name", "hs_dictionary_university"."url" FROM "hs_dictio...
```
I also run migrate command and it shows no migrations to apply. @aphelionz Let me know if you will look into it. Otherwise, I can look into it if needed.

**Comment by hyi** [comment] 2017-12-12 15:05
@aphelionz I am running "makemigrations" on www now since I cannot reproduce this issue on my local development branch which I just merged with master yesterday and did a rebuild, so I suspect it is a migration issue. Let's see if "makemigrations" followed by "migrate" would fix this issue.

**Comment by aphelionz** [comment] 2017-12-12 15:08
@hyi ok, I have a hotfix in place. It's odd that the `master` branch isnt applying the migrations

**Comment by hyi** [comment] 2017-12-12 15:11
@aphelionz "makemigrations" command ended and it said no changes detected, so it does not look like migration is an issue. Somehow it works on playground which I just merged with latest master branch yesterday and did a rebuild which include SciDAS supercomputing demo code. I have just approved your hotfix, so you can merge it and deploy it to see if that fixed this issue.

**Comment by aphelionz** [comment] 2017-12-12 15:14
ok

**Comment by aphelionz** [comment] 2017-12-12 15:32
@dtarb @hyi All is well on WWW

Due to the fact that we copied settings.py from a backup, the hs_dictionary app was neve radded to the INSTALLED_APPS configuration directive. I added that, and ran migrate, and it added the necessary db tables.

I also used git fetch and git checkout to switch from 1.14.1 to 1.14.2 and ran hsctl restart. I know, I know. Sorry. But it was one line of code and it all worked out.

**Comment by pkdash** [comment] 2017-12-12 15:45
@aphelionz Curious to know why a backup copy of the settings.py was used in deployment and not the one that was in release RC branch?

**Comment by hyi** [comment] 2017-12-12 15:59
@aphelionz Thanks. It explains why it works on playground but not on www.

**Comment by aphelionz** [comment] 2017-12-12 16:05
@pkdash maybe an oversight on our part. let's discuss elsewhere

**Closed by aphelionz** 2017-12-12 16:05 UTC
Labels: bug
