### ISSUE TITLE
Map doesn't show all search results - Discover feature parity 

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#3995] opened 2020-10-15 14:09 UTC
The search results table shows that 5 resources match my query and each has spatial information (as indicated by the globe icon). However only 4 points appear on the map. I would expect all resources in the table to appear on the map.

Steps to reproduce:
1. Search for Castronova
2. Go to page 2 of the results
3. Open the map
4. Notice that 5 resources appear in the list but only 4 on the map.

![image](https://user-images.githubusercontent.com/4822372/96140640-257e0600-0ece-11eb-967d-752422839def.png)

![image](https://user-images.githubusercontent.com/4822372/96140622-20b95200-0ece-11eb-8a40-1e7bb86c8373.png)

**Comment by cuahsimarko** [comment] 2020-10-15 14:23
I’m unable to reproduce this. Can you suggest a next step here? At all zoom levels on beta.hydroshare.org it shows all five for me (one in Pennsylvania). What browser, OS are you using?

**Comment by Castronova** [comment] 2020-10-15 14:26
I'm using google chrome

**Comment by sblack-usu** [comment] 2020-10-15 14:29
I was able to reproduce this in firefox after hitting last modified sorting... There were 5 results in the list, 4 shown on the map and the page header showed that there should be 40, I think it thought it was showing results from the first page, but it really was showing the second page.
<img width="920" alt="Screen Shot 2020-10-15 at 8 26 22 AM" src="https://user-images.githubusercontent.com/35820390/96143366-43446e80-0ec0-11eb-9bf5-39cd88b752fe.png">

**Comment by cuahsimarko** [comment] 2020-10-15 14:46
The issue here is the "CUAHSI Presentations" resource has 0.0000 North 0.0000 South -180.0000 East 180.0000 West and therefore is registering as having geographic coordinates and the map API or Discover logic is not drawing a marker or is rendering it in a non-visible location. As the resource does contain spatial coverage, I suggest the Globe icon and tooltip are valid.

**Comment by cuahsimarko** [comment] 2020-10-15 14:47
Scott, when you change sort directions, it goes back to the first page automatically.

**Comment by cuahsimarko** [comment] 2020-10-15 14:49
@Castronova @sblack-usu please close this GitHub Issue, if you see this as resolved from Discover bugs and you can add it to informal running list of data quality issues that I believe Martin is leading for now (or the task has fallen to him by default until we structure a comprehensive project). If not resolved, let's discuss what needs to change.

**Comment by sblack-usu** [comment] 2020-10-15 14:51
> Scott, when you change sort directions, it goes back to the first page automatically.

Then explain the screenshot? I've been able to reproduce it several times.

**Comment by cuahsimarko** [comment] 2020-10-15 18:04
After realizing this GitHub Issue is a 2-for-1, my understanding is that Tony's issue is a data issue and can be temporarily fixed by properly updating the Spatial Coverage data for the resource "CUAHSI Presentation" and/or wait for the larger data quality effort around resources to take shape.

The second issue was reported by Scott and initially not fully understood by me. This is a bug and has been resolved, and the process for verification and deployment will go through the standard procedures. The effect is:

1. Sorting by column no longer automatically jumps to the first page (do not assume the user wants to see the first page, maybe they still want to stay on the last page but just sort by a different method)

2. When searching freetext, then activating map, then going to the last page, then sorting by column, the erroneous behavior of jumping to the first page no longer occurs. See commit https://github.com/hydroshare/hydroshare/pull/3999/commits/9f89f24beddeaf37931ca6ca5c1d107514951e59

**Comment by sblack-usu** [comment] 2020-10-16 18:36
>Sorting by column no longer automatically jumps to the first page (do not assume the user wants to see the first page, maybe they still want to stay on the last page but just sort by a different method)

I'm not sure if we can just run with this assumption or not.  I can see any argument both ways but you are better informed than I am on this topic.

**Comment by martinseul** [comment] 2020-10-19 14:36
this is  tricky one, when looking at Amazon or ebay each change in sort order sends you back to the first page and that is also the behaviour I would expect. It's a bit more subtle here as you click on  a table element which could suggest it only applies to the current content.

**Comment by hydrocheck** [comment] 2020-11-06 02:39
Issue resolved as a part of the Discover redesign

**Closed by hydrocheck** 2020-11-06 02:39 UTC
Labels: Discover, bug
