### ISSUE TITLE
Reference Model Program resource to allow publication without content files

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#856] opened 2016-01-04 15:23 UTC
The resource at https://www.hydroshare.org/resource/77c54c01ab99439abb263ea0e11b18c3/ is a reference to HEC-HMS.  This is needed in HydroShare so that a Model Instance can refer to it, but I do not want to store the HEC program in HydroShare as the US Army website is the authoritative site.  This resource type needs to be allowed to be made public/discoverable without content files.

Refer to #488 for additional background.

**Comment by mohamedmorsy** [comment] 2016-01-05 16:25
@dtarb @Castronova @goodalljl Our idea behind creating the Model Program resource type is to preserve a specific version for a specific model so we can link it later with a specific Model Instance resource type to promote reproducible modeling results. If the Model Program resource were linked, whatever happens at the main website of that model would be reflected in the version stored in the HydroShare system. Only by having a specific Model Program version stored in HydroShare can we ensure that the results of a specific Model Instance resource linked to the Model Program engine will be reproducible. For example, the EPA SWMM model webpage (http://www.epa.gov/water-research/storm-water-management-model-swmm) always includes the *latest* version of the SWMM model (i.e whenever a new version comes out they replace the old version with the new version). So if a Model Instance produces results based on a mutable SWMM Model Program resource linked to this webpage, the results are not necessarily reproducible. The SWMM version used to produce the results from the Model Instance needs to be stored on HydroShare and the authoritative site needs to be cited appropriately.

**Comment by Castronova** [comment] 2016-01-05 19:21
@mohamedmorsy Since Model Program resources cannot be made public without content files, we are unable to represent closed source models/applications within HydroShare.  Consider a script or model that is executed as a tool within ArcMap.  The creator of the Model Program resource cannot upload content to satisfy the **computational engine** or **software** metadata because it is not physically and/or legally possible.  We should not prevent users from creating Model Program resources when these metadata are not available.  This issue can be side-stepped by uploading a "dummy" file or providing **documentation** and/or **release notes** because there is no distinction as to which content files are required.  This seems like an oversight in our implementation and I suggest we revisit which metadata are required to make this resource public.   Below are my initial thoughts, what do you think @goodalljl and @mohamedmorsy?

|term | required?| reason |
|---|---|---|
|Computational Engine | optional | may not be available |
|Software | optional | may not be available |
|Documentation | optional | may not be available as document (e.g. webpage) |
|Release Notes | optional | may not be available |
|Release Date | REQUIRED | important to identify software versioning |
|Website | optional | website may not exist for (e.g. academic software/scripts) |
|Version | REQUIRED | important to identify specific software release |
|Language | optional | may not be obvious for closed-source applications
|Software Repository | optional | may not be publicly available |
|Operating System | REQUIRED | important for determining OS compatibility |

Note: Either **Release Date** or **Version** must be provided, not necessarily both.

**Comment by mohamedmorsy** [comment] 2016-01-05 20:16
@Castronova I agree totally with you that we need the metadata elements: Release Date, Version, and Operating System to be required to make the resource public or discoverable. But beside that I would like also the user to satisfy one of the following metadata elements: Computational Engine, or Software by uploading the related files.

**Comment by goodalljl** [comment] 2016-01-19 17:54
@Castronova @mohamedmorsy @dtarb I agree with Mohamed that

**Comment by goodalljl** [comment] 2016-01-19 18:11
@Castronova @mohamedmorsy If the resource is a reference type like @dtarb is describing, then it is required to have some way of linking to the resource it references. So the required metadata is really a function of whether the resource is a reference, copy, or original resource type. If it is a copy or original resource type, then it requires software as Mohamed says. If it is a reference resource type as Dave T is describing, then it requires perhaps a website. @hyi developed code that changes the reference format based on whether the resources is a reference, copy, or original type. You may be able to use similar code to test if required metadata is provided based on the type.

I'd also say that we want to probably discourage reference model programs because it reduces the potential for reproducible for the reasons Mohamed gave.

**Comment by dtarb** [comment] 2016-01-19 21:07
Should not be closed until there is some code deployed that implements the solution being discussed.

**Comment by Castronova** [comment] 2016-01-26 18:40
@dtarb @goodalljl @mohamedmorsy: I've updated the model program resource to reflect this discussion.  It is currently deployed on http://playground.hydroshare.org/ (until 1/28/16).  Can you please test it and make sure that these modifications work as expected.  If not, I can make changes to the required metadata fields.

Summary of changes:
For a model program to be made public it must have:
* Abstract
* Keywords
* ModelVersion
* ModelReleaseDate
* ModelOperatingSystem
* One of the following: (1) ModelWebsite, (2) either ModelEngine or ModelSoftware

**Comment by Castronova** [comment] 2016-01-27 21:13
I initially thought that the following metadata *ModelVersion*, *ModelReleaseDate*, and *Model OperatingSystem* should all be required to help identify a unique release of a particular model.  While, *ModelOperatingSystem* provides information that would be useful to other HydroShare users, it is not necessarily required identify a specific "snapshot" of a model.  Additionally, since either *ModelReleaseDate* or *ModelVersion* can be used to identify a specific "snapshot" of model software, both should not be required.  In fact, it is likely that only one of these is known, e.g. *ModelVersion* but not *ModelReleaseDate*.  With these considerations I propose:

For a model program to be made public it must have:
* Abstract  *(same as all other resources)*
* Keywords *(same as all other resources)*
* One of the following: (1) ModelVersion, (2) ModelReleaseDate
* One of the following: (1) ModelWebsite, (2) either ModelEngine or ModelSoftware

Any thoughts?

**Comment by danames** [comment] 2016-01-27 21:22
I suggest dropping ModelReleaseDate and only using ModelVersion. Any one
posting a model should know its version. If it doesn't have a version, then
it is likely an original model and it's high-time that the programmer
assign it a version. This will encourage them to do so.

**Comment by mohamedmorsy** [comment] 2016-01-28 16:01
I agree with Dr. Ames about making the ModelReleaseDate an optional metadata field. I still have concern about the last point (One of the following: (1) ModelWebsite, (2) either ModelEngine or ModelSoftware). When the user create a new Model Program resource type, he or she will specify a specific version of the Model Program. When the user just uses the ModelWebsite to point to the location of the engine or the software that does not guarantee the preservation of the same version all the time on the model official website. I stated that before as an example of the EPA SWMM model and how the official website changes with the time. I suggest to keep one of the ModelEngine or ModelSoftware as required field for making the resource public.

**Comment by Castronova** [comment] 2016-01-28 20:56
@mohamedmorsy I understand your concern, but consider a scenario in which the model developers have their own hosting (e.g. GIT).  In this case, making the user upload source code will only deter them from using the Model Program resource.  I think that we need to allow this type of behavior, and just be clear that the preferred usage is to upload model source code when applicable.

**Comment by dtarb** [comment] 2016-01-29 19:46
@Castronova I have tested this.  You can see the resource I am checking at http://playground.hydroshare.org/resource/3cdb9ce252f845e88a0ccd3425cd06b1.  It can be made public now, but there is ambiguity between the website in Resource Specific and the website in Related Resources hosted by that needs to be entered to have the citation refer to the offsite website rather than a HydroShare permalink.  I still think that this is too complicated and that our method for having a model instance of a model program that is hosted elsewhere (like this HEC case) clumsy and confusing.

**Comment by goodalljl** [comment] 2017-11-22 10:20
@Castronova Checking on status of this issue. I changed it to backburner as there hasn't been any updates recently, but if you think you can work on this and get it wrapped up, please let me know.

**Comment by Castronova** [comment] 2019-04-18 20:02
closing due to inactivity

**Closed by Castronova** 2019-04-18 20:02 UTC
Labels: Backburner, Modeling, enhancement, low priority
