### ISSUE TITLE
Resources files may be lost or unexpected files appear when repeatedly refreshing a HIS Referenced Time Series resource landing page

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#478] opened 2015-06-09 15:41 UTC
This issue may be related to #466

An unbroken Referenced Time Series (Refts) resource should contain four resource files: *.csv, *-wml_1.xml, *-wml_2_0.xml and *.png. When a user repeatedly refreshes a landing page (e.g., http://www.hydroshare.org/resource/cd54cddcabc24e80b5a91deb59cc681a/ 
or 
http://dev.hydroshare.org/resource/c377d07efcfb484ab0da1c5c2ec7c7ac/), it may happen:

1)	Snapshot 1: All four resource files display; the button “Download All Content as Zipped Bagit Archive” cannot display properly.
2)	Snapshot 2-4:  Some (2, 3) or all (4) resource files may be lost; the download button displays sometimes (3). 
3)	Snapshot 5: Unexpected files appear; No download button
4)	Snapshot 6: Error message

Snapshot 1:
![image](https://cloud.githubusercontent.com/assets/10070599/8062036/e8c96266-0e8a-11e5-9372-295b4635194e.png)

 
Snapshot 2:
![image](https://cloud.githubusercontent.com/assets/10070599/8062047/f6fb1168-0e8a-11e5-8ffa-05da23556387.png)

 
Snapshot 3:
 
![image](https://cloud.githubusercontent.com/assets/10070599/8062058/fe0860b4-0e8a-11e5-9741-d673f8585131.png)

Snapshot 4:
 
![image](https://cloud.githubusercontent.com/assets/10070599/8062063/055eb39a-0e8b-11e5-87cd-503dc88879e7.png)

Snapshot 5:
 
![image](https://cloud.githubusercontent.com/assets/10070599/8062066/0b2482be-0e8b-11e5-9896-09afe16120cd.png)

Snapshot 6:
 
![image](https://cloud.githubusercontent.com/assets/10070599/8062071/10e1b9f6-0e8b-11e5-904a-89cdbbb3c35d.png)

**Comment by dtarb** [comment] 2015-06-17 17:47
@zhiyuli indicated that this is still an issue with the new bagit restructuring in park.hydroshare.org.  

http://park.hydroshare.org/resource/3c74d1820b1948a48e91ecc0915f298e/

One possible reason for this is that the latency is due to the time being taken to reconstruct the files from the web service, rather than due to retrieving them from iRODS.  If this was the cause (which needs checking) then it would isolate this issue to RefTS.

**Comment by zhiyuli** [comment] 2015-06-17 23:11
@dtarb @selimnairb @hyi @jsadler2 

Hong and Brian,
I merged our current refts workflow (deprecated) into Hong's 446-improve-res-mod-perf branch. 
Now first time creating a refts res is implemented by "hydroshare.add_resource_files(res.short_id, *files)"; When users refresh the landing page, the res is updated via hydroshare.update_resource_file(res.short_id, file.name, file)". As Hong told me in the dev call, all old codes related to bag are removed. (see Line 542-546 in ts_utils.py).

A quick test shows the missing res files problem still happens. Also, I repeatedly typed the 'ils' command in console to inspect irods folder "/data/contents". It turned out irods really has some delay (see snapshot). Although we already decided to refactor current refts workflow and this problem may not interfere other res types, I still pushed it to branch "478-old-refts-on-new-irods" as an archive for future investigation…

Thanks
Drew
![image](https://cloud.githubusercontent.com/assets/10070599/8220735/a74107d8-1513-11e5-9790-e13f87aea089.png)

**Comment by hyi** [comment] 2015-06-18 13:48
@zhiyuli @selimnairb After looking into update_resource_file() routine in resource.py, I found it actually delete resource file first, then add an updated resource file, so calling update_resource_file() has the same effect as your previous implementation to delete it, then add an updated one. In our current model implementation, it may not be possible to update the file in place without deleting it first. So some delays are expected because you delete the file first, then add another updated file. This is not an iRODS issue, it is just the way our Django client is currently implemented. It does not appear to me it is a valid use case for the user to manually refresh page at random intervals. I think it should be implemented programmatically to refresh page automatically when all files are added/updated so this will not be an issue. Also, if you don't delete bags and re-create bags again with the new on-demand bagging workflow, the download button should always be there without disappearing.

**Comment by zhiyuli** [comment] 2015-06-18 14:19
@hyi Yes, I think in my case the communication between django server and irods server should be blocking communication. Something likes the function hydroshare.update_resource_file() should wait for a irods signal saying "all files are already stored properly", then return and go on with following code...

The bag download button is good now

Thanks
Drew

**Comment by danames** [comment] 2015-07-29 17:08
Closing this issue because it is related to the old design. We are refactoring the referenced time series and this issue will become irrelevant. See #502 .

**Closed by danames** 2015-07-29 17:08 UTC
Labels: bug, Referece Resources
