### ISSUE TITLE
Single subject keyword deletion fails

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#474] opened 2015-06-07 21:36 UTC
An attempt to delete a subject keyword where there is only one present results in a message "Error! Metadata updated failed."  If we are enforcing a policy that the last keyword can not be deleted the error message should be changed to "Cannot delete keyword.  At least one keyword is required".  

For other cases where the metadata update fails, the grammar should be corrected to "Error! Metadata updated failed."

**Comment by pkdash** [comment] 2015-06-08 04:29
For any metadata element when the update fails currently we just show that the update failed without showing more specific reason why it failed. Though at the the back end specific error is raised we are currently not propagating that message to the UI. That needs to be fixed/implemented.

**Comment by hyi** [comment] 2015-07-08 17:51
The issue is resolved. Closing.

**Closed by hyi** 2015-07-08 17:51 UTC
Labels: bug, Clean up
