### ISSUE TITLE
Labels and Favorite flags do not persist after refreshing the page.

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#825] opened 2015-12-14 17:01 UTC
As deployed live on hydroshare.org right now.

Steps to reproduce:
*  Add a resource to My Resources from the discovery page.
* In My Resources page, add a label and tag the resource with it.
* Refresh the page.
* At this point, the label appears no longer applied to the resource.

Other users might not experience this as it was the case when testing on beta, but it keeps happening to me. I can't reproduce this in my local environment.

**Comment by mjstealey** [comment] 2015-12-14 17:12
@mauriel133 - I can also replicate this behavior on www using the steps outlined.

Browser used: Safari - Version 9.0.1 (11601.2.7.2)

**Comment by hyi** [comment] 2015-12-14 17:31
@mauriel133 I can replicate this behavior on www as well. I also tried to create a resource, then followed the same steps and labels persist after refresh for the resources I created, but not persist after refresh from the resource I added from discovery page. So perhaps there are some underlying logic that clears the labels for resources added from discovery page?

**Comment by mauriel133** [comment] 2015-12-14 17:48
While trying to reproduce this error I found another issue:
* Started with a clean database and created two users, user1 and user2.
* Created a resource with user1 and made it discoverable.
* Logged in with user2 and tried to find the resource in the discovery page, but it doesn't show up no matter what search string I use.
* Went to user1's profile and clicked on the resource from there.
* In the resource landing page tried to add it to My Resources, but the action won't work and the resource doesn't get added. Here is the error I get (Chrome browser)
POST

>  http://localhost:8000/hsapi/_internal/b7b21b79ba7d4093a2c9fafc502b7803/label-resource-action/ 500 (INTERNAL SERVER ERROR)

* The ajax calls error clause is called when it returns and these are the value in the parameters:
   * textStatus = "error"
   * errorThrown = "INTERNAL SERVER ERROR"

**Comment by hyi** [comment] 2015-12-14 17:56
@mauriel133 This issue may be caused by the missing solr index update piece. I have already set up a cron job to be run every midnight to update solr index to make new resources created during the day discoverable from discovery page, but you will not be able to see the new resources created discoverable until the next day. I will investigate on-demand solr index update next after AGU, but this issue you outlined here may prompt us to set solr update index background job to run more frequently than once each midnight? Bringing in @alvacouch and @dtarb into loop to get their input.

**Comment by hyi** [comment] 2015-12-14 18:06
@mauriel133 @alvacouch @dtarb On the other hand, apart from newly created resource cannot be discovered from discovery page, internal server error can still be fixed without on-demand solr index update when adding a resource to My Resources from resource landing page. If you can reproduce this error in your local development environment, can you see a more informative debug error message other than "internal server error?"

**Comment by mauriel133** [comment] 2015-12-14 18:12
For the issue trying to add the resource to My Resources, all the information I could gather is posted above. 

The original issue of labels not persisting after page refresh, I still haven't found a way to reproduce it in my local environment.

**Comment by hyi** [comment] 2015-12-14 20:01
@mauriel133 I can reproduce the label refresh issue in my local dev environment. Please use hsproxy irods account as set up by default in local_settings.py in our codebase and download http://distribution.hydroshare.org/public_html/www.deploy.sql to your hydroshare directory, and change the line to "HS_DATABASE: www.deploy.sql" in config/hydroshare-config.yaml to deploy in your local dev env. Then you should be able to reproduce the issue in your local dev env, i.e., discover a resource, then add it to my resources, then label it, then refresh the page, then the label is gone.

**Comment by pkdash** [comment] 2015-12-14 22:26
@mauriel133 and @hyi I think I found the bug. If you look at this line (https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/__init__.py#L491) it is missing the ```discovered_resources``` in the for loop.

**Comment by mauriel133** [comment] 2015-12-14 22:28
Good job! Can you make a PR for this and have @hyi deployed it on beta for testing?

**Comment by pkdash** [comment] 2015-12-14 22:31
Will do.

**Comment by mauriel133** [comment] 2015-12-15 00:42
Confirmed fixed on beta and www.

**Closed** 2015-12-21 21:26 UTC
Labels: bug, in progress
