### ISSUE TITLE
My Resources page scrolling

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#908] opened 2016-01-26 00:42 UTC
A change has crept into the My Resources page scrolling that is in my opinion a regression.  I do not recall there being an issue to change the scrolling of the My Resources page.  

As presently deployed on Alpha.hydroshare.org My Resources are displayed in a box that limits the space that they can take up and they have their own scroll bar.  This makes it clumsy to find resources in a long list.
![new](https://cloud.githubusercontent.com/assets/3456833/12569314/e17a447a-c38a-11e5-9cfb-ae495f08750b.png)

The current www.hydroshare.org deployment is much better in my opinion.
![old](https://cloud.githubusercontent.com/assets/3456833/12569316/e90184e2-c38a-11e5-9fa1-ecb96387f40a.png)

**Comment by mauriel133** [comment] 2016-01-26 01:59
This was the 4th step outlined in this issue: https://github.com/hydroshare/hydroshare/issues/770

I will undo it tomorrow.

**Comment by horsburgh** [comment] 2016-01-26 03:11
@mauriel133 - what I was hoping for with the scrolling is not that you would implement a fixed height box within which the resource list would scroll, but rather that the box would take up the whole space available to it on the page.  So, where Dave has labeled "Useless wasted space", you should just extend the scrolling list to the border of the footer.

We definitely need to have a scrolling mechanism for when the list gets longer than the length of a page on the screen. We want to keep the filters and search bar where they are at on the page. When one scrolls down the list of resources, the facets and search box should stay where they are and not scroll off the top of the screen so you can no longer see them.

**Comment by mauriel133** [comment] 2016-01-27 18:12
@horsburgh, @dtarb the new scrolling behavior can be tested at https://riverdev.hydroshare.org/

**Comment by horsburgh** [comment] 2016-02-06 19:42
From @dtarb: When I go to the My Resources page I get two vertical scroll bars. One just for the resource listing box and one for the whole page. However if I resize my browser window to be wider or narrower (it works both ways) the internal scroll bar disappears and all resources are shown.

I would actually prefer to always get the display without the internal scroll bar.

**Comment by horsburgh** [comment] 2016-02-06 20:01
@dtarb - this issue is a bit complicated. @mauriel133 is trying to keep a page styling that is responsive in web browsers and on mobile devices.  When you make the window very narrow (as would be the case in a browser window taking up less than half your screen or on a mobile device) the filters flip to the top of the table of resources, and the footer compresses in width, which makes it longer.  So, the whole page has to scroll if you want to see everything.

At the same time, @mauriel133 has put the list of resources within a container that is capable of scrolling. This is so that when you have a long list of resources the filters don't disappear off the top of the page when you scroll the list of resources.

After studying this a bit, I'm seeing three options:

1. Leave it how it is. It seems to work OK in both web browsers and mobile browsers.  I'm not seeing the issue with the vertical scroll bar disappearing in @mauriel133 's latest implementation on riverdev.hydroshare.org.  But, his latest implementation does need a small tweak so the table always extends all the way to the footer when the filters flip from the top of the table back to the left side of the table.
2. Take the list of resources out of the container and render the whole list on the page.  The whole page will scroll and the filters will remain at the top and scroll off the top of the page when you scroll down.  The page may take longer to load if there is a long list of resources because you are rendering the whole table of resources every time you load the page.
3. Fix the height of the page to the browser window so the page does not scroll, fix the filter facets to the left side of the page, make the footer much smaller and anchored at the bottom of the page, and then fill the rest of the page with a scrollable list of resources (see how Google Drive manages their page and table). But, this would not be responsive on a mobile device browser.

My preference would be number 1.

**Comment by dtarb** [comment] 2016-02-06 20:42
My preference is number 2 with an option as is common on these lists on shopping sites (I looked at Amazon, Orbitz, Expedia) to have at the bottom showing page x of y and an option to set how many to display if you are concerned about loading time and the length of scrolling on small screens.  I do not like number 1 because two scroll bars nested seem like poor interface design and when I use the scroll wheel on the mouse the behavior as to which scroll bar it relates to is non intuitive.  I think that nesting the container is the extra complication that is making it complicated.  At the sites I mentioned above there are actually not headers at all on the entries.  Our listings of resources in our profile pages Contributions and Overview tabs also do not have headers at all, so perhaps we should consider dispensing with the headers and having a single sort by dropdown for the listing (which Amazon, Orbitz, Expedia all use).  There is also an attractiveness to having the same resource entry appearance on all pages.  Right now we have 4 different listings on each of My Resources, Discover, Profile Overview and Profile Contributions.  

I verified that #936 is "fixed" on Riverdev deployment.

**Comment by horsburgh** [comment] 2016-02-06 20:46
I'm trying to get away from paging.  I don't like it and it isn't always obvious that it's an option.  Plus, it's impossible to use on a small (mobile) screen.

**Comment by dtarb** [comment] 2016-02-06 21:12
Amazon, Orbitz, Expedia, Google, Bing, zions bank (among others) use paging.  How many more mainstream websites do you want me to list to convince you that it is mainstream?  I can not find another mainstream site that has nested scroll bars.

**Comment by horsburgh** [comment] 2016-02-06 22:00
My mom always told me I shouldn't do things just because everyone else is doing them.   ;-)

I personally hate paging. I'm sure I could give you as many examples of websites that don't use paging. For example - Google Search does use paging, but Google drive (which is much more similar to our My Resources page) does not.

Don't we have more pressing issues to deal with?

**Comment by dtarb** [comment] 2016-02-06 22:27
We certainly do have more pressing issues to deal with.  The page was fine before the container was added.  I do not know why it had to be complicated by adding it.

**Comment by horsburgh** [comment] 2016-02-09 22:58
@dtarb - @mauriel133 and I just discussed this.  He's going to revert back to the way the page was before. The whole table of resources will be rendered when the page loads. The whole page will scroll (with one scroll bar). The controls will scroll off the top of the page, but there will be an arrow button that shows up when you have scrolled down that will take you back to the top. This will be responsive in both web browsers and mobile browsers, and it shouldn't be any slower.  Should be a quick fix.

**Comment by dtarb** [comment] 2016-02-09 23:02
Great.  Thanks.

**Comment by mauriel133** [comment] 2016-04-06 17:51
Is this still an issue?

**Comment by horsburgh** [comment] 2016-04-06 18:03
I think this has been reverted and deployed to www. @mauriel133 - if you can verity this, I will close.

**Comment by mauriel133** [comment] 2016-04-06 18:22
I just tested for Chrome, Firefox and IE and it works as intended. Could you test on Safari?

**Comment by horsburgh** [comment] 2016-04-06 19:51
Tested successfully in Safari on www. Closing.

**Closed by horsburgh** 2016-04-06 19:51 UTC
Labels: in progress
