### ISSUE TITLE
Unexpected results when I search for Model Instance resource in the search box

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#1143] opened 2016-04-21 03:32 UTC
If I search for "model instance resource" in the search box I get the following results:

![image](https://cloud.githubusercontent.com/assets/5543781/14697232/e338f870-074f-11e6-89f2-a6f42844d840.png)

however, if I search for just "model instance" in the search box I get the following results:

![image](https://cloud.githubusercontent.com/assets/5543781/14697271/24483ede-0750-11e6-8de6-6bb46a4d8fd6.png)

**Comment by xuezhaokun** [comment] 2016-04-21 04:00
It is caused by a SOLR index issue. For resource type, I am trying to index the resource type's verbose name which could cause these two search issue. If I just index on resource_type property, when you want to search "model instance resource", you have to do "ModelInstanceResource". Trying to find a better way to solve it. @alvacouch Do you have any suggestion for this issue?

**Comment by xuezhaokun** [comment] 2016-04-21 04:13
Is there any way I can get the resource type verbose name based on "resource_type" property?

**Comment by alvacouch** [comment] 2016-05-02 13:56
@xuezhaokun 

I have a strange response for you. When searching for "resources", "resource" is actually a stopword. It adds nothing to search results. So, adding "resource" to stopwords.txt in SOLR would actually address the issue....!

At a deeper level, If you have a resource object  r, then 

`r._meta.verbose_name`

is what you want. 

If you just have a model type name, then you're stuck, because we need **both a model type and an app name** to fetch the model, to wit: 
```
from django.db.models.loading import get_model
verbose = get_model(app_name, resource_type)._meta.verbose_name
```

Most -- but not all -- resource models have their own apps. And **we didn't write down the app name** in the resource metadata..

**Comment by hyi** [comment] 2016-05-16 14:29
@xuezhaokun Please close this issue if it has been resolved.

**Comment by xuezhaokun** [comment] 2016-05-16 14:35
@hyi @mohamedmorsy I think this one is resolved. We can close it.

**Closed** 2016-05-16 14:43 UTC
Labels: Discovery
