### ISSUE TITLE
Bag zip files for large resources cannot be cleanly unzipped

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2661] opened 2018-03-04 00:13 UTC
This was reported by a user for this resource https://www.hydroshare.org/resource/9badb941303d4813b3c398cdab038368/

I was able to to reproduce the user's problems.  I copied the bag resource to my iRODS zone.  The resulting zip file (9 GB) was too big to download over the internet.  Downloading via iRODS then attempting to unzip on a PC I get the following errors
![image](https://user-images.githubusercontent.com/3456833/36940701-06f24e7c-1f06-11e8-97b0-c6c4d77109e5.png)
![image](https://user-images.githubusercontent.com/3456833/36940703-0fbcf908-1f06-11e8-85c4-c008f1024155.png)

More details of what I did are in https://docs.google.com/document/d/1XCYVzaOFI2P9innJ2KITfQiw3MIj4CmDLFjjCYB3xRI/edit#

**Comment by alvacouch** [comment] 2018-03-07 17:33
There is a testbed available now at https://cuahsi-dev-2.hydroshare.org/cache/bags . Feel free to 

1. Choose your favorite browser and platform. 
2. Download one of the files there (all public). 
3. Unzip using your favorite unzipper. 
4. Report any problems here.

**Comment by alvacouch** [comment] 2018-03-07 17:34
@dtarb My evidence is that the windows native unzip cannot handle large zipfiles and reports **erroniously** that the file is invalid. 7zip does unzip these files.

**Comment by dtarb** [comment] 2018-03-10 12:55
I did some testing and reported results in the spreadsheet https://docs.google.com/spreadsheets/d/11ZhrhZ1OqgXgnFkvKceE1pP6kcuoNPldhJKFRhhhWzo/edit#gid=0.

Downloading seems to be working fine over both Chrome and Firefox
- Can download the 37 GB file obtained from a 3rd party 
- Can download all the HydroShare bags I tried 
- Times are size related and comparable to my experience at other sites

Unzipping
- Can unzip the 37 GB file obtained from a 3rd party using both native windows and 7zip
- Cannot unzip HydroShare resource files larger that 4 GB using native windows
- Unzipping HydroShare resource files smaller than 4 GB using 7zip generates warning "There are some data after the end of the payload"
- Unzipping HydroShare resource files larger than 4 GB using 7zip generates two warnings: "32-bit overflow in headers" and "There are some data after the end of the payload"

**Comment by ChristinaB** [comment] 2018-03-29 21:23
@rayi113 Do we have an update on how to download large files?      
For example, I am getting errors downloading this 3G zipped file
https://www.hydroshare.org/resource/ec518c49772b420b97047f7482ae92aa/

Also, the help page labeled 'Uploading/Downloading large files to/from HydroShare.' does not actually contain information on Downloading and likely should also be informed by how this issue is resolved.

**Comment by rayi113** [comment] 2018-04-13 17:54
iRODS ibun problem associated with https://www.hydroshare.org/resource/9badb941303d4813b3c398cdab038368/ have been reproduced by iRODS development team, cause identified, fix verified.  Fix to be part of iRODS 4.2.3 release that should occur before June 2018.  hydroshareZone will have to be upgraded to iRODS 4.2.3 at that time, and all bag_modified flag for all HydroShare resources reset to cause recreation of all hydroshare bags.

**Comment by dtarb** [comment] 2018-05-08 19:38
@rayi113 has reported that this requires an iRODS update once iRODS has fixed the issue.  @rayi113 please schedule an iRODS update at a good time, then when this issue is fixed, close the issue.

**Comment by rayi113** [comment] 2018-06-02 23:27
iRODS 4.2.3 is officially released, so this upgrade can now take place, see: https://irods.org/2018/05/irods-4-2-3-is-released/

**Comment by dtarb** [comment] 2018-06-02 23:52
Great.  Can the sysops team please work out a schedule for doing this.  As we have done in the past, I would prefer and iRODS release to be separate from any Django code release, so that if there are problems the cause is isolated.  I suggest that with 1.16 exact contents still being worked on, that we consider an iRODS update before the 1.16 deploy.  Could we do (1) the iRODS update to beta in the next week or so.  Put it through testing, then do (2) an update to www once satisfied.  Then (3) cut the 1.16 beta with new Django code.

**Comment by dtarb** [comment] 2018-07-18 22:29
I created a new resource on beta.hydroshare.org that has a new iRODS.  However for both and existing and newly created resource I tested I get the following errors when unzipping a downloaded bag.  This suggests to me that the new iRODS has not resolved the zipping problem that it was supposed to.

![image](https://user-images.githubusercontent.com/3456833/42911301-b80f24a2-8aa7-11e8-9237-dd85c1683504.png)

**Comment by hyi** [comment] 2019-09-11 13:59
@dtarb I just tried to download a bag of my resource on www.hydroshare.org, and I have no problem to unzip it on my windows pc with no warnings. Can you try again to see if you still run into issues or not when you have a chance? Our current iRODS server version is 4.2.6.

**Comment by dtarb** [comment] 2019-11-17 00:09
@hyi I just downloaded the bag for this resource https://www.hydroshare.org/resource/a270f893d7cd4a0f9bf98af40ea5eaa2/ which is 5.2 GB.  I get the warning below on my laptop with 7zip
![image](https://user-images.githubusercontent.com/3456833/69000926-b0581a00-0893-11ea-8c3d-53a3ad87ad35.png)

**Comment by hyi** [comment] 2019-11-18 14:29
@dtarb This warning looks like an issue with 7zip. See this post: https://superuser.com/questions/1153751/what-does-there-are-some-data-after-the-end-of-the-payload-data-mean

**Comment by dtarb** [comment] 2019-11-19 13:27
@hyi.  There is something different about the big bags/zip files that come from HydroShare.

If I download the bag for this resource https://www.hydroshare.org/resource/a270f893d7cd4a0f9bf98af40ea5eaa2/ which is 5.2 GB, I get the warning mentioned above.  If I attempt to unzip using Windows I get
![image](https://user-images.githubusercontent.com/3456833/69149124-09da6780-0a93-11ea-8e8b-22157bb6abba.png)

However if I download a different 39 GB zip file that was created somewhere else, from https://www.hydroshare.org/resource/165e2c3e335d40949dbf501c97827837/ (the second link in the abstract), both Windows and 7Zip can unzip this cleanly.

These are the same symptoms reported in May 2018.  I do not think you can blame it on 7Zip, when it is also a problem for Windows Zip and 7zip and Windows Zip can both accommodate a 39 GB zip file from another source.

**Comment by hyi** [comment] 2019-11-19 14:43
@dtarb I tried to unzip this resource bag using unzip utility on my linux and it gave me the following warning too although it can unzip the bag successfully:
```
warning [a270f893d7cd4a0f9bf98af40ea5eaa2.zip]:  4294967296 extra bytes at beginning or within zipfile
```
which is similar to the warning given by 7zip. It looks like 7zip and unzip utility are tolerant to this warning and can proceed with unzipping successfully while windows unzip does not. I'll contact Terrell about this and see what he says.

**Comment by hyi** [comment] 2019-11-19 16:57
@dtarb I have just received Terrell's response as below:
--------------
I think we've probably already fixed this - it seems very similar to the scenario we reproduced and solved in 4-2-stable.     Happy to get you an engineering build if you want to test it out with the latest code.   4.2.7 didn't get released before SC19.   But perhaps the week we get back.   It's very close.
--------------
I'd say just to wait until 4.2.7 comes out, then we will test this as well as another big file unzipping ibun issue. Let me know if you think otherwise.

**Comment by dtarb** [comment] 2019-11-20 04:39
I agree to just wait for 4.2.7

**Comment by hyi** [comment] 2020-02-04 18:30
@dtarb I have manually run ibun command on beta to force regeneration of the bag zip file for this big resource https://beta.hydroshare.org/resource/a270f893d7cd4a0f9bf98af40ea5eaa2/, then retrieved the newly generated zipped bag file and unzipped it cleanly without any warning using unzip utility on my linux (it gave me a warning as detailed above in the older iRODS version 4.2.6), so I believe this issue has been fixed. Can you verify it on beta for this resource: https://beta.hydroshare.org/resource/a270f893d7cd4a0f9bf98af40ea5eaa2/ to see if it is indeed fixed? This is a published resource, the resource bag has to be regenerated in order to fix it on production after iRODS is upgraded there.

**Comment by dtarb** [comment] 2020-02-29 18:30
@hyi I tried to test this issue but ran into other possibly other unrelated problems.  

1. Downloads of large bags seem to take unnecessarily long.  A 5 GB bag download takes 2 hours (but downloading a 4.3 gb file from a windows server to the same PC over the same internet connection I am using takes 18 min).
2.  I wanted to create a new resource bigger than 4 GB by loading files from iRODS.  I ran into #3776
3.  On www I created a resource https://beta.hydroshare.org/resource/b34c6a9d9295475981cc644134deb014/ but when I tried to download a bag got this
![image](https://user-images.githubusercontent.com/3456833/75613059-b1c9ed00-5ae6-11ea-8389-075cc97c38bf.png)

**Comment by dtarb** [comment] 2020-02-29 18:52
I was unable to share the problem resource https://www.hydroshare.org/resource/549fc78936334b508b11cb0b1ca89abe/ mentioned above with developers because of #3534.

**Comment by trel** [comment] 2020-03-02 01:26
The fix for files >4GB included in 4.2.7 handled both https://github.com/irods/irods/issues/4495 and https://github.com/irods/irods/issues/4118.

**Comment by dtarb** [comment] 2020-03-10 15:52
I received the following error from a small bag downloaded today
![image](https://user-images.githubusercontent.com/3456833/76331445-c9f2f680-62b4-11ea-8e32-5106f1456bf9.png)

**Comment by hyi** [comment] 2020-04-03 17:12
@dtarb I suspect this zipped bag for this small resource may be generated before iRODS upgrade. Could you try to update the resource metadata to get the resource modified flag set to True so that when you download this bag, the zipped bag can be regenerated by the upgraded iRODS? If the problem persists, I'll look into it further if you could put the resource id for this small bag here (when I manually typed in this 32 digit number following what is in the screenshot, iRODS tells me it does not exits. I am not sure whether it is worthwhile to regenerate existing bags holistically by upgraded iRODS since this problem does not seem to be widespread, so it may work better to deal with it on a case-by-case basis.

**Comment by dtarb** [comment] 2020-04-20 01:19
@hyi I think I had deleted the resource illustrated, but I just created a new one and the error still persists
![image](https://user-images.githubusercontent.com/3456833/79705320-80fa6e80-8272-11ea-88fe-f04dda5c8692.png)

The fact that I created a new one means that the bag has to have been created using the most recent code.

The resource is https://www.hydroshare.org/resource/5c9b831d47af47f197253a227f3e3a5c/

**Comment by dtarb** [comment] 2020-04-24 03:46
@hyi I was able to obtain a download of a large (5 GB) resource after the upgrade this week, and the warning of data after the end of the payload data still persists
![image](https://user-images.githubusercontent.com/3456833/80173035-d654b980-85ab-11ea-9087-93f830220a08.png)

**Comment by hyi** [comment] 2020-04-24 14:52
@dtarb I downloaded the bag for this small resource: https://www.hydroshare.org/resource/5c9b831d47af47f197253a227f3e3a5c/ and can unzip it with 7 zips without any warning. I also tried to use unzip utility on linux to unzip this bag and it does not give my any warning although before the fix unzip utility did give a warning as you see to another problematic resource. So I cannot reproduce the warning issue you see. Let me check with Scott to see if he can reproduce the warning issue just to have an another pair of eyes in case I missed something.

**Comment by sblack-usu** [comment] 2020-04-24 16:22
I also see the warning.  I downloaded the bag @hyi linked above.  and opened the zip file in parser mode with 7zip.  this allows me to see what the data is at the end of the payload (it's the file named 2 in the display).
![image](https://user-images.githubusercontent.com/35820390/80232566-5a418c80-8612-11ea-8b5c-469b8a4e66de.png)
I extracted those bytes and opened it.  It appears to be 5 kb of the null character.
![image](https://user-images.githubusercontent.com/35820390/80232935-eeabef00-8612-11ea-8bc0-0f58d6ce3e31.png)
I'm not sure if it's worth spending much more time on this as most compression tools just ignore the extra payload when decompressing, and the 7zip is just displaying a warning without affecting the result.

If we were to continue investigating, I'd suggest downloading the zipped file directly with scp instead of the web service and try extracting and see if the bytes are still there.  Googling suggests that web services can append these bytes when transferring the files.  Nothing I found was very clear or convincing.

**Comment by hyi** [comment] 2020-04-24 17:05
@sblack-usu Thanks for looking into it. I can now see the warning as well. I will investigate a bit further to see if the null ends are generated by iRODS or added by web service.

**Comment by hyi** [comment] 2020-04-24 17:32
@dtarb @sblack-usu I verified the zip files created directly from iRODS caused this warning in 7 zips. I used to see similar warnings using unzip utility command in linux, but now I don't see it any more, although 7 zips still report the warning. I will report it in iRODS issue tracker and we will just have to keep track of it for now. This applies to all zipped bags, not only for large bags.

**Comment by hyi** [comment] 2020-04-24 18:18
@dtarb @sblack-usu Before I create an iRODS issue tracker, I want to know whether we can reproduce this warning using any unzipping tools other than 7 zips. I remember I used to see the warning with unzip utility in linux in addition to 7 zips, and now that issue has been fixed by iRODS, so now I don't see warnings in linux unzip utility. Googling indicates there are multiple scenarios this warning happens in 7 zips mainly due to 7 zips bugs, so I think we need to show this warning happens in other unzipping tools as well beyond just 7 zips.

**Comment by dtarb** [comment] 2020-04-25 13:14
I do not know of any utility that results in this warning other than 7-Zip.  

It is a warning and we could ignore.  I do not think we can/should spend much HydroShare development time on this.  We have probably spent too much already, and this appears to be something we can not do anything about.

The original problem included an error and a warning, and the error part appears to have been fixed.

Scott's investigation above appears to indicate that there is data appended, and this appears to originate from the zipping being done in iRODS, and this generates the warning.  The iRODS team should at least be made aware of this as @trel asserted above that an iRODS release fixed this.  If iRODS team is able to do anything about this is beyond our control, and it is for them to decide if concern over iRODS zipping leaving data after the payload that generates warnings is something they want to address.  Once they know about this, I am happy for this issue to be closed.

**Comment by trel** [comment] 2020-04-25 18:16
This relatively recent post suggests that newer/newest versions of 7Zip do not emit this warning anymore... https://appuals.com/fix-there-are-some-data-after-the-end-of-the-payload-data/

> A 7-Zip bug – The “There are some data after the end of the payload data” warning message on every extraction attempt is a known issue with 7Zip, but only on older builds. The issue is known to occur with build 16.02 and older builds. Although the developers haven’t really explained the issue, users speculate that it’s related to using the RAR encryption on certain types of data. In the latest builds of 7Zip, the issue has been addressed by the developers of the extraction utility.

The second suggestion is to change the file suffix from `.zip` to `.rar` and see if 7Zip still gives the warning.

**Comment by hyi** [comment] 2020-04-25 22:28
@trel I came across that post as well and tried both suggestions of upgrading 7-zips to the latest version and changing ```.zip``` to ```.rar```, but still got the warning. I'll defer to you whether it is something iRODS team is interested in investigating further, but since we only see this warning in 7-zips and it does not prevent unzipping in any way, I'd suggest to close this issue for now. @dtarb

**Comment by trel** [comment] 2020-04-26 00:37
Ah, very good - okay.   We'll read up a bit more and look into making sure we're holding libarchive the 'correct way' to create these archive files.   I think closing this issue is correct for now.

**Closed** 2020-04-26 12:41 UTC
Labels: High Priority, bug, iRODS
