### ISSUE TITLE
Unnecessary Title Creation Dialog

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#3549] opened 2019-08-22 21:11 UTC
When users create a resource, they are prompted for a title, then given the chance to edit it. Can skip the initial extra prompt and go right to resource creation, where a Cancel button should be available:

![image](https://user-images.githubusercontent.com/45397838/63550086-e3427a00-c4ff-11e9-9846-0e56a8553f34.png)
Skip this dialog

**Comment by horsburgh** [comment] 2019-08-22 21:16
We added this dialog on purpose because as things currently work, once you get to the resource editing page the resource has already been created on disk. This was a way to avoid the creation of a bunch of empty resources.

**Comment by dtarb** [comment] 2019-08-23 12:26
I agree it would be cool to avoid the title prompt and go straight to the landing page.  When @sblack-usu implemented this, he and I wracked our brains about how to do this, and this was the best solution we came up with.  If there is another way that will quickly get to the landing page in edit mode without creating a resource until a user actually adds content, then that would be better.

**Comment by cuahsimarko** [comment] 2019-08-23 15:53
Ok I'll have a look and check back.

**Comment by cuahsimarko** [comment] 2019-10-14 16:48
Related to https://github.com/hydroshare/hydroshare/issues/3415

**Comment by cuahsimarko** [comment] 2021-02-01 20:41
Note to developer (or me if participating in design) https://github.com/hydroshare/hydroshare/issues/3415 ensure there are no backend remnants as a part of canceling resource creation.

**Comment by martinseul** [comment] 2021-02-22 19:13
Upon review with the group, this is as designed closing

**Closed by martinseul** 2021-02-22 19:13 UTC
Labels: Resource Landing Page, USER INCONVENIENCE, design phase needed
