### ISSUE TITLE
Web app connector URL patterns pass invalid characters

### ISSUE THREAD

**Issue by kjlippold** [hydroshare/hydroshare#3513] opened 2019-08-06 20:30 UTC
Some of the URL patterns for web app connectors will pass invalid characters to URL query params. The most notable ones are HS_FILE_PATH and HS_AGG_PATH which will pass forward slashes from the file paths to the URL query param if the aggregation is located in a subdirectory. HS_FILE_NAME and HS_MAIN_FILE can also potentially pass invalid characters from file names to the URL query params.

**Comment by Maurier** [comment] 2019-09-28 13:31
@sblack-usu - Is this addressed by https://github.com/hydroshare/hydroshare/pull/3584/files?

**Comment by sblack-usu** [comment] 2019-09-30 14:46
no, this is a separate issue.

**Comment by dtarb** [comment] 2021-02-12 19:48
@sblack-usu is this still an issue.  Do you have a recommendation for how/whether to address this.

**Comment by sblack-usu** [comment] 2021-03-25 17:03
and this will have to be done on the frontend for some scenarios.

**Comment by cbcunc** [comment] 2021-11-16 14:36
Reference PR #4347

**Comment by sblack-usu** [comment] 2022-01-13 20:45
After trying to debug what the effects of this patch on jupyterhub (with @aaraney), we learned that a forward slash does not need to be URL encoded in a query parameter.

https://en.wikipedia.org/wiki/Percent-encoding#Reserved_characters

It only needs to be encoded if in a path parameter
>In the "query" component of a URI (the part after a ? character), for example, / is still considered a reserved character but it normally has no reserved purpose, unless a particular URI scheme says otherwise. The character does not need to be percent-encoded when it has no reserved purpose. 

So... what is the original issue that prompted the creation of this issue?  @kjlippold @dtarb @pkdash

**Comment by aaraney** [comment] 2022-01-13 21:00
I just tracked down the log message. The issue has to do with `nbfetch`. Specifically,  `jinja2.exceptions.TemplateNotFound: hstatus.html` in the [`nbfetch.handlers.HSHandler.get`](https://github.com/hydroshare/nbfetch/blob/ec3fce949bcb4655673c1cf4a2356f3d5d3f15aa/nbfetch/handlers.py#L395) method.

**Comment by dtarb** [comment] 2022-01-16 21:58
I do not know what the original issue was.  Mentioning @danames in case @kjlippold is not able to respond.

**Comment by danames** [comment] 2022-01-18 18:23
I believe that the issue is that HS_FILE_PATH and HS_AGG_PATH can potentially pass strings that have forward slashes or other symbols which are legal in a file path but illegal as URL query string parameters. @sblack-usu it looks like you tested this a bit. Do you know how other web services handle such encodings? I assume that they use url codes like %20 in place of the actual characters. @dtarb I think we need to leave this issue open until it is figured out.

**Comment by sblack-usu** [comment] 2022-01-18 18:31
The ticket is asking for url encoded forward slashes in the query parameters.  That is something that is not necessary for query parameters, it is not a bug. 

I'd like to know what prompted this issue to be created before I close this to help resolve the root problem.

**Comment by pkdash** [comment] 2022-02-01 22:06
@sblack-usu There seems to be potential other issues with encoding of web app launch url. Here are some examples:

App URL pattern: `https://www.hydrolearn.org/${HS_RES_ID}/${HS_AGG_PATH}`

For the above pattern, HydroShare generates this: `https://www.hydrolearn.org/49a9db8fc3c74e93b68b9b7d9546d76e/folder-with-space/netcdf_valid.nc`
The actual aggregation path: `folder with space/netcdf_valid.nc`

App URL Pattern: `https://www.hydrolearn.org/${HS_RES_ID}?aggr-path=${HS_AGG_PATH}`

For the above pattern, HydroShare generates this: `https://www.hydrolearn.org/49a9db8fc3c74e93b68b9b7d9546d76e?aggr-path=folder with space/netcdf_valid.nc`

**Comment by dtarb** [comment] 2022-04-21 17:21
@pkdash it seems your Feb 1 comment is outlining a separate issue.  If that is the case, and since we have not heard specifics from @kjlippold , I suggest this issue be closed and the new items you raised be put in a new issue.  If there are still issues related to this issue, @kjlippold or @danames could re-open.

**Comment by dtarb** [comment] 2022-07-08 17:05
See #4693.  If it has been closed it means this issue is ready to be closed too.

**Closed** 2022-08-11 15:13 UTC
Labels: bug, Resource Model, Web App Connector, Resource Landing Page
