### ISSUE TITLE
Zip files created in Hydroshare cannot be unzipped

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4752] opened 2022-08-30 03:53 UTC
**Description of the bug**
When a zip file is created in Hydroshare, the same zip file can't be unzipped.  The issue seems to persist, across zip/file naming, file types, file sizes, and whether or not there are unzipping collisions.  The error message is non-descriptive and doesn't help the user.  

Steps to reproduce the bug:
https://user-images.githubusercontent.com/43424907/187345303-9e5f086a-fd6f-4989-bc59-e7a3e5d9e7c7.mov

**Expected behavior**
Zipped files are unzippable (either the issue with zipping or unzipping is fixed to avoid errors.

**Additional information**
Chrome 104.0.5112.101

**Comment by devincowan** [comment] 2022-08-30 13:01
PR https://github.com/hydroshare/hydroshare/pull/4751 seems to (at least partially) fix this issue.

**Comment by hyi** [comment] 2022-08-30 13:37
I tried to reproduce this issue on beta but everything works for me as expected, so I cannot reproduce this issue. As shown in the video, I followed the same workflow by first downloading zipped for the zip file, then unzip the first time, it succeeded, then after I tried to unzip the same zip file again,  I got unzip failed and Select whether to allow file override link right after the "unzip failed." in the notification popup as expected, yet in Neal's video, that whether to allow file override link is not displayed. I am not sure what is going on, perhaps related to Selenium testing which somehow could not get the whether to allow file override link displayed or something. Anyway, everything works for me as expected on beta and I cannot reproduce this issue. @devincowan @ndebuhr See whether you can manually reproduce this issue on beta.

**Comment by devincowan** [comment] 2022-08-30 13:54
I can confirm being able to reproduce this issue. Examples of resources that I used are here for you @hyi 
https://beta.hydroshare.org/resource/8fee1c9555f64bca88db00a5020a0553/
https://beta.hydroshare.org/resource/d95a79e854864ca1bbbb5772e3f67054/
Attempting to unzip the "devin_test.zip" in either of those resources will fail

**Comment by hyi** [comment] 2022-08-30 15:39
Yes, it is definitely filename collision. However, this is handled by showing up a whether to allow file override link after unzip failed message in the notification popup, once clicked, a dialog should be displayed asking users whether to override those files with filename collision. For some reason, this whether to allow file override link is not shown in Neal's test. I cannot reproduce this issue in my local development environment, so trying to figure out which workflow could have caused this whether to allow file override link not showing.

**Comment by devincowan** [comment] 2022-08-30 15:41
@hyi I can reproduce on my local dev with rc-1.58 checked out. Just rebuilt the containers to make sure nothing fishy with same result.

**Comment by hyi** [comment] 2022-08-30 17:01
@devincowan Thanks for the info. Will checkout rc-1.58 and rebuild HydroShare trying to reproduce it since with my current develop branch in my local development environment I cannot reproduce it.

**Comment by hyi** [comment] 2022-08-30 21:12
This issue only occurs when adding the zip file of the file created via "download zipped" which put the file into a folder with the same name as the file. For example, the resource contains a file named ```test.txt``` and when downloading zipped for this file from HydroShare, HydroShare creates a zipped file named ```test.txt.zip``` that contains a root folder named ```test.txt``` which includes the file named ```test.txt```. When unzipping this zipped here to the same folder that contains the file named ```test.txt```, the folder with the same name ```test.txt``` cannot be created since a file with the same name existed, which is the root of this issue. This folder name overriding a file name case has not been handled properly in the unzip here without creating an extra folder work which I am looking into how to best handle it. Want to provide an update here. It looks to me putting the single file into a folder named with the single file name in the zip file being created from the ```Download zipped``` action is confusing and most likely will not be the desired behavior for the user, but a folder name overriding a file with the same name needs to be handled in the unzip here work regardless. I am looping in @devincowan and @pkdash who have tried to help me reproduce this issue.

**Comment by hyi** [comment] 2022-09-12 15:21
@hydrocheck Tested it out on production. This issue appears to be fixed. Can you close the issue if it also works for you on production?

**Comment by hyi** [comment] 2022-09-12 15:30
@hydrocheck I am closing it as decided at the developer coordination meeting. Feel free to reopen it if you still see the issue.

**Closed by hyi** 2022-09-12 15:30 UTC
Labels: bug
