### ISSUE TITLE
Composite File type FileSet doesn't work properly

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3634] opened 2019-10-24 14:37 UTC
Resource 665dfa6aee8d4689ab59def52b3b1179/ is the only available instance of `FileSet` as of two weeks ago, and is badly corrupted. Most folders and files are listed twice. This means that their Django representations are likely corrupt.

**Comment by alvacouch** [comment] 2019-10-24 14:38
Shouldn't I add a `unique` constraint onto the filenames and folder names for a resource?

**Comment by dtarb** [comment] 2019-10-25 12:27
@pkdash can you take a look at this.

**Comment by pkdash** [comment] 2019-10-25 13:47
@dtarb I can take a look at this. When I go to the landing page of this resource (665dfa6aee8d4689ab59def52b3b1179), it seems it has three types of aggregation:
![image](https://user-images.githubusercontent.com/2523434/67575743-3789f600-f70b-11e9-8f0b-3880b98875d9.png)
 However, these aggregations are not getting displayed in the content browsing area. It only shows these files:
![image](https://user-images.githubusercontent.com/2523434/67575877-7a4bce00-f70b-11e9-96a7-73477d2759b4.png)

So there is obviously a problem of not getting the aggregation information from the backend to the frontend. However, I don't see the issue of folders and files getting listed twice. Are these duplicate listing applies to the downloaded bag? 

I assume you created this resource. Do you remember seeing the aggregations ever in the content area?

**Comment by dtarb** [comment] 2019-10-25 14:02
This resource was created by Irene.  She made me an owner.  She was trying to create a resource with different composite types in it but unzipping and auto aggregation was failing so she ended up deleting the content aggregations and just leaving the zip files.  I do not know if she ever saw aggregations in the content area.  You could ask her at i.garousi@aggiemail.usu.edu.  She created another resource after some of the problems had been resolved, but left this resource as an example of the problems for developers to try figure out what went wrong and how to fix.  @sblack-usu has been working on check resources and fix resources scripts, so it may be good to hear from him on the status of these and coordinate any investigation.

This resource is not important to us and can be deleted if/when problems are resolved, but at present is kept as an example of the problems.

**Comment by pkdash** [comment] 2019-10-25 15:02
It seems for this specfic resource there are resource files in Django DB which doesn't exist in irods. The content types displayed on the landing page in summary section are based on the files on DB. The content types/aggregations displayed in the file browsing area are based on files that exist both in irods and DB. If we can delete the resource file records in db that doesn't exist in irods for this resource, we can get this resource to a clean state.

**Comment by pkdash** [comment] 2019-10-25 20:40
Another look into the code base suggests that this resource has hanging logical file object (no resource file or folder association) records in Django DB rather than resource file mismatch between irods and Django DB as I mentioned in my earlier comment.

**Comment by sblack-usu** [comment] 2019-10-28 23:06
yes, this resource has the hanging files caused by the aggregation task failing.

**Comment by dtarb** [comment] 2021-11-12 17:36
@pkdash please follow up with Irene and ask her to check if she thinks there is still a problem with this resource that can be easily stated.  If not, ask her to delete this resource and lets close this issue.  While we are not sure, we think that the async and other stabilization improvements made since this was filed should have resolved the root causes, though this resource may still be in an inconsistent state and if not needed, we should just delete it and move on.

**Comment by dtarb** [comment] 2021-12-11 00:20
Working with @pkdash we've tested and determined that to the best of our knowledge async work has resolved this.  I deleted the problematic resource.

**Closed by dtarb** 2021-12-11 00:20 UTC
Labels: bug, File System, Pages and General HS Components
